return {
	mod_name = {
		en = "Holy Light",
		ru = "Holy Light",
		de = "Holy Light",
		fr = "Holy Light",
		["zh-cn"] = "Holy Light",
	},
	mod_description = {
		en = "Adds glow above pickups and crates in missions.",
		ru = "Добавляет свечение над предметами и ящиками в миссиях.",
		de = "Fugt Beuteobjekten und Kisten in Missionen ein Leuchten hinzu.",
		fr = "Ajoute une lueur au-dessus des objets et des caisses en mission.",
		["zh-cn"] = "为任务中的拾取物和箱子添加发光效果。",
	},
	general_group = {
		en = "\238\128\140 DISPLAY",
		ru = "\238\128\140 ОТОБРАЖЕНИЕ",
		de = "\238\128\140 ANZEIGE",
		fr = "\238\128\140 AFFICHAGE",
		["zh-cn"] = "\238\128\140 显示设置",
	},
	targets_group = {
		en = "\238\128\161 ITEM CATEGORIES",
		ru = "\238\128\161 КАТЕГОРИИ ПРЕДМЕТОВ",
		de = "\238\128\161 GEGENSTANDSKATEGORIEN",
		fr = "\238\128\161 CATEGORIES D'OBJETS",
		["zh-cn"] = "\238\128\161 物品类别",
	},
	expedition_group = {
		en = "\238\128\161 EXPEDITION ITEMS",
		ru = "\238\128\161 ПРЕДМЕТЫ ЭКСПЕДИЦИИ",
		de = "\238\128\161 EXPEDITIONS-GEGENSTÄNDE",
		fr = "\238\128\161 OBJETS D'EXPÉDITION",
		["zh-cn"] = "\238\128\161 远征物品",
	},
	enable_mod = {
		en = "Enable mod",
		ru = "Включить мод",
		de = "Mod aktivieren",
		fr = "Activer le mod",
		["zh-cn"] = "启用模组",
	},
	effect_height = {
		en = "Height offset",
		ru = "Смещение по высоте",
		de = "Hohenversatz",
		fr = "Decalage en hauteur",
		["zh-cn"] = "高度偏移",
	},
	enable_stimms = {
		en = "Glow on stimms",
		ru = "Свечение на стимуляторах",
		de = "Leuchten auf Stimms",
		fr = "Lueur sur les stimms",
		["zh-cn"] = "强化针发光",
	},
	enable_ammo_pickups = {
		en = "Glow on ammo pickups",
		ru = "Свечение на патронах",
		de = "Leuchten auf Munitionsaufnahmen",
		fr = "Lueur sur les munitions",
		["zh-cn"] = "弹药发光",
	},
	enable_grenade_pickups = {
		en = "Glow on grenade pickups",
		ru = "Свечение на гранатах",
		de = "Leuchten auf Granaten",
		fr = "Lueur sur les grenades",
		["zh-cn"] = "手雷发光",
	},
	enable_ammo_crates = {
		en = "Glow on ammo crates",
		ru = "Свечение на ящиках боеприпасов",
		de = "Leuchten auf Munitionskisten",
		fr = "Lueur sur les caisses de munitions",
		["zh-cn"] = "弹药箱发光",
	},
	enable_medical_crates = {
		en = "Glow on medical crates",
		ru = "Свечение на медицинских ящиках",
		de = "Leuchten auf Medizinkisten",
		fr = "Lueur sur les caisses medicales",
		["zh-cn"] = "医疗箱发光",
	},
	enable_plasteel_pickups = {
		en = "Glow on plasteel",
		ru = "Свечение на пластиле",
		de = "Leuchten auf Plasteel",
		fr = "Lueur sur le plastacier",
		["zh-cn"] = "塑钢发光",
	},
	enable_diamantine_pickups = {
		en = "Glow on diamantine",
		ru = "Свечение на диамантине",
		de = "Leuchten auf Diamantin",
		fr = "Lueur sur la diamantine",
		["zh-cn"] = "金精发光",
	},
	enable_grimoires = {
		en = "Glow on grimoires",
		ru = "Свечение на гримуарах",
		de = "Leuchten auf Grimoiren",
		fr = "Lueur sur les grimoires",
		["zh-cn"] = "魔典发光",
	},
	enable_scriptures = {
		en = "Glow on scriptures",
		ru = "Свечение на писаниях",
		de = "Leuchten auf Schriften",
		fr = "Lueur sur les ecritures",
		["zh-cn"] = "圣卷发光",
	},
	enable_expedition_salvage = {
		en = "Glow on salvage",
		ru = "Свечение на ломе",
		de = "Leuchten auf Bergungsgut",
		fr = "Lueur sur la récupération",
		["zh-cn"] = "打捞物发光",
	},
	enable_expedition_tech_remnants = {
		en = "Glow on tech remnants",
		ru = "Свечение на техноостанках",
		de = "Leuchten auf Tech-Überresten",
		fr = "Lueur sur les vestiges technologiques",
		["zh-cn"] = "科技残骸发光",
	},
	enable_expedition_reliquaries = {
		en = "Glow on reliquaries",
		ru = "Свечение на реликвариях",
		de = "Leuchten auf Reliquiare",
		fr = "Lueur sur les reliquaires",
		["zh-cn"] = "圣物匣发光",
	},
	enable_expedition_strikes = {
		en = "Glow on strike grenades",
		ru = "Свечение на страйк-гранатах",
		de = "Leuchten auf Strike-Granaten",
		fr = "Lueur sur les grenades de frappe",
		["zh-cn"] = "打击手雷发光",
	},
	enable_expedition_mines = {
		en = "Glow on servo-triggered mines",
		ru = "Свечение на сервоминах",
		de = "Leuchten auf servogesteuerten Minen",
		fr = "Lueur sur les mines à déclenchement servo",
		["zh-cn"] = "伺服触发地雷发光",
	},
	enable_expedition_luggables = {
		en = "Glow on explosive luggables",
		ru = "Свечение на переносимых взрывных бочках",
		de = "Leuchten auf explosiven Fässern",
		fr = "Lueur sur les barils explosifs transportables",
		["zh-cn"] = "可搬运爆炸桶发光",
	},
}
