local mod = get_mod("TeamKills")

local Color = Color

local killstreak_widget_settings = {
    shading_environment = "content/shading_environments/ui/system_menu",
    killsboard_size = {1060, 900},
    killsboard_max_height = 990,
    killsboard_min_height = 200,
    killsboard_base_z = 500,
    killsboard_row_height = 16,
    killsboard_row_header_height = 26,
    killsboard_column_kills_width = 75,
    killsboard_column_damage_width = 140,
    killsboard_column_player_width = 215,
    killsboard_column_player_bg_width = 214,
    killsboard_column_header_width = 200,
    killsboard_category_text_offset = 10,
    killsboard_fade_length = 0.1,
    killsboard_font_size = 12,
    killsboard_font_size_header = 14,
    killsboard_font_size_player_names = 16,
    killsboard_row_color_dark_func = Color.terminal_grid_background,
    killsboard_row_color_light_func = Color.terminal_grid_background,
    killsboard_row_color_dark_alpha = 20,
    killsboard_row_color_light_alpha = 40,
    killsboard_row_color_highlight_alpha = 220,
    killsboard_header_bg_alpha = 0,
    killsboard_subheader_bg_alpha = 0,
    killsboard_total_bg_alpha = 0,
    killsboard_group_header_bg_alpha = 0,
    killsboard_spacer_bg_alpha = 0,
    killsboard_background_alpha = 220,
    killsboard_background_width_offset = 10,
    killsboard_rows_top_offset = 0,
    killsboard_rows_bottom_offset = 0,
    killsboard_show_empty_categories = false,
    killsboard_category_text_horizontal_alignment = "left",
    killsboard_category_text_vertical_alignment = "center",
    killsboard_category_text_color_alpha = 255,
    killsboard_category_text_color_use_terminal = true,
    killsboard_category_text_white_alpha = 200,
    killsboard_column_text_horizontal_alignment = "center",
    killsboard_column_text_vertical_alignment = "center",
    killsboard_column_text_color_alpha = 255,
    killsboard_column_text_color_use_terminal = true,
    killsboard_column_text_white_alpha = 200,
    killsboard_no_data_text_horizontal_alignment = "center",
    killsboard_no_data_text_vertical_alignment = "center",
    killsboard_no_data_text_offset = 10,
    killsboard_no_data_text_color_func = Color.terminal_text_body_sub_header,
    killsboard_no_data_text_color_alpha = 255,
}

return killstreak_widget_settings
