local mod = get_mod("MourningstarCommandWheel")

return {
  name = mod:localize("mod_name"),
  description = mod:localize("mod_description"),
  is_togglable = false,
  options = {
    widgets = {
      {
        setting_id = "command_wheel_group",
        type = "group",
        title = "i18n_command_wheel_section",
        sub_widgets = {
          {
            setting_id      = "open_command_wheel_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "held",
            keybind_type    = "function_call",
            function_name   = "command_wheel_held",
          },
        },
      },
      {
        setting_id = "hotkeys_group",
        type = "group",
        title = "i18n_hotkeys_section",
        sub_widgets = {
          {
            setting_id = "enable_in_psykhanium",
            type = "checkbox",
            default_value = false,
            title = "enable_in_psykhanium",
            tooltip_text = "enable_in_psykhanium_description",
          },
          {
            setting_id = "enable_toggle_view",
            type = "checkbox",
            default_value = false,
            title = "enable_toggle_view",
            tooltip_text = "enable_toggle_view_description",
          },
          {
            setting_id      = "open_inventory_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_inventory_background_view",
          },
          {
            setting_id      = "open_change_character_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_change_character",
          },
          {
            setting_id      = "open_barber_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_barber_vendor_background_view",
          },
          {
            setting_id      = "open_contracts_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_contracts_background_view",
          },
          {
            setting_id      = "open_crafting_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_crafting_view",
          },
          {
            setting_id      = "open_credits_vendor_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_credits_vendor_background_view",
          },
          {
            setting_id      = "open_mission_board_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_mission_board_view",
          },
          {
            setting_id      = "open_premium_store_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_store_view",
          },
          {
            setting_id      = "open_training_grounds_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_training_grounds_view",
          },
          {
            setting_id      = "open_social_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_social_view",
          },
          {
            setting_id      = "open_commissary_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_commissary_view",
          },
          {
            setting_id      = "open_penance_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_penance_overview_view",
          },
          {
            setting_id      = "open_havoc_background_view",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_havoc_background_view",
          },
          {
            setting_id      = "open_group_finder_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_group_finder_view",
          },
        },
      },
    }
  }
}
