local mod = get_mod("MourningstarCommandWheel")

return {
  name = mod:localize("mod_name"),
  description = mod:localize("mod_description"),
  is_togglable = false,
  options = {
    widgets = {
      {
        setting_id = "command_wheel_group",
        type = "group",
        title = "i18n_command_wheel_section",
        sub_widgets = {
          {
            setting_id      = "open_command_wheel_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "held",
            keybind_type    = "function_call",
            function_name   = "command_wheel_held",
          },
          {
            setting_id = "enable_in_psykhanium_wheel",
            type = "checkbox",
            default_value = true,
            title = "enable_in_psykhanium_wheel",
            tooltip_text = "enable_in_psykhanium_wheel_description",
          },
        },
      },
      {
        setting_id = "hotkeys_group",
        type = "group",
        title = "i18n_hotkeys_section",
        sub_widgets = {
          {
            setting_id = "enable_in_psykhanium",
            type = "checkbox",
            default_value = false,
            title = "enable_in_psykhanium",
            tooltip_text = "enable_in_psykhanium_description",
          },
          {
            setting_id = "enable_toggle_view",
            type = "checkbox",
            default_value = false,
            title = "enable_toggle_view",
            tooltip_text = "enable_toggle_view_description",
          },
          {
            setting_id      = "open_inventory_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_inventory_background_view",
          },
          {
            setting_id      = "open_change_character_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_change_character",
          },
          {
            setting_id      = "open_barber_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_barber_vendor_background_view",
          },
          {
            setting_id      = "open_contracts_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_contracts_background_view",
          },
          {
            setting_id      = "open_crafting_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_crafting_view",
          },
          {
            setting_id      = "open_credits_vendor_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_credits_vendor_background_view",
          },
          {
            setting_id      = "open_mission_board_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_mission_board_view",
          },
          {
            setting_id      = "open_premium_store_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_store_view",
          },
          {
            setting_id      = "open_training_grounds_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_training_grounds_view",
          },
          {
            setting_id      = "open_social_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_social_view",
          },
          {
            setting_id      = "open_commissary_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_commissary_view",
          },
          {
            setting_id      = "open_penance_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_penance_overview_view",
          },
          {
            setting_id      = "open_havoc_background_view",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_havoc_background_view",
          },
          {
            setting_id      = "open_group_finder_view_key",
            type            = "keybind",
            default_value   = {},
            keybind_trigger = "pressed",
            keybind_type    = "function_call",
            function_name   = "open_group_finder_view",
          },
        },
      },
      {
        setting_id = "gamepad_supergroup",
        type = "group",
        title = "i18n_gamepad_section",
        sub_widgets = {
          {
            setting_id = "playstation_group",
            type = "group",
            title = "i18n_playstation_section",
            sub_widgets = {
              {
                setting_id = "playstation_controller_button",
                type = "dropdown",
                default_value = "default",
                title = "playstation_controller_button",
                tooltip_text = "playstation_controller_button_description",
                options = {
                  { text = "playstation_controller_button_default", value = "default" },
                  { text = "playstation_controller_button_l1", value = "ps4_controller_l1" },
                  { text = "playstation_controller_button_l2", value = "ps4_controller_l2" },
                  { text = "playstation_controller_button_l3", value = "ps4_controller_l3" },
                  { text = "playstation_controller_button_r1", value = "ps4_controller_r1" },
                  { text = "playstation_controller_button_r2", value = "ps4_controller_r2" },
                  { text = "playstation_controller_button_r3", value = "ps4_controller_r3" },
                  { text = "playstation_controller_button_triangle", value = "ps4_controller_triangle" },
                  { text = "playstation_controller_button_circle", value = "ps4_controller_circle" },
                  { text = "playstation_controller_button_cross", value = "ps4_controller_cross" },
                  { text = "playstation_controller_button_square", value = "ps4_controller_square" },
                  { text = "playstation_controller_button_d_up", value = "ps4_controller_d_up" },
                  { text = "playstation_controller_button_d_down", value = "ps4_controller_d_down" },
                  { text = "playstation_controller_button_d_left", value = "ps4_controller_d_left" },
                  { text = "playstation_controller_button_d_right", value = "ps4_controller_d_right" },
                  { text = "playstation_controller_button_options", value = "ps4_controller_options" },
                  { text = "playstation_controller_button_touch", value = "ps4_controller_touch" },
                },
              },
            },
          },
        },
      },
    }
  }
}
