local mod = get_mod("TeamKills")

return {
	name = mod:localize("i18n_mod_title"),
	description = mod:localize("i18n_mod_description"),
	is_togglable = true,
	allow_rehooking = true,
	options = {
		localize = true,
		widgets = {
			{
				setting_id = "opt_hud_team_kills_tracker",
				type = "group",
				title = "i18n_hud_team_kills_tracker_title",
				sub_widgets = {
					{
						setting_id = "opt_hud_counter_mode",
						type = "dropdown",
						title = "i18n_hud_counter_mode",
						default_value = 1,
						options = {
							{text = "i18n_hud_counter_mode_kills_damage", value = 1},
							{text = "i18n_hud_counter_mode_kills", value = 2},
							{text = "i18n_hud_counter_mode_damage", value = 3},
							{text = "i18n_hud_counter_mode_last_damage", value = 4},
							{text = "i18n_hud_counter_mode_kills_last_damage", value = 5},
							{text = "i18n_hud_counter_mode_kills_total_last_damage", value = 6},
						},
					},
					{
						setting_id = "opt_show_team_summary",
						type = "dropdown",
						title = "i18n_show_team_summary",
						default_value = 1,
						options = {
							{text = "i18n_show_team_summary_show", value = 1},
							{text = "i18n_show_team_summary_hide", value = 2},
						},
					},
					{
						setting_id = "opt_display_mode",
						type = "dropdown",
						title = "i18n_display_mode",
						default_value = 1,
						options = {
							{text = "i18n_display_mode_all", value = 1},
							{text = "i18n_display_mode_only_me", value = 2},
							{text = "i18n_display_mode_except_me", value = 4},
							{text = "i18n_display_mode_hide_all", value = 3},
						},
					},
					{
						setting_id = "opt_show_killstreaks",
						type = "dropdown",
						title = "i18n_show_killstreaks",
						default_value = 1,
						options = {
							{text = "i18n_show_killstreaks_show", value = 1},
							{text = "i18n_show_killstreaks_hide", value = 2},
						},
					},
					{
						setting_id = "opt_killstreak_difficulty",
						type = "dropdown",
						title = "i18n_killstreak_difficulty",
						default_value = 2,
						options = {
							{text = "i18n_killstreak_difficulty_recruit", value = 1},
							{text = "i18n_killstreak_difficulty_veteran", value = 2},
							{text = "i18n_killstreak_difficulty_ruthless", value = 3},
						},
					},
				},
			},
			-- {
			-- 	setting_id = "hud_boss_damage_tracker",
			-- 	type = "group",
			-- 	title = "hud_boss_damage_tracker_title",
			-- 	sub_widgets = {
			-- 		{
			-- 			setting_id = "boss_damage_placeholder",
			-- 			type = "dropdown",
			-- 			default_value = 1,
			-- 			options = {
			-- 				{text = "boss_damage_placeholder_text", value = 1},
			-- 			},
			-- 		},
			-- 	},
			-- },
			{
				setting_id = "opt_hud_general_settings",
				type = "group",
				title = "i18n_hud_general_settings_title",
				sub_widgets = {
					{
						setting_id = "opt_kills_color",
						type = "dropdown",
						title = "i18n_kills_color",
						default_value = "white",
						options = {
							{text = "i18n_color_white", value = "white"},
							{text = "i18n_color_red", value = "red"},
							{text = "i18n_color_green", value = "green"},
							{text = "i18n_color_blue", value = "blue"},
							{text = "i18n_color_yellow", value = "yellow"},
							{text = "i18n_color_orange", value = "orange"},
							{text = "i18n_color_purple", value = "purple"},
							{text = "i18n_color_cyan", value = "cyan"},
							{text = "i18n_color_teal", value = "teal"},
							{text = "i18n_color_gold", value = "gold"},
							{text = "i18n_color_purple_deep", value = "purple_deep"},
							{text = "i18n_color_magenta", value = "magenta"},
							{text = "i18n_color_orange_dark", value = "orange_dark"},
							{text = "i18n_color_orange_medium", value = "orange_medium"},
							{text = "i18n_color_amber", value = "amber"},
							{text = "i18n_color_grey", value = "grey"},
						},
					},
					{
						setting_id = "opt_damage_color",
						type = "dropdown",
						title = "i18n_damage_color",
						default_value = "orange",
						options = {
							{text = "i18n_color_white", value = "white"},
							{text = "i18n_color_red", value = "red"},
							{text = "i18n_color_green", value = "green"},
							{text = "i18n_color_blue", value = "blue"},
							{text = "i18n_color_yellow", value = "yellow"},
							{text = "i18n_color_orange", value = "orange"},
							{text = "i18n_color_purple", value = "purple"},
							{text = "i18n_color_cyan", value = "cyan"},
							{text = "i18n_color_teal", value = "teal"},
							{text = "i18n_color_gold", value = "gold"},
							{text = "i18n_color_purple_deep", value = "purple_deep"},
							{text = "i18n_color_magenta", value = "magenta"},
							{text = "i18n_color_orange_dark", value = "orange_dark"},
							{text = "i18n_color_orange_medium", value = "orange_medium"},
							{text = "i18n_color_amber", value = "amber"},
							{text = "i18n_color_grey", value = "grey"},
						},
					},
					{
						setting_id = "opt_last_damage_color",
						type = "dropdown",
						title = "i18n_last_damage_color",
						default_value = "orange",
						options = {
							{text = "i18n_color_white", value = "white"},
							{text = "i18n_color_red", value = "red"},
							{text = "i18n_color_green", value = "green"},
							{text = "i18n_color_blue", value = "blue"},
							{text = "i18n_color_yellow", value = "yellow"},
							{text = "i18n_color_orange", value = "orange"},
							{text = "i18n_color_purple", value = "purple"},
							{text = "i18n_color_cyan", value = "cyan"},
							{text = "i18n_color_teal", value = "teal"},
							{text = "i18n_color_gold", value = "gold"},
							{text = "i18n_color_purple_deep", value = "purple_deep"},
							{text = "i18n_color_magenta", value = "magenta"},
							{text = "i18n_color_orange_dark", value = "orange_dark"},
							{text = "i18n_color_orange_medium", value = "orange_medium"},
							{text = "i18n_color_amber", value = "amber"},
							{text = "i18n_color_grey", value = "grey"},
						},
					},
					{
						setting_id = "opt_show_background",
						type = "dropdown",
						title = "i18n_show_background",
						default_value = 1,
						options = {
							{text = "i18n_show_background_show", value = 1},
							{text = "i18n_show_background_hide", value = 2},
						},
					},
					{
						setting_id = "opt_font_size",
						type = "numeric",
						title = "i18n_font_size",
						default_value = 16,
						range = {15, 30},
					},
					{
						setting_id = "opt_opacity",
						type = "numeric",
						title = "i18n_opacity",
						default_value = 100,
						range = {0, 100},
					},
				},
			},
			{
				setting_id = "opt_killstreak_board",
				type = "group",
				title = "i18n_killstreak_board_title",
				sub_widgets = {
					{
						setting_id = "opt_show_killsboard",
						type = "dropdown",
						title = "i18n_show_killsboard",
						default_value = 1,
						options = {
							{text = "i18n_show_killsboard_show", value = 1},
							{text = "i18n_show_killsboard_hide", value = 2},
						},
					},
					{
						setting_id = "opt_show_killsboard_end_view",
						type = "dropdown",
						title = "i18n_show_killsboard_end_view",
						default_value = 1,
						options = {
							{text = "i18n_show_killsboard_end_view_show", value = 1},
							{text = "i18n_show_killsboard_end_view_hide", value = 2},
						},
					},
					{
						setting_id = "opt_open_killsboard",
						type = "keybind",
						title = "i18n_open_killsboard",
						default_value = {"f7"},
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "open_killsboard",
					},
				},
			},
        },
	},
}

