local mod = get_mod("TeamKills")

return {
	name = mod:localize("i18n_mod_title"),
	description = mod:localize("i18n_mod_description"),
	is_togglable = true,
	allow_rehooking = true,
	options = {
		localize = true,
		widgets = {
			{
				setting_id = "opt_hud_team_kills_tracker",
				type = "group",
				title = "i18n_hud_team_kills_tracker_title",
				sub_widgets = {
					{
						setting_id = "opt_show_team_kills_tracker",
						type = "checkbox",
						title = "i18n_show_team_kills_tracker",
						default_value = true,
						sub_widgets = {
							{
								setting_id = "opt_show_kills",
								type = "checkbox",
								title = "i18n_show_kills",
								default_value = true,
							},
							{
								setting_id = "opt_show_total_damage",
								type = "checkbox",
								title = "i18n_show_total_damage",
								default_value = true,
							},
							{
								setting_id = "opt_show_last_damage",
								type = "checkbox",
								title = "i18n_show_last_damage",
								default_value = false,
							},
						},
					},
					{
						setting_id = "opt_show_team_summary",
						type = "checkbox",
						title = "i18n_show_team_summary",
						default_value = true,
					},
					{
						setting_id = "opt_display_mode",
						type = "dropdown",
						title = "i18n_display_mode",
						default_value = 1,
						options = {
							{text = "i18n_display_mode_all", value = 1},
							{text = "i18n_display_mode_only_me", value = 2},
							{text = "i18n_display_mode_except_me", value = 4},
							{text = "i18n_display_mode_hide_all", value = 3},
						},
					},
					{
						setting_id = "opt_show_killstreaks",
						type = "checkbox",
						title = "i18n_show_killstreaks",
						default_value = true,
					},
					{
						setting_id = "opt_killstreak_difficulty",
						type = "dropdown",
						title = "i18n_killstreak_difficulty",
						default_value = 2,
						options = {
							{text = "i18n_killstreak_difficulty_recruit", value = 1},
							{text = "i18n_killstreak_difficulty_veteran", value = 2},
							{text = "i18n_killstreak_difficulty_ruthless", value = 3},
						},
					},
					{
						setting_id = "opt_killstreak_min_display",
						type = "numeric",
						title = "i18n_killstreak_min_display",
						default_value = 2,
						range = {1, 50},
					},
				},
			},
			{
				setting_id = "opt_hud_boss_damage_tracker",
				type = "group",
				title = "i18n_hud_boss_damage_tracker_title",
				sub_widgets = {
					{
						setting_id = "opt_show_boss_damage_tracker",
						type = "checkbox",
						title = "i18n_show_boss_damage_tracker",
						default_value = true,
						sub_widgets = {
							{
								setting_id = "opt_show_boss_total_damage",
								type = "checkbox",
								title = "i18n_show_boss_total_damage",
								default_value = true,
							},
							{
								setting_id = "opt_show_boss_last_damage",
								type = "checkbox",
								title = "i18n_show_boss_last_damage",
								default_value = false,
							},
						},
					},
				},
			},
			{
				setting_id = "opt_hud_shot_tracker",
				type = "group",
				title = "i18n_hud_shot_tracker_title",
				sub_widgets = {
					{
						setting_id = "opt_show_shot_tracker",
						type = "checkbox",
						title = "i18n_show_shot_tracker",
						default_value = true,
						sub_widgets = {
							{
								setting_id = "opt_show_shots_fired",
								type = "checkbox",
								title = "i18n_show_shots_fired",
								default_value = true,
							},
							{
								setting_id = "opt_show_shots_missed",
								type = "checkbox",
								title = "i18n_show_shots_missed",
								default_value = true,
							},
							{
								setting_id = "opt_show_head_shot_kill",
								type = "checkbox",
								title = "i18n_show_head_shot_kill",
								default_value = true,
							},
						},
					},
				},
			},
			{
				setting_id = "opt_hud_general_settings",
				type = "group",
				title = "i18n_hud_general_settings_title",
				sub_widgets = {
				{
					setting_id = "opt_kills_color",
					type = "dropdown",
					title = "i18n_kills_color",
					default_value = "white",
					options = {
						{text = "i18n_color_white", value = "white"},
						{text = "i18n_color_red", value = "red"},
						{text = "i18n_color_green", value = "green"},
						{text = "i18n_color_blue", value = "blue"},
						{text = "i18n_color_yellow", value = "yellow"},
						{text = "i18n_color_orange", value = "orange"},
						{text = "i18n_color_purple", value = "purple"},
						{text = "i18n_color_cyan", value = "cyan"},
						{text = "i18n_color_teal", value = "teal"},
						{text = "i18n_color_gold", value = "gold"},
						{text = "i18n_color_purple_deep", value = "purple_deep"},
						{text = "i18n_color_magenta", value = "magenta"},
						{text = "i18n_color_orange_dark", value = "orange_dark"},
						{text = "i18n_color_orange_medium", value = "orange_medium"},
						{text = "i18n_color_amber", value = "amber"},
						{text = "i18n_color_grey", value = "grey"},
					},
				},
				{
					setting_id = "opt_damage_color",
					type = "dropdown",
					title = "i18n_damage_color",
					default_value = "orange",
					options = {
						{text = "i18n_color_white", value = "white"},
						{text = "i18n_color_red", value = "red"},
						{text = "i18n_color_green", value = "green"},
						{text = "i18n_color_blue", value = "blue"},
						{text = "i18n_color_yellow", value = "yellow"},
						{text = "i18n_color_orange", value = "orange"},
						{text = "i18n_color_purple", value = "purple"},
						{text = "i18n_color_cyan", value = "cyan"},
						{text = "i18n_color_teal", value = "teal"},
						{text = "i18n_color_gold", value = "gold"},
						{text = "i18n_color_purple_deep", value = "purple_deep"},
						{text = "i18n_color_magenta", value = "magenta"},
						{text = "i18n_color_orange_dark", value = "orange_dark"},
						{text = "i18n_color_orange_medium", value = "orange_medium"},
						{text = "i18n_color_amber", value = "amber"},
						{text = "i18n_color_grey", value = "grey"},
					},
				},
				{
					setting_id = "opt_last_damage_color",
					type = "dropdown",
					title = "i18n_last_damage_color",
					default_value = "orange",
					options = {
						{text = "i18n_color_white", value = "white"},
						{text = "i18n_color_red", value = "red"},
						{text = "i18n_color_green", value = "green"},
						{text = "i18n_color_blue", value = "blue"},
						{text = "i18n_color_yellow", value = "yellow"},
						{text = "i18n_color_orange", value = "orange"},
						{text = "i18n_color_purple", value = "purple"},
						{text = "i18n_color_cyan", value = "cyan"},
						{text = "i18n_color_teal", value = "teal"},
						{text = "i18n_color_gold", value = "gold"},
						{text = "i18n_color_purple_deep", value = "purple_deep"},
						{text = "i18n_color_magenta", value = "magenta"},
						{text = "i18n_color_orange_dark", value = "orange_dark"},
						{text = "i18n_color_orange_medium", value = "orange_medium"},
						{text = "i18n_color_amber", value = "amber"},
						{text = "i18n_color_grey", value = "grey"},
					},
				},
					{
						setting_id = "opt_show_background",
						type = "checkbox",
						title = "i18n_show_background",
						default_value = true,
					},
					{
						setting_id = "opt_font_size",
						type = "numeric",
						title = "i18n_font_size",
						default_value = 16,
						range = {15, 30},
					},
					{
						setting_id = "opt_opacity",
						type = "numeric",
						title = "i18n_opacity",
						default_value = 100,
						range = {0, 100},
					},
				},
			},
			{
				setting_id = "opt_notifications",
				type = "group",
				title = "i18n_notifications_title",
				sub_widgets = {
					{
						setting_id = "opt_show_boss_death_notification",
						type = "checkbox",
						title = "i18n_show_boss_death_notification",
						default_value = true,
						sub_widgets = {
							{
								setting_id = "opt_show_killer_name_notification",
								type = "checkbox",
								title = "i18n_show_killer_name_notification",
								default_value = true,
							},
							{
								setting_id = "opt_show_last_hit_damage_notification",
								type = "checkbox",
								title = "i18n_show_last_hit_damage_notification",
								default_value = true,
							},
							{
								setting_id = "opt_show_total_damage_notification",
								type = "checkbox",
								title = "i18n_show_total_damage_notification",
								default_value = true,
							},
							{
								setting_id = "opt_show_max_damage_notification",
								type = "checkbox",
								title = "i18n_show_max_damage_notification",
								default_value = true,
							},
						},
					},
				},
			},
			{
				setting_id = "opt_killstreak_board",
				type = "group",
				title = "i18n_killstreak_board_title",
				sub_widgets = {
					{
						setting_id = "opt_show_killsboard",
						type = "checkbox",
						title = "i18n_show_killsboard",
						default_value = true,
						sub_widgets = {
							{
								setting_id = "opt_toggle_killsboard",
								type = "keybind",
								title = "i18n_toggle_killsboard",
								default_value = {},
								keybind_trigger = "pressed",
								keybind_type = "function_call",
								function_name = "toggle_killsboard",
							},
						},
					},
					{
						setting_id = "opt_show_killsboard_end_view",
						type = "checkbox",
						title = "i18n_show_killsboard_end_view",
						default_value = true,
					},
					{
						setting_id = "opt_highlight_my_killstreaks",
						type = "checkbox",
						title = "i18n_highlight_my_killstreaks",
						tooltip_text = "i18n_highlight_my_killstreaks_tooltip",
						default_value = true,
					},
					{
						setting_id = "opt_highlight_team_killstreaks",
						type = "checkbox",
						title = "i18n_highlight_team_killstreaks",
						tooltip_text = "i18n_highlight_team_killstreaks_tooltip",
						default_value = true,
					},
					{
						setting_id = "opt_show_killstreak_progress_in_killsboard",
						type = "checkbox",
						title = "i18n_show_killstreak_progress_in_killsboard",
						tooltip_text = "i18n_show_killstreak_progress_in_killsboard_tooltip",
						default_value = true,
					},
					{
						setting_id = "opt_show_category_totals_in_group_header",
						type = "checkbox",
						title = "i18n_show_category_totals_in_group_header",
						tooltip_text = "i18n_show_category_totals_in_group_header_tooltip",
						default_value = false,
					},
					{
						setting_id = "opt_show_enemy_list_in_groups",
						type = "checkbox",
						title = "i18n_show_enemy_list_in_groups",
						tooltip_text = "i18n_show_enemy_list_in_groups_tooltip",
						default_value = true,
					},
				},
			},
        },
	},
}

