return {
	mod_name = {
		en = "Division HUD",
		ru = "Division HUD",
		de = "Division HUD",
		["zh-cn"] = "全境封锁风格 HUD",
	},
	mod_description = {
		en = "Adds extra combat HUD styled like The Division.",
		ru = "Добавляет дополнительный боевой HUD в стиле The Division.",
		de = "Fügt ein zusätzliches Kampf-HUD im Stil von The Division hinzu.",
		["zh-cn"] = "添加《全境封锁》风格的额外战斗界面。",
	},
	divisionhud_super_layout = {
		en = "\238\128\140 DISPLAY",
		ru = "\238\128\140 ОТОБРАЖЕНИЕ",
		de = "\238\128\140 ANZEIGE",
		["zh-cn"] = "\238\128\140 显示设置",
	},
	divisionhud_visible = {
		en = "Show Division HUD",
		ru = "Показывать Division HUD",
		de = "Division HUD anzeigen",
		["zh-cn"] = "显示 Division HUD",
	},
	divisionhud_visible_description = {
		en = "When off, the entire Division HUD overlay is hidden.",
		ru = "Если выключено, скрыт весь оверлей Division HUD.",
		de = "Wenn deaktiviert, wird das gesamte Division-HUD-Overlay ausgeblendet.",
		["zh-cn"] = "关闭时隐藏整个 Division HUD。",
	},
	divisionhud_toggle_visible_keybind = {
		en = "Toggle HUD visibility",
		ru = "Переключить видимость HUD",
		de = "HUD-Sichtbarkeit umschalten",
		["zh-cn"] = "切换 HUD 显示",
	},
	divisionhud_toggle_visible_keybind_description = {
		en = "Same as «Show Division HUD» above.",
		ru = "То же, что чекбокс «Показывать Division HUD» выше.",
		de = "Entspricht oben «Division HUD anzeigen».",
		["zh-cn"] = "与上方「显示 Division HUD」相同。",
	},
	divisionhud_auto_switch = {
		en = string.rep("\194\160", 8) .. "Auto visibility switch",
		ru = string.rep("\194\160", 8) .. "Авто переключение видимости",
		de = string.rep("\194\160", 8) .. "Automatische Sichtbarkeit",
		["zh-cn"] = string.rep("\194\160", 8) .. "自动切换可见性",
	},
	divisionhud_auto_first_person = {
		en = "First person",
		ru = "От первого лица",
		de = "Ego-Perspektive",
		["zh-cn"] = "第一人称",
	},
	divisionhud_auto_first_person_description = {
		en = "Show HUD in first person.",
		ru = "Показывать HUD от первого лица.",
		de = "HUD in der Ego-Perspektive anzeigen.",
		["zh-cn"] = "第一人称时显示。",
	},
	divisionhud_auto_third_person = {
		en = "Third person",
		ru = "От третьего лица",
		de = "Dritte Person",
		["zh-cn"] = "第三人称",
	},
	divisionhud_auto_third_person_description = {
		en = "Show HUD in third person.",
		ru = "Показывать HUD от третьего лица.",
		de = "HUD in der Third-Person-Ansicht anzeigen.",
		["zh-cn"] = "第三人称时显示。",
	},
	divisionhud_auto_slot_device = {
		en = "Device in hand",
		ru = "Устройство в руках",
		de = "Gerät in der Hand",
		["zh-cn"] = "手持设备",
	},
	divisionhud_auto_slot_device_description = {
		en = "If you hold a device: off — hide Division HUD. On — do not hide.",
		ru = "Если в руках устройство: выкл — скрыть Division HUD. Вкл — не скрывать.",
		de = "Wenn du ein Gerät hältst: Aus — Division HUD ausblenden. Ein — nicht ausblenden.",
		["zh-cn"] = "手持设备时：关 — 隐藏 Division HUD；开 — 不隐藏。",
	},
	divisionhud_placement = {
		en = string.rep("\194\160", 8) .. "Position, opacity & scale",
		ru = string.rep("\194\160", 8) .. "Позиция, прозрачность и масштаб",
		de = string.rep("\194\160", 8) .. "Position, Deckkraft & Skalierung",
		["zh-cn"] = string.rep("\194\160", 8) .. "位置、不透明度与缩放",
	},
	position_x = {
		en = "Offset X",
		ru = "Смещение по X",
		de = "Versatz X",
		["zh-cn"] = "水平偏移 X",
	},
	position_x_description = {
		en = "Horizontal offset from the screen center in logical pixels (reference canvas 1920×1080). Range ±960. Negative moves the HUD left, positive moves it right. The root block is center-aligned.",
		ru = "Горизонтальное смещение от центра экрана в логических пикселях (эталонный холст 1920×1080). Диапазон ±960. Отрицательные значения — влево, положительные — вправо. Корневой блок привязан к центру экрана.",
		de = "Horizontaler Versatz von der Bildschirmmitte in logischen Pixeln (Referenzfläche 1920×1080). Bereich ±960. Negative Werte verschieben das HUD nach links, positive nach rechts. Der Wurzelblock ist mittig ausgerichtet.",
		["zh-cn"] = "以屏幕中心为基准的水平偏移（参考分辨率 1920×1080），范围 ±960。负值左移，正值右移。根节点默认居中。",
	},
	position_y = {
		en = "Offset Y",
		ru = "Смещение по Y",
		de = "Versatz Y",
		["zh-cn"] = "垂直偏移 Y",
	},
	position_y_description = {
		en = "Vertical offset from the screen center in logical pixels (reference canvas 1920×1080). Range ±540. Negative moves the HUD up, positive moves it down. The root block is center-aligned.",
		ru = "Вертикальное смещение от центра экрана в логических пикселях (эталонный холст 1920×1080). Диапазон ±540. Отрицательные значения — вверх, положительные — вниз. Корневой блок привязан к центру экрана.",
		de = "Vertikaler Versatz von der Bildschirmmitte in logischen Pixeln (Referenzfläche 1920×1080). Bereich ±540. Negative Werte verschieben das HUD nach oben, positive nach unten. Der Wurzelblock ist mittig ausgerichtet.",
		["zh-cn"] = "以屏幕中心为基准的垂直偏移（参考分辨率 1920×1080），范围 ±540。负值上移，正值下移。根节点默认居中。",
	},
	opacity = {
		en = "Opacity",
		ru = "Прозрачность",
		de = "Deckkraft",
		["zh-cn"] = "不透明度",
	},
	hud_scale = {
		en = "Scale",
		ru = "Масштаб",
		de = "Skalierung",
		["zh-cn"] = "缩放",
	},
	hud_scale_description = {
		en = "Scale multiplier applied to the whole Division HUD (reference canvas 1920×1080). Values below 1 shrink the HUD, values above 1 enlarge it.",
		ru = "Множитель масштаба, применяемый ко всему Division HUD (эталонный холст 1920×1080). Значения меньше 1 уменьшают HUD, больше 1 — увеличивают.",
		de = "Skalierungsfaktor für das gesamte Division HUD (Referenzfläche 1920×1080). Werte unter 1 verkleinern das HUD, Werte über 1 vergrößern es.",
		["zh-cn"] = "对整个 Division HUD 应用的缩放倍率（参考分辨率 1920×1080）。小于1缩小，大于1放大。",
	},
	divisionhud_super_bars = {
		en = "\238\128\178 COMBAT HUD",
		ru = "\238\128\178 БОЕВОЙ HUD",
		de = "\238\128\178 KAMPF-HUD",
		["zh-cn"] = "\238\128\178 战斗界面",
	},
	show_stamina_bar = {
		en = "Stamina and dodge bar",
		ru = "Полоса стамины и уворотов",
		de = "Ausdauer- und Ausweichleiste",
		["zh-cn"] = "体力与闪避条",
	},
	show_toughness_bar = {
		en = "Toughness bar",
		ru = "Полоса стойкости",
		de = "Widerstandsleiste",
		["zh-cn"] = "韧性条",
	},
	show_health_bar = {
		en = "Health bar",
		ru = "Полоса здоровья",
		de = "Gesundheitsleiste",
		["zh-cn"] = "生命值条",
	},
	show_ability_timer = {
		en = "Ability bar",
		ru = "Полоса способности",
		de = "Fähigkeitsleiste",
		["zh-cn"] = "技能冷却条",
	},
	show_ability_icon = {
		en = "Ability icon",
		ru = "Иконка способности",
		de = "Fähigkeitssymbol",
		["zh-cn"] = "技能图标",
	},
	stimm_slot_icon_tint_by_type = {
		en = "Color pocket stimm icon",
		ru = "Цвет иконки шприца",
		de = "Stimm-Symbol im Taschenplatz einfärben",
		["zh-cn"] = "注射器图标按类型着色",
	},
	stimm_slot_icon_tint_by_type_description = {
		en = "When enabled, the pocket stimm icon in the Division HUD strip is tinted by syringe template (speed, power, corruption cleanse, ability boost, broker syringe, etc.) using built-in colors. When off, the icon uses the default white tint.",
		ru = "Если включено, иконка карманного шприца в полоске Division HUD окрашивается по шаблону шприца (скорость, сила, снятие порчи, усиление способности, шприц брокера и т.д.) встроенными цветами. Если выключено — обычный белый тон.",
		de = "Wenn aktiviert, wird das Stimm-Symbol im Taschenplatz der Division-HUD-Leiste anhand der Spritzenvorlage eingefärbt (Geschwindigkeit, Kraft, Verderbnisreinigung, Fähigkeitsverstärkung, Broker-Spritze usw.) und nutzt integrierte Farben. Wenn deaktiviert, verwendet das Symbol die standardmäßige weiße Färbung.",
		["zh-cn"] = "启用后，根据注射器类型（速度、力量、腐蚀清除、技能强化、巢都渣滓注射器等）使用内置颜色为图标着色。关闭时使用默认白色。",
	},
	ammo_text_color_by_fraction = {
		en = "Ammo text color by remaining fraction",
		ru = "Цвет патронов по доле боезапаса",
		de = "Munitionstextfarbe nach verbleibendem Anteil",
		["zh-cn"] = "弹药文字按剩余比例变色",
	},
	ammo_text_color_by_fraction_description = {
		en = "When enabled, the large ammo numbers tint by total ammo fraction: above 75% main, above 50% low, above 25% medium, 25% or less high. When off, they use the default main color.",
		ru = "Если включено, крупные цифры патронов окрашиваются по доле боезапаса: выше 75% — основной цвет; выше 50% и не выше 75% — низкий запас; выше 25% и не выше 50% — средний; 25% и ниже — критический. Если выключено — обычный основной цвет.",
		de = "Wenn aktiviert, werden die großen Munitionszahlen nach dem Gesamtmunitionsanteil eingefärbt: über 75% Hauptfarbe, über 50% niedrig, über 25% mittel, 25% oder weniger hoch. Wenn deaktiviert, verwenden sie die standardmäßige Hauptfarbe.",
		["zh-cn"] = "启用后，大号弹药数字按剩余比例变色：75%以上为主色，50%–75%为低量色，25%–50%为中量色，25%及以下为警告色。关闭时使用默认主色。",
	},
	ammo_size_big = {
		en = "big",
		ru = "big",
		de = "big",
		["zh-cn"] = "big",
	},
	grenade_color_by_fraction = {
		en = "Grenade slot color by charge fraction",
		ru = "Цвет гранаты по доле зарядов",
		de = "Granatenplatzfarbe nach Ladungsanteil",
		["zh-cn"] = "手雷槽按充能比例着色",
	},
	grenade_color_by_fraction_description = {
		en = "When enabled, the grenade ability slot icon and counter tint by remaining charges, using the same color bands and fraction thresholds as the large ammo numbers. When off, the slot uses the default colors.",
		ru = "Если включено, иконка и счётчик слота гранаты окрашиваются по доле оставшихся зарядов — те же цветовые полосы и пороги доли, что у крупного текста патронов. Если выключено — цвета по умолчанию.",
		de = "Wenn aktiviert, werden Symbol und Zähler des Granaten-Fähigkeitsplatzes nach verbleibenden Ladungen eingefärbt, mit denselben Farbbereichen und Anteilsschwellen wie die großen Munitionszahlen. Wenn deaktiviert, verwendet der Platz die Standardfarben.",
		["zh-cn"] = "启用后，手雷图标与计数按剩余充能比例着色，规则与弹药数字一致。关闭时使用默认颜色。",
	},
	wielded_weapon_icon_state_colors = {
		en = "Current weapon icon colors",
		ru = "Цвет текущего оружия",
		de = "Farben des aktuellen Waffensymbols",
		["zh-cn"] = "当前武器图标按状态着色",
	},
	wielded_weapon_icon_state_colors_description = {
		en = "When enabled, tints the wielded-weapon strip icon for weapons included in this mod's internal list by inactive, active, and optional cooldown states. Other weapons stay full white.",
		ru = "Если включено, для оружия из внутреннего списка мода окрашивает иконку текущего оружия в полоске Division HUD по неактивному, активному и при необходимости кулдауну. Для остального оружия остаётся обычный белый.",
		de = "Wenn aktiviert, färbt es das Symbol der geführten Waffe in der Leiste für Waffen aus der internen Liste dieses Mods nach inaktivem, aktivem und optionalem Abklingzeit-Zustand ein. Andere Waffen bleiben vollständig weiß.",
		["zh-cn"] = "启用后，模组支持的武器会按未激活、激活、冷却状态变色，其他武器保持白色。",
	},
	buff_rows_enabled = {
		en = "Buff rows",
		ru = "Строки баффов",
		de = "Buff-Zeilen",
		["zh-cn"] = "增益行",
	},
	buff_rows_enabled_description = {
		en = "Displays active player buffs in rows below the stamina/dodge bars (up to 15 buffs, 5 per row).",
		ru = "Отображает активные бафы игрока рядами ниже полос стамины/уклонения (до 15 бафов, по 5 в ряд).",
		de = "Zeigt aktive Spieler-Buffs in Zeilen unter den Ausdauer-/Ausweichleisten an (bis zu 15 Buffs, 5 pro Zeile).",
		["zh-cn"] = "在耐力/闪避栏下方以行显示玩家的激活增益（最多15个，每行5个）。",
	},
	main_strip_background_fill = {
		en = "Weapon & ammo slots background",
		ru = "Фон под слотами оружия и патронов",
		de = "Hintergrund für Waffen- und Munitionsplätze",
		["zh-cn"] = "武器与弹药槽背景",
	},
	main_strip_background_fill_description = {
		en = "Fill behind the weapon and ammo slots (Division HUD).",
		ru = "Заливка под слотами оружия и патронов (Division HUD).",
		de = "Füllung hinter den Waffen- und Munitionsplätzen (Division HUD).",
		["zh-cn"] = "武器与弹药槽背后的填充（Division HUD）。",
	},
	proximity_strip_background_fill = {
		en = "Detected items area background",
		ru = "Фон под иконками обнаруженных предметов",
		de = "Hintergrund des Bereichs erkannter Gegenstände",
		["zh-cn"] = "探测物品图标区域背景",
	},
	proximity_strip_background_fill_description = {
		en = "Fill behind proximity item icons; separate from weapon/ammo slots.",
		ru = "Заливка под иконками обнаруженных предметов (proximity), отдельно от слотов оружия и патронов.",
		de = "Füllung hinter Symbolen von Gegenständen in der Nähe; getrennt von Waffen-/Munitionsplätzen.",
		["zh-cn"] = "近距离探测到的物品图标背后的填充（与武器/弹药槽分开）。",
	},
	main_strip_background_fill_weapon_hud_plain = {
		en = "Weapon fill only",
		ru = "Только оружейная заливка",
		de = "Nur Waffenfüllung",
		["zh-cn"] = "仅武器填充",
	},
	main_strip_background_fill_weapon_hud = {
		en = "Weapon fill + frame",
		ru = "Оружейная заливка + рамка",
		de = "Waffenfüllung + Rahmen",
		["zh-cn"] = "武器填充 + 边框",
	},
	main_strip_background_fill_terminal = {
		en = "Terminal gradient green",
		ru = "Терминальный градиент зеленый",
		de = "Terminal-Verlauf grün",
		["zh-cn"] = "终端渐变绿色",
	},
	main_strip_background_fill_black = {
		en = "Terminal gradient black",
		ru = "Терминальный градиент черный",
		de = "Terminal-Verlauf schwarz",
		["zh-cn"] = "终端渐变黑色",
	},
	divisionhud_super_danger_zone = {
		en = "\238\128\161 DANGER ZONE",
		ru = "\238\128\161 ОПАСНАЯ ЗОНА",
		de = "\238\128\161 GEFAHRENBEREICH",
		["zh-cn"] = "\238\128\161 危险区域",
	},
	danger_zone_label = {
		en = "Danger zone",
		ru = "Опасная зона",
		de = "Gefahrenbereich",
		["zh-cn"] = "危险区域",
	},
	danger_zone_in_zone = {
		en = "In blast\nzone",
		ru = "В зоне\nпоражения",
		de = "Im Explosions-\nbereich",
		["zh-cn"] = "位于\n危险区",
	},
	danger_zone_enabled = {
		en = "Enable danger zone",
		ru = "Включить опасную зону",
		de = "Gefahrenbereich aktivieren",
		["zh-cn"] = "启用危险区域",
	},
	danger_zone_enabled_description = {
		en = "Shows the Danger zone block when you approach tracked hazardous areas.",
		ru = "Показывает блок Danger zone при приближении к отслеживаемым опасным зонам.",
		de = "Zeigt den Gefahrenbereich-Block an, wenn du dich verfolgten Gefahrenzonen näherst.",
		["zh-cn"] = "接近已追踪的危险区域时显示 Danger zone 模块。",
	},
	danger_zone_radius = {
		en = "Detection distance (m)",
		ru = "Расстояние обнаружения (м)",
		de = "Erkennungsentfernung (m)",
		["zh-cn"] = "检测距离（米）",
	},
	danger_zone_radius_description = {
		en = "Maximum distance in meters from the edge of a tracked danger zone to show the Danger zone block.",
		ru = "Максимальное расстояние в метрах от границы отслеживаемой опасной зоны, на котором показывается блок Danger zone.",
		de = "Maximale Entfernung in Metern vom Rand eines verfolgten Gefahrenbereichs, bei der der Gefahrenbereich-Block angezeigt wird.",
		["zh-cn"] = "距离已追踪危险区域边缘的最大显示距离（米）。",
	},
	danger_zone_los_check = {
		en = "Account for obstacles (line of sight)",
		ru = "Учитывать препятствия (видимость)",
		de = "Hindernisse berücksichtigen (Sichtlinie)",
		["zh-cn"] = "考虑遮挡物（视线）",
	},
	danger_zone_los_check_description = {
		en = "Ignore danger sources separated from you by walls, floors or bridges (line-of-sight raycast). Disable to use distance only.",
		ru = "Игнорировать источники опасности, отделённые от вас стенами, полом или мостом (проверка прямой видимости лучом). Отключите, чтобы учитывать только расстояние.",
		de = "Ignoriert Gefahrenquellen, die durch Wände, Böden oder Brücken von dir getrennt sind (Sichtlinien-Raycast). Deaktivieren, um nur die Entfernung zu verwenden.",
		["zh-cn"] = "忽略被墙壁、楼板或桥梁分隔的危险源（视线射线检测）。关闭则仅按距离判定。",
	},
	danger_zone_show_daemonhost = {
		en = "Daemonhost",
		ru = "Демонхост",
		de = "Dämonenhost",
		["zh-cn"] = "恶魔宿主",
	},
	danger_zone_show_daemonhost_description = {
		en = "Show alerts for this unit (spawn and alert stages).",
		ru = "Показывать оповещения для этого юнита (появление и стадии тревоги).",
		de = "Warnungen für diese Einheit anzeigen (Erscheinen und Alarmstufen).",
		["zh-cn"] = "显示该单位的警报（出生与各警戒阶段）。",
	},
	danger_zone_show_daemonhost_aura = {
		en = "Daemonhost corruption aura",
		ru = "Аура демонхоста",
		de = "Verderbnis-Aura des Dämonenhosts",
		["zh-cn"] = "恶魔宿主腐化光环",
	},
	danger_zone_show_daemonhost_aura_description = {
		en = "Show the radius of this corruption aura (area effect around the unit).",
		ru = "Показывать радиус этой коррумпирующей ауры (область воздействия вокруг юнита).",
		de = "Radius dieser Verderbnis-Aura anzeigen (Flächeneffekt um die Einheit).",
		["zh-cn"] = "显示该腐化光环的半径（单位周围的区域效果）。",
	},
	danger_zone_show_poxburster = {
		en = "Poxburster",
		ru = "Поксбёрстер",
		de = "Poxburster",
		["zh-cn"] = "瘟疫爆弹者",
	},
	danger_zone_show_poxburster_description = {
		en = "Show alerts for this explosion threat — uses its explosion radius.",
		ru = "Показывать оповещения для этой взрывной угрозы — используется её радиус взрыва.",
		de = "Warnungen für diese Explosionsgefahr anzeigen — verwendet ihren Explosionsradius.",
		["zh-cn"] = "显示该爆炸威胁的警报（使用其爆炸半径）。",
	},
	danger_zone_show_tox_flamer = {
		en = "Tox flamer",
		ru = "Токс-огнемётчик",
		de = "Tox-Flamer",
		["zh-cn"] = "毒焰喷射者",
	},
	danger_zone_show_tox_flamer_description = {
		en = "Show alerts for this fire threat (backpack/flare explosions). Uses its explosion radius.",
		ru = "Показывать оповещения для этой огненной угрозы (взрывы ранца). Используется её радиус взрыва.",
		de = "Warnungen für diese Feuergefahr anzeigen (Rucksack-/Fackel-Explosionen). Verwendet ihren Explosionsradius.",
		["zh-cn"] = "显示该火焰威胁的警报（背包/喷射器爆炸），使用其爆炸半径。",
	},
	danger_zone_show_scab_flamer = {
		en = "Scab flamer",
		ru = "Скаб-огнемётчик",
		de = "Scab-Flamer",
		["zh-cn"] = "血痂喷火兵",
	},
	danger_zone_show_scab_flamer_description = {
		en = "Show alerts for this fire threat (backpack explosions). Uses its explosion radius.",
		ru = "Показывать оповещения для этой огненной угрозы (взрывы ранца). Используется её радиус взрыва.",
		de = "Warnungen für diese Feuergefahr anzeigen (Rucksackexplosionen). Verwendet ihren Explosionsradius.",
		["zh-cn"] = "显示该火焰威胁的警报（背包爆炸），使用其爆炸半径。",
	},
	danger_zone_show_bomber_grenade = {
		en = "Bomber grenade",
		ru = "Граната бомбардира",
		de = "Bombergranate",
		["zh-cn"] = "投弹兵手雷",
	},
	danger_zone_show_bomber_grenade_description = {
		en = "Show alerts for Bomber grenade explosions — uses the grenade explosion radius.",
		ru = "Показывать оповещения о гранатах бомбардира — используется радиус взрыва гранаты.",
		de = "Warnungen für Bombergranaten-Explosionen anzeigen — verwendet den Explosionsradius der Granate.",
		["zh-cn"] = "显示投弹兵手雷爆炸警报（使用手雷爆炸半径）。",
	},
	danger_zone_show_explosive_barrel = {
		en = "Explosive barrel",
		ru = "Взрывная бочка",
		de = "Explosives Fass",
		["zh-cn"] = "爆炸桶",
	},
	danger_zone_show_explosive_barrel_description = {
		en = "Show alerts for explosive barrels — uses the barrel explosion radius.",
		ru = "Показывать оповещения о взрывных бочках — используется радиус взрыва бочки.",
		de = "Warnungen für explosive Fässer anzeigen — verwendet den Explosionsradius des Fasses.",
		["zh-cn"] = "显示爆炸桶的警报（使用其爆炸半径）。",
	},
	danger_zone_show_fire_barrel = {
		en = "Fire barrel",
		ru = "Огненная бочка",
		de = "Feuerfass",
		["zh-cn"] = "火焰桶",
	},
	danger_zone_show_fire_barrel_description = {
		en = "Show alerts for fire barrels — uses the fire barrel radius.",
		ru = "Показывать оповещения о огненных бочках — используется радиус их воздействия.",
		de = "Warnungen für Feuerfässer anzeigen — verwendet den Radius des Feuerfasses.",
		["zh-cn"] = "显示火焰桶的警报（使用其影响半径）。",
	},
	divisionhud_super_dynamic = {
		en = "\238\129\135 DYNAMIC HUD",
		ru = "\238\129\135 ДИНАМИЧЕСКИЙ HUD",
		de = "\238\129\135 DYNAMISCHES HUD",
		["zh-cn"] = "\238\129\135 动态界面",
	},
	dynamic_hud = {
		en = "Dynamic HUD",
		ru = "Динамический HUD",
		de = "Dynamisches HUD",
		["zh-cn"] = "动态界面",
	},
	dynamic_hud_strength = {
		en = "Shift strength",
		ru = "Сила сдвига",
		de = "Verschiebungsstärke",
		["zh-cn"] = "偏移强度",
	},
	dynamic_hud_pitch_ratio = {
		en = "Vertical ratio",
		ru = "Вертикаль относительно горизонтали",
		de = "Vertikales Verhältnis",
		["zh-cn"] = "垂直偏移比例",
	},
	dynamic_hud_decay = {
		en = "Return speed",
		ru = "Скорость возврата",
		de = "Rückkehrgeschwindigkeit",
		["zh-cn"] = "界面回弹速度",
	},
	dynamic_hud_max_offset = {
		en = "Max offset",
		ru = "Макс. смещение",
		de = "Max. Versatz",
		["zh-cn"] = "界面最大偏移量",
	},
	dynamic_hud_freeze_on_ads = {
		en = "Freeze when aiming",
		ru = "Стабилизировать при прицеливании",
		de = "Beim Zielen einfrieren",
		["zh-cn"] = "瞄准时锁定界面",
	},
	dynamic_hud_freeze_on_ads_description = {
		en = "Freezes HUD movement while aiming down sights (works with mouse and controllers).",
		ru = "Фиксирует динамику HUD при прицеливании. Работает с мышью и геймпадом.",
		de = "Friert die HUD-Bewegung beim Zielen über Kimme und Korn ein (funktioniert mit Maus und Controllern).",
		["zh-cn"] = "瞄准时锁定界面偏移（支持鼠标和手柄）。",
	},
	divisionhud_super_vanilla_hide = {
		en = "\238\128\161 VANILLA HUD",
		ru = "\238\128\161 ВАНИЛЬНЫЙ HUD",
		de = "\238\128\161 VANILLA-HUD",
		["zh-cn"] = "\238\128\161 原版界面",
	},
	hide_vanilla_team_panel_local = {
		en = "Hide local player panel",
		ru = "Скрыть панель локального игрока",
		de = "Lokales Spielerfenster ausblenden",
		["zh-cn"] = "隐藏本地玩家面板",
	},
	hide_vanilla_stamina_area = {
		en = "Hide stamina",
		ru = "Скрыть стамину",
		de = "Ausdauer ausblenden",
		["zh-cn"] = "隐藏体力条",
	},
	hide_vanilla_dodge_area = {
		en = "Hide dodges",
		ru = "Скрыть увороты",
		de = "Ausweichmanöver ausblenden",
		["zh-cn"] = "隐藏闪避计数",
	},
	hide_vanilla_weapon_pivot = {
		en = "Hide weapons",
		ru = "Скрыть оружие",
		de = "Waffen ausblenden",
		["zh-cn"] = "隐藏武器显示",
	},
	hide_vanilla_combat_ability_slot = {
		en = "Hide combat ability",
		ru = "Скрыть боевую способность",
		de = "Kampffähigkeit ausblenden",
		["zh-cn"] = "隐藏战斗技能",
	},
	hide_vanilla_player_buffs_background = {
		en = "Hide buffs",
		ru = "Скрыть баффы",
		de = "Buffs ausblenden",
		["zh-cn"] = "隐藏增益效果",
	},
	hide_vanilla_mission_objectives = {
		en = "Hide mission objectives",
		ru = "Скрыть цели миссии",
		de = "Missionsziele ausblenden",
		["zh-cn"] = "隐藏任务目标",
	},
	hide_vanilla_mission_objectives_description = {
		en = "When enabled, only the center mission objective popups are hidden; the objective feed (including the area strip) keeps drawing. Use the Mission objectives section to mirror selected popup events into the Division HUD notification strip.",
		ru = "Если включено, скрываются только центральные всплывающие окна целей; лента целей (включая область area) продолжает отображаться. В блоке «Цели миссии» можно дублировать выбранные события попапов в полоску оповещений Division HUD.",
		de = "Wenn aktiviert, werden nur die zentralen Missionsziel-Popups ausgeblendet; der Zielfeed (einschließlich Bereichsleiste) wird weiter gezeichnet. Im Abschnitt Missionsziele kannst du ausgewählte Popup-Ereignisse in die Benachrichtigungsleiste des Division HUD spiegeln.",
		["zh-cn"] = "启用后仅隐藏中央任务弹窗，目标条带仍保留。可在任务目标设置中，将弹窗事件同步显示到 Division HUD 提示栏。",
	},
	alerts_super = {
		en = "\238\128\161 ALERTS",
		ru = "\238\128\161 ОПОВЕЩЕНИЯ",
		de = "\238\128\161 WARNUNGEN",
		["zh-cn"] = "\238\128\161 警报",
	},
	alerts_enabled = {
		en = "Enable approach alerts",
		ru = "Включить оповещения о приближении",
		de = "Annäherungswarnungen aktivieren",
		["zh-cn"] = "启用敌人接近警报",
	},
	alerts_max_visible = {
		en = "Maximum simultaneous alerts",
		ru = "Максимум одновременных оповещений",
		de = "Maximale gleichzeitige Warnungen",
		["zh-cn"] = "同时显示警报上限",
	},
	alerts_duration_sec = {
		en = "Alert duration (seconds)",
		ru = "Время показа оповещения (сек.)",
		de = "Warnungsdauer (Sekunden)",
		["zh-cn"] = "警报显示时长（秒）",
	},
	alerts_show_duration_bar = {
		en = "Alert display time bar",
		ru = "Полоса времени показа оповещения",
		de = "Leiste für Warnungsanzeigezeit",
		["zh-cn"] = "显示警报持续时间条",
	},
	alerts_group_bosses = {
		en = string.rep("\194\160", 8) .. "Bosses",
		ru = string.rep("\194\160", 8) .. "Боссы",
		de = string.rep("\194\160", 8) .. "Bosse",
		["zh-cn"] = string.rep("\194\160", 8) .. "首领",
	},
	alerts_group_specialists = {
		en = string.rep("\194\160", 8) .. "Specialists",
		ru = string.rep("\194\160", 8) .. "Специалисты",
		de = string.rep("\194\160", 8) .. "Spezialisten",
		["zh-cn"] = string.rep("\194\160", 8) .. "专家",
	},
	mission_objectives_super = {
		en = string.rep("\194\160", 8) .. "Mission objectives",
		ru = string.rep("\194\160", 8) .. "Цели миссии",
		de = string.rep("\194\160", 8) .. "Missionsziele",
		["zh-cn"] = string.rep("\194\160", 8) .. "任务目标",
	},
	mission_objectives_super_description = {
		en = "When «Hide mission objectives» is on (VANILLA HUD section), these toggles choose which objective events appear in the Division HUD strip (title row + body; same look as enemy approach notifications).",
		ru = "Когда включено «Скрыть цели миссии» (супергруппа «Ванильный HUD»), эти переключатели задают, какие события целей показывать в полоске оповещений Division HUD (заголовок в полоске + текст цели, оформление как при оповещении о приближении).",
		de = "Wenn «Missionsziele ausblenden» aktiviert ist (Abschnitt VANILLA-HUD), legen diese Schalter fest, welche Zielereignisse in der Division-HUD-Leiste erscheinen (Titelzeile + Text; gleiches Aussehen wie Warnungen vor nahenden Gegnern).",
		["zh-cn"] = "在原版界面设置中启用“隐藏任务目标”后，可通过这些开关选择哪些事件显示在 Division HUD 提示栏。",
	},
	alert_mission_objective_start = {
		en = "New objective",
		ru = "Новая цель",
		de = "Neues Ziel",
		["zh-cn"] = "新目标",
	},
	alert_mission_objective_start_description = {
		en = "When enabled, show in the Division HUD strip when a mission objective starts (same title and description as the standard center popup).",
		ru = "Показывать в полоске Division HUD при старте цели миссии (тот же заголовок и текст, что у стандартного попапа по центру).",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn ein Missionsziel startet (gleicher Titel und gleiche Beschreibung wie im standardmäßigen zentralen Popup).",
		["zh-cn"] = "任务目标开始时，在 Division HUD 栏显示与中央弹窗相同的标题与描述。",
	},
	alert_mission_objective_progress = {
		en = "Objective progress",
		ru = "Прогресс цели",
		de = "Zielfortschritt",
		["zh-cn"] = "目标进度",
	},
	alert_mission_objective_progress_description = {
		en = "When enabled, show in the Division HUD strip when the game would show a progression popup for an objective (with counter text when applicable).",
		ru = "Показывать в полоске Division HUD, когда игра показала бы попап прогресса цели (со счётчиком, если он есть).",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn das Spiel ein Fortschritts-Popup für ein Ziel anzeigen würde (mit Zählertext, falls vorhanden).",
		["zh-cn"] = "游戏显示目标进度弹窗时，在 Division HUD 栏同步显示（含计数）。",
	},
	alert_mission_objective_complete = {
		en = "Objective complete",
		ru = "Цель выполнена",
		de = "Ziel abgeschlossen",
		["zh-cn"] = "目标完成",
	},
	alert_mission_objective_complete_description = {
		en = "When enabled, show in the Division HUD strip when a mission objective completes.",
		ru = "Показывать в полоске Division HUD при завершении цели миссии.",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn ein Missionsziel abgeschlossen wird.",
		["zh-cn"] = "任务目标完成时在 Division HUD 栏显示提示。",
	},
	alert_mission_objective_custom_popup = {
		en = "Scripted objective popups",
		ru = "Сюжетные всплывашки целей",
		de = "Geskriptete Ziel-Popups",
		["zh-cn"] = "剧情脚本目标弹窗",
	},
	alert_mission_objective_custom_popup_description = {
		en = "When enabled, show in the Division HUD strip for generic mission popup events (event_show_objective_popup), e.g. some narrative beats.",
		ru = "Показывать в полоске Division HUD для общих всплывашек целей (event_show_objective_popup), например сюжетных сообщений.",
		de = "Wenn aktiviert, in der Division-HUD-Leiste für allgemeine Missions-Popup-Ereignisse anzeigen (event_show_objective_popup), z. B. manche erzählerische Momente.",
		["zh-cn"] = "对通用任务弹窗事件（如剧情提示）在 Division HUD 栏显示。",
	},
	mission_objective_custom_popup_strip_fallback = {
		en = "OBJECTIVE",
		ru = "ЦЕЛЬ",
		de = "ZIEL",
		["zh-cn"] = "目标",
	},
	alerts_group_team = {
		en = string.rep("\194\160", 8) .. "Strike team",
		ru = string.rep("\194\160", 8) .. "Ударная группа",
		de = string.rep("\194\160", 8) .. "Einsatzteam",
		["zh-cn"] = string.rep("\194\160", 8) .. "小队",
	},
	alerts_group_team_description = {
		en = "Show teammate knockdowns, trapper net, Pox Hound pin, ledge hang, Beast of Nurgle consume, and deaths in the Division HUD alert strip. The player name uses the squad slot color.",
		ru = "Показывать нокдауны, сеть ловушечника, схват чумной гончей, висение на уступе, поглощение зверем Нургла и смерти в полоске оповещений Division HUD. Ник окрашивается цветом слота отряда.",
		de = "Zeigt Niederschläge von Teammitgliedern, Fallensteller-Netz, Pox-Hound-Fixierung, Hängen an Kanten, Verschlingen durch die Bestie des Nurgle und Tode in der Warnleiste des Division HUD. Der Spielername nutzt die Farbe des Truppplatzes.",
		["zh-cn"] = "在警报栏显示队友倒地、被网、被狗咬、悬挂悬崖、被吞、阵亡等状态。玩家名称使用队伍颜色。",
	},
	alerts_team_knock = {
		en = "Teammate knocked down",
		ru = "Союзник упал",
		de = "Teammitglied niedergeschlagen",
		["zh-cn"] = "队友倒地",
	},
	alerts_team_knock_description = {
		en = "When a teammate enters the knocked down state, enqueue an alert line (wording includes that help is needed).",
		ru = "Когда союзник падает в нокдаун, добавлять строку в оповещения (в тексте указано, что нужна помощь).",
		de = "Wenn ein Teammitglied niedergeschlagen wird, eine Warnzeile einreihen (der Text enthält, dass Hilfe benötigt wird).",
		["zh-cn"] = "队友倒地时显示警报，并提示需要帮助。",
	},
	alerts_team_net = {
		en = "Caught in net",
		ru = "Пойман в сеть",
		de = "Im Netz gefangen",
		["zh-cn"] = "被网困住",
	},
	alerts_team_net_description = {
		en = "When a teammate is netted (Scab Trapper), enqueue an alert. Uses character_state / disabled checks like the player panel, and also when the state machine applies a server correction to netted so other players on your client are covered.",
		ru = "Когда союзник в сети ловушечника — строка в оповещениях. Те же проверки character_state / disabled, что у панели игрока; дополнительно при server_correction_occurred в netted, чтобы срабатывало и для союзников с репликацией состояния.",
		de = "Wenn ein Teammitglied im Netz ist (Scab Trapper), eine Warnung einreihen. Nutzt character_state-/disabled-Prüfungen wie das Spielerfenster und zusätzlich, wenn die Zustandsmaschine eine Serverkorrektur auf netted anwendet, damit andere Spieler auf deinem Client abgedeckt sind.",
		["zh-cn"] = "队友被陷阱兵网住时显示警报，判定逻辑与原版玩家面板一致，并兼容服务器状态同步。",
	},
	alerts_team_hound = {
		en = "Pox Hound on teammate",
		ru = "Чумная Гончая на союзнике",
		de = "Pox Hound auf Teammitglied",
		["zh-cn"] = "瘟疫猎犬扑中队友",
	},
	alerts_team_hound_description = {
		en = "When a teammate enters the pounced disabled state (Pox Hound pin), enqueue an alert line. Uses the same disabled_character_state check as the vanilla player panel.",
		ru = "Когда союзник в состоянии «схвачен» с типом pounced (чумная гончая), добавлять строку. Проверка disabled_character_state + PlayerUnitStatus.is_pounced, как у ванильной панели игрока.",
		de = "Wenn ein Teammitglied in den deaktivierten Zustand pounced gerät (Pox-Hound-Fixierung), eine Warnzeile einreihen. Nutzt dieselbe disabled_character_state-Prüfung wie das Vanilla-Spielerfenster.",
		["zh-cn"] = "队友被瘟疫猎犬扑倒压制时显示警报，使用与原版一致的状态判定。",
	},
	alerts_team_ledge = {
		en = "Hanging on ledge",
		ru = "Висит на уступе",
		de = "Hängt an einer Kante",
		["zh-cn"] = "悬挂悬崖",
	},
	alerts_team_ledge_description = {
		en = "When a teammate enters ledge_hanging (needs pull-up help), enqueue an alert line. Uses PlayerUnitStatus.is_ledge_hanging on character_state.",
		ru = "Когда союзник в состоянии ledge_hanging (висит на уступе, нужен подтяг), добавлять строку. Проверка PlayerUnitStatus.is_ledge_hanging по character_state.",
		de = "Wenn ein Teammitglied in ledge_hanging gerät (hängt an einer Kante und braucht Hilfe beim Hochziehen), eine Warnzeile einreihen. Nutzt PlayerUnitStatus.is_ledge_hanging auf character_state.",
		["zh-cn"] = "队友悬挂在悬崖需要救援时显示警报。",
	},
	alerts_team_consumed = {
		en = "Swallowed by Beast of Nurgle",
		ru = "Поглощён Зверем Нургла",
		de = "Von der Bestie des Nurgle verschlungen",
		["zh-cn"] = "被纳垢巨兽吞噬",
	},
	alerts_team_consumed_description = {
		en = "When a teammate enters the consumed disabled state (Beast of Nurgle), enqueue an alert line. Uses PlayerUnitStatus.is_consumed on disabled_character_state.",
		ru = "Когда союзник в состоянии consumed (поглощён зверем Нургла), добавлять строку. Проверка PlayerUnitStatus.is_consumed по disabled_character_state.",
		de = "Wenn ein Teammitglied in den deaktivierten Zustand consumed gerät (Bestie des Nurgle), eine Warnzeile einreihen. Nutzt PlayerUnitStatus.is_consumed auf disabled_character_state.",
		["zh-cn"] = "队友被纳垢巨兽吞入体内时显示警报。",
	},
	alerts_team_death = {
		en = "Teammate death",
		ru = "Смерть союзника",
		de = "Tod eines Teammitglieds",
		["zh-cn"] = "队友阵亡",
	},
	alerts_team_death_description = {
		en = "When a teammate dies, enqueue an alert line.",
		ru = "Когда союзник умирает, добавлять строку в оповещения.",
		de = "Wenn ein Teammitglied stirbt, eine Warnzeile einreihen.",
		["zh-cn"] = "队友死亡时显示警报。",
	},
	alerts_team_strip = {
		en = "Strike team",
		ru = "Ударная группа",
		de = "Einsatzteam",
		["zh-cn"] = "小队",
	},
	alerts_team_suffix_knock = {
		en = "knocked down, needs help",
		ru = "упал, нужна помощь",
		de = "niedergeschlagen, braucht Hilfe",
		["zh-cn"] = "倒地，需要帮助",
	},
	alerts_team_suffix_death = {
		en = "died",
		ru = "погиб",
		de = "ist gestorben",
		["zh-cn"] = "阵亡",
	},
	alerts_team_suffix_trapper_net = {
		en = "was ensnared by a Scab Trapper",
		ru = "пойман в сеть Скаб Ловушечника",
		de = "wurde von einem Scab Trapper gefangen",
		["zh-cn"] = "被血痂陷阱手的网困住",
	},
	alerts_team_suffix_hound_pounce = {
		en = "was pinned by a Pox Hound",
		ru = "схватила Чумная гончая",
		de = "wurde von einem Pox Hound festgenagelt",
		["zh-cn"] = "被瘟疫猎犬扑倒",
	},
	alerts_team_suffix_ledge_hanging = {
		en = "is hanging on a ledge, needs help",
		ru = "висит на уступе, нужна помощь",
		de = "hängt an einer Kante, braucht Hilfe",
		["zh-cn"] = "悬挂在悬崖，需要救援",
	},
	alerts_team_suffix_consumed = {
		en = "consumed by a Beast of Nurgle",
		ru = "поглощён зверем Нургла",
		de = "von einer Bestie des Nurgle verschlungen",
		["zh-cn"] = "被纳垢兽吞噬",
	},
	alerts_ui_banner_alert = {
		en = "ALERT",
		ru = "ВНИМАНИЕ",
		de = "WARNUNG",
		["zh-cn"] = "警报",
	},
	alerts_message_specialist_approach = {
		en = "Detected %s",
		ru = "Обнаружен %s",
		de = "%s erkannt",
		["zh-cn"] = "侦测到：%s",
	},
	alerts_message_boss_approach = {
		en = "Detected %s",
		ru = "Обнаружен %s",
		de = "%s erkannt",
		["zh-cn"] = "侦测到：%s",
	},
	alerts_message_spawn_grouped = {
		en = "Detected %s x%d",
		ru = "Обнаружен %s x%d",
		de = "%s x%d erkannt",
		["zh-cn"] = "侦测到：%s x%d",
	},
	alerts_message_mission_objective_grouped = {
		en = "%s x%d",
		ru = "%s x%d",
		de = "%s x%d",
		["zh-cn"] = "%s x%d",
	},
	alerts_breed_title_override_chaos_mutator_daemonhost = {
		en = "Daemonhost (mutator)",
		ru = "Демонхост (мутатор)",
		de = "Dämonenhost (Mutator)",
		["zh-cn"] = "恶魔宿主（突变）",
	},
	alerts_breed_title_override_chaos_hound_mutator = {
		en = "Pox Hound (mutator)",
		ru = "Чумная гончая (мутатор)",
		de = "Pox Hound (Mutator)",
		["zh-cn"] = "瘟疫猎犬（突变）",
	},
	alerts_breed_title_override_renegade_grenadier = {
		en = "Renegade Grenadier",
		ru = "Скаб-Бомбардир",
		de = "Renegaten-Grenadier",
		["zh-cn"] = "血痂火雷兵",
	},
	divisionhud_super_proximity = {
		en = "\238\128\161 PROXIMITY DETECTOR",
		ru = "\238\128\161 ДЕТЕКТОР ПРЕДМЕТОВ",
		de = "\238\128\161 NÄHE-DETEKTOR",
		["zh-cn"] = "\238\128\161 近距感应",
	},
	proximity_enabled = {
		en = "Enable proximity detector",
		ru = "Включить детектор предметов",
		de = "Nähe-Detektor aktivieren",
		["zh-cn"] = "启用近距感应",
	},
	proximity_enabled_description = {
		en = "Shows nearby pickups (medkits, ammo, stimms) to the right of the HUD slots.",
		ru = "Показывает ближайшие предметы (аптечки, патроны, стимы) справа от слотов HUD.",
		de = "Zeigt nahe Pickups (Medkits, Munition, Stimms) rechts von den HUD-Plätzen an.",
		["zh-cn"] = "在HUD槽右侧显示附近的拾取物（急救箱、弹药、注射器）。",
	},
	proximity_radius = {
		en = "Detection radius (m)",
		ru = "Радиус обнаружения (м)",
		de = "Erkennungsradius (m)",
		["zh-cn"] = "检测半径（米）",
	},
	proximity_radius_description = {
		en = "Maximum distance in meters to detect nearby items.",
		ru = "Максимальное расстояние в метрах для обнаружения предметов.",
		de = "Maximale Entfernung in Metern, um nahe Gegenstände zu erkennen.",
		["zh-cn"] = "检测附近物品的最大距离（米）。",
	},
	proximity_show_medical_station = {
		en = "Show health stations",
		ru = "Показывать мед станции",
		de = "Medicae-Stationen anzeigen",
		["zh-cn"] = "显示医疗站",
	},
	proximity_show_medical_station_description = {
		en = "Detect health stations (only those with remaining charges).",
		ru = "Обнаруживать мед станции (только с оставшимися зарядами).",
		de = "Medicae-Stationen erkennen (nur solche mit verbleibenden Ladungen).",
		["zh-cn"] = "检测医疗站（仅剩余充能时显示）。",
	},
	proximity_show_medical = {
		en = "Show medkits",
		ru = "Показывать аптечки",
		de = "Medkits anzeigen",
		["zh-cn"] = "显示急救箱",
	},
	proximity_show_medical_description = {
		en = "Detect pocketable medical crates.",
		ru = "Обнаруживать карманные мед ящики.",
		de = "Tragbare medizinische Kisten erkennen.",
		["zh-cn"] = "检测可携带医疗箱。",
	},
	proximity_show_medical_deployed = {
		en = "Show deployed medical crates",
		ru = "Показывать развёрнутые мед ящики",
		de = "Aufgestellte medizinische Kisten anzeigen",
		["zh-cn"] = "显示已部署医疗箱",
	},
	proximity_show_medical_deployed_description = {
		en = "Detect deployed medical crates placed by players.",
		ru = "Обнаруживать развёрнутые мед ящики, выставленные игроками.",
		de = "Von Spielern platzierte aufgestellte medizinische Kisten erkennen.",
		["zh-cn"] = "检测玩家放置的已部署医疗箱。",
	},
	proximity_show_stimm = {
		en = "Show stimulants",
		ru = "Показывать стимуляторы",
		de = "Stimms anzeigen",
		["zh-cn"] = "显示注射器",
	},
	proximity_show_stimm_description = {
		en = "Detect stimulant syringes.",
		ru = "Обнаруживать стимулирующие шприцы.",
		de = "Stimm-Spritzen erkennen.",
		["zh-cn"] = "检测刺激注射器。",
	},
	proximity_show_ammo_small = {
		en = "Show small ammo clips",
		ru = "Показывать малые патроны",
		de = "Kleine Munitionsclips anzeigen",
		["zh-cn"] = "显示小弹夹",
	},
	proximity_show_ammo_small_description = {
		en = "Detect small ammo clips.",
		ru = "Обнаруживать малые обоймы с патронами.",
		de = "Kleine Munitionsclips erkennen.",
		["zh-cn"] = "检测小弹夹。",
	},
	proximity_show_ammo_large = {
		en = "Show large ammo clips",
		ru = "Показывать крупные патроны",
		de = "Große Munitionsclips anzeigen",
		["zh-cn"] = "显示大弹夹",
	},
	proximity_show_ammo_large_description = {
		en = "Detect large ammo clips.",
		ru = "Обнаруживать крупные обоймы с патронами.",
		de = "Große Munitionsclips erkennen.",
		["zh-cn"] = "检测大弹夹。",
	},
	proximity_show_ammo_crate = {
		en = "Show ammo crates",
		ru = "Показывать ящики патронов",
		de = "Munitionskisten anzeigen",
		["zh-cn"] = "显示弹药箱",
	},
	proximity_show_ammo_crate_description = {
		en = "Detect pocketable ammo crates and ammo crates placed on the level.",
		ru = "Обнаруживать карманные ящики патронов и ящики с патронами, размещённые на уровне.",
		de = "Tragbare Munitionskisten und im Level platzierte Munitionskisten erkennen.",
		["zh-cn"] = "检测可携带弹药箱和关卡内放置的弹药箱。",
	},
	proximity_show_ammo_crate_deployed = {
		en = "Show deployed ammo crates",
		ru = "Показывать развёрнутые ящики патронов",
		de = "Aufgestellte Munitionskisten anzeigen",
		["zh-cn"] = "显示已部署弹药箱",
	},
	proximity_show_ammo_crate_deployed_description = {
		en = "Detect deployed ammo crates placed by players.",
		ru = "Обнаруживать развёрнутые ящики патронов, выставленные игроками.",
		de = "Von Spielern platzierte aufgestellte Munitionskisten erkennen.",
		["zh-cn"] = "检测玩家放置的已部署弹药箱。",
	},
	proximity_show_grenade = {
		en = "Show grenades",
		ru = "Показывать гранаты",
		de = "Granaten anzeigen",
		["zh-cn"] = "显示手榴弹",
	},
	proximity_show_grenade_description = {
		en = "Detect grenades (standard and expedition).",
		ru = "Обнаруживать гранаты (обычные и экспедиционные).",
		de = "Granaten erkennen (Standard und Expedition).",
		["zh-cn"] = "检测手榴弹（普通和远征）。",
	},
	proximity_show_grimoire = {
		en = "Show grimoires",
		ru = "Показывать гримуары",
		de = "Grimoires anzeigen",
		["zh-cn"] = "显示秘典",
	},
	proximity_show_grimoire_description = {
		en = "Detect grimoires on the map.",
		ru = "Обнаруживать гримуары на карте.",
		de = "Grimoires auf der Karte erkennen.",
		["zh-cn"] = "检测地图上的秘典。",
	},
	proximity_show_tome = {
		en = "Show scriptures",
		ru = "Показывать писания",
		de = "Schriften anzeigen",
		["zh-cn"] = "显示圣书",
	},
	proximity_show_tome_description = {
		en = "Detect scriptures (tomes) on the map.",
		ru = "Обнаруживать писания на карте.",
		de = "Schriften (Tomes) auf der Karte erkennen.",
		["zh-cn"] = "检测地图上的圣书。",
	},
	divisionhud_integrations = {
		en = "\238\128\172 INTEGRATIONS",
		ru = "\238\128\172 ИНТЕГРАЦИИ",
		de = "\238\128\172 INTEGRATIONEN",
		["zh-cn"] = "\238\128\172 模组兼容",
	},
	integration_custom_hud = {
		en = "Custom HUD",
		ru = "Custom HUD",
		de = "Custom HUD",
		["zh-cn"] = "Custom HUD 兼容",
	},
	integration_custom_hud_description = {
		en = "When enabled and Custom HUD has saved layout for this HUD (including root), Division HUD applies that position every frame and adds Dynamic HUD motion on top. Offset X/Y sliders are ignored for root. If only inner nodes are saved, root is left unchanged. Until anything is saved in Custom HUD, the X/Y sliders still move the block.",
		ru = "Если включено и в Custom HUD сохранена раскладка этого HUD (в т.ч. root), Division HUD каждый кадр ставит эту позицию и при необходимости добавляет смещение Dynamic HUD. Слайдеры X/Y для root не используются. Если в Custom HUD сохранены только внутренние узлы, root не трогаем. Пока в Custom HUD нет сохранений — блок двигают слайдеры X/Y.",
		de = "Wenn aktiviert und Custom HUD ein Layout für dieses HUD gespeichert hat (einschließlich root), wendet Division HUD diese Position in jedem Frame an und fügt die Dynamic-HUD-Bewegung darüber hinzu. Die X/Y-Versatzregler werden für root ignoriert. Wenn nur innere Knoten gespeichert sind, bleibt root unverändert. Solange in Custom HUD nichts gespeichert ist, bewegen die X/Y-Regler den Block weiterhin.",
		["zh-cn"] = "启用后，若 Custom HUD 已保存布局，Division HUD 将使用其位置并叠加动态效果，忽略 X/Y 偏移。未保存布局时仍可使用滑块调整。",
	},
	integration_stimm_countdown = {
		en = "StimmCountdown",
		ru = "StimmCountdown",
		de = "StimmCountdown",
		["zh-cn"] = "StimmCountdown 兼容",
	},
	integration_stimm_countdown_description = {
		en = "When enabled and the StimmCountdown mod is loaded and enabled, the pocket stimm slot in the Division HUD strip shows its countdown (active / cooldown) using that mod’s display options. When off, the slot uses the usual 01/00 counter only.",
		ru = "Если включено и мод StimmCountdown загружен и включён, в слоте карманного шприца в полоске Division HUD показывается отсчёт (действие / перезарядка) с учётом настроек того мода. Если выключено — только обычные 01/00.",
		de = "Wenn aktiviert und der Mod StimmCountdown geladen und aktiviert ist, zeigt der Stimm-Taschenplatz in der Division-HUD-Leiste seinen Countdown (aktiv / Abklingzeit) mit den Anzeigeoptionen dieses Mods. Wenn deaktiviert, verwendet der Platz nur den üblichen 01/00-Zähler.",
		["zh-cn"] = "启用后，若已加载 StimmCountdown，注射器槽会显示持续/冷却倒计时；关闭则只显示 01/00。",
	},
	integration_recolor_stimms = {
		en = "RecolorStimms",
		ru = "RecolorStimms",
		de = "RecolorStimms",
		["zh-cn"] = "RecolorStimms 兼容",
	},
	integration_recolor_stimms_description = {
		en = "When enabled and the RecolorStimms mod is loaded and enabled, pocket stimm icon colors are taken from that mod (get_stimm_argb_255). When off or the mod is unavailable, built-in syringe colors are used.",
		ru = "Если включено и мод RecolorStimms загружен и включён, цвета иконки карманного шприца берутся из него (get_stimm_argb_255). Иначе используются встроенные цвета шприцев.",
		de = "Wenn aktiviert und der Mod RecolorStimms geladen und aktiviert ist, werden die Farben des Stimm-Symbols im Taschenplatz von diesem Mod übernommen (get_stimm_argb_255). Wenn deaktiviert oder der Mod nicht verfügbar ist, werden die integrierten Spritzenfarben verwendet.",
		["zh-cn"] = "启用后，注射器图标颜色将从 RecolorStimms 读取；未启用时使用内置颜色。",
	},
	divisionhud_super_enemy_target = {
		en = "\238\128\178 ENEMY TARGET",
		ru = "\238\128\178 ВРАЖЕСКАЯ ЦЕЛЬ",
		de = "\238\128\178 GEGNERZIEL",
		["zh-cn"] = "\238\128\178 敌方目标",
	},
	enemy_target_enabled = {
		en = "Enable enemy target",
		ru = "Включить вражескую цель",
		de = "Gegnerziel aktivieren",
		["zh-cn"] = "启用敌方目标",
	},
	enemy_target_enabled_description = {
		en = "Shows or hides the enemy target block.",
		ru = "Показывает или скрывает блок вражеской цели.",
		de = "Zeigt oder verbirgt den Gegnerziel-Block.",
		["zh-cn"] = "显示或隐藏敌方目标模块。",
	},
	enemy_target_sources = {
		en = string.rep("\194\160", 8) .. "Information sources",
		ru = string.rep("\194\160", 8) .. "Источники информации",
		de = string.rep("\194\160", 8) .. "Informationsquellen",
		["zh-cn"] = string.rep("\194\160", 8) .. "信息来源",
	},
	enemy_target_sources_description = {
		en = "Choose which events are allowed to show the enemy target block.",
		ru = "Выберите, какие события могут показывать блок цели.",
		de = "Wähle, welche Ereignisse den Gegnerziel-Block anzeigen dürfen.",
		["zh-cn"] = "选择哪些事件可以显示敌方目标模块。",
	},
	enemy_target_show_on_hover = {
		en = "Hover enemy",
		ru = "Наведение на врага",
		de = "Gegner anvisieren",
		["zh-cn"] = "瞄准敌人",
	},
	enemy_target_show_on_hover_description = {
		en = "Show the block when the current target is under the crosshair.",
		ru = "Показывать блок, когда текущая цель находится под прицелом.",
		de = "Block anzeigen, wenn sich das aktuelle Ziel unter dem Fadenkreuz befindet.",
		["zh-cn"] = "当当前目标处于准星下时显示模块。",
	},
	enemy_target_show_on_hit = {
		en = "Hit enemy",
		ru = "Попадание по врагу",
		de = "Gegner treffen",
		["zh-cn"] = "命中敌人",
	},
	enemy_target_show_on_hit_description = {
		en = "Show the block when you damage an enemy.",
		ru = "Показывать блок, когда вы наносите урон врагу.",
		de = "Block anzeigen, wenn du einem Gegner Schaden zufügst.",
		["zh-cn"] = "当你对敌人造成伤害时显示模块。",
	},
	enemy_target_hold_time = {
		en = "Display time (seconds)",
		ru = "Время показа (сек.)",
		de = "Anzeigedauer (Sekunden)",
		["zh-cn"] = "显示时间（秒）",
	},
	enemy_target_hold_time_description = {
		en = "How many seconds the block remains visible after a hit trigger (does not affect hover).",
		ru = "Сколько секунд блок остается видимым после триггера попадания (не влияет на наведение).",
		de = "Wie viele Sekunden der Block nach einem Treffer-Auslöser sichtbar bleibt (wirkt sich nicht auf Anvisieren aus).",
		["zh-cn"] = "命中触发后模块保持显示的秒数（不影响瞄准触发）。",
	},
	enemy_target_show_debuffs = {
		en = "Show debuffs",
		ru = "Показывать дебафы",
		de = "Debuffs anzeigen",
		["zh-cn"] = "显示减益",
	},
	enemy_target_show_debuffs_description = {
		en = "Show the list of active debuffs on the enemy target inside the block.",
		ru = "Показывать список активных дебафов на вражеской цели внутри блока.",
		de = "Liste aktiver Debuffs auf dem Gegnerziel im Block anzeigen.",
		["zh-cn"] = "在模块中显示敌方目标身上的有效减益列表。",
	},
	enemy_target_groups = {
		en = string.rep("\194\160", 8) .. "Enemy groups",
		ru = string.rep("\194\160", 8) .. "Группы врагов",
		de = string.rep("\194\160", 8) .. "Gegnergruppen",
		["zh-cn"] = string.rep("\194\160", 8) .. "敌人分组",
	},
	enemy_target_groups_description = {
		en = "Choose which enemy groups are allowed to appear in the block.",
		ru = "Выберите, какие группы врагов можно показывать в блоке.",
		de = "Wähle, welche Gegnergruppen im Block erscheinen dürfen.",
		["zh-cn"] = "选择允许在模块中显示的敌人分组。",
	},
	enemy_target_show_boss = {
		en = "Boss",
		ru = "Боссы",
		de = "Boss",
		["zh-cn"] = "Boss",
	},
	enemy_target_show_boss_description = {
		en = "Allow bosses in the enemy target block.",
		ru = "Разрешить показ боссов в блоке цели.",
		de = "Bosse im Gegnerziel-Block erlauben.",
		["zh-cn"] = "允许在敌方目标模块中显示 Boss。",
	},
	enemy_target_show_elite = {
		en = "Elite",
		ru = "Элита",
		de = "Elite",
		["zh-cn"] = "精英",
	},
	enemy_target_show_elite_description = {
		en = "Allow elites in the enemy target block.",
		ru = "Разрешить показ элиты в блоке цели.",
		de = "Eliten im Gegnerziel-Block erlauben.",
		["zh-cn"] = "允许在敌方目标模块中显示精英。",
	},
	enemy_target_show_special = {
		en = "Special",
		ru = "Специалисты",
		de = "Spezialist",
		["zh-cn"] = "专家",
	},
	enemy_target_show_special_description = {
		en = "Allow specials in the enemy target block.",
		ru = "Разрешить показ специалистов в блоке цели.",
		de = "Spezialisten im Gegnerziel-Block erlauben.",
		["zh-cn"] = "允许在敌方目标模块中显示专家。",
	},
	divisionhud_super_system = {
		en = "\238\128\169 SYSTEM SETTINGS",
		ru = "\238\128\169 СИСТЕМНЫЕ НАСТРОЙКИ",
		de = "\238\128\169 SYSTEMEINSTELLUNGEN",
		["zh-cn"] = "\238\128\169 系统设置",
	},
	debug = {
		en = "Debug",
		ru = "Debug",
		de = "Debug",
		["zh-cn"] = "调试",
	},
	debug_description = {
		en = "Enables the internal DivisionHUD debug hotkeys on the numpad. Numpad 1 shows the alert \"Enemies nearby\". Numpad 2 simulates the invulnerability toughness buff and the 125 + 170 toughness label.",
		ru = "Включает внутренние debug-горячие клавиши DivisionHUD на numpad. Numpad 1 показывает алерт «Враги рядом». Numpad 2 имитирует баф неуязвимости на стойкость и подпись стойкости 125 + 170.",
		de = "Aktiviert die internen Debug-Hotkeys von DivisionHUD auf dem Nummernblock. Nummernblock 1 zeigt die Warnung \"Gegner in der Nähe\". Nummernblock 2 simuliert den Unverwundbarkeits-Buff auf Widerstand und die Widerstandsbeschriftung 125 + 170.",
		["zh-cn"] = "启用 DivisionHUD 的数字小键盘调试热键。小键盘 1 显示“敌人接近”警报，小键盘 2 模拟无敌韧性增益和 125 + 170 韧性文本。",
	},
	divisionhud_reset_all_settings = {
		en = "Reset settings",
		ru = "Сбросить настройки",
		de = "Einstellungen zurücksetzen",
		["zh-cn"] = "重置设置",
	},
	divisionhud_reset_all_settings_description = {
		en = "Pick the confirm entry and apply. All Division HUD options return to defaults.",
		ru = "Выберите подтверждение и примените. Все параметры Division HUD вернутся к значениям по умолчанию.",
		de = "Bestätigungseintrag auswählen und anwenden. Alle Division-HUD-Optionen werden auf Standardwerte zurückgesetzt.",
		["zh-cn"] = "选择确认并应用，所有 Division HUD 设置恢复默认。",
	},
	divisionhud_reset_confirm = {
		en = "Yes, reset",
		ru = "Да, сбросить",
		de = "Ja, zurücksetzen",
		["zh-cn"] = "确认重置",
	},
	divisionhud_reset_done = {
		en = "Division HUD: settings restored to defaults.",
		ru = "Division HUD: настройки сброшены к значениям по умолчанию.",
		de = "Division HUD: Einstellungen auf Standardwerte zurückgesetzt.",
		["zh-cn"] = "全境封锁 HUD：已恢复默认设置。",
	},
	enemy_target_type_monster = {
		en = "Miniboss",
		ru = "Минибосс",
		de = "Miniboss",
		["zh-cn"] = "小BOSS",
	},
	enemy_target_type_captain = {
		en = "Boss",
		ru = "Босс",
		de = "Boss",
		["zh-cn"] = "BOSS",
	},
	enemy_target_type_disabler = {
		en = "Disabler",
		ru = "Контроль",
		de = "Disabler",
		["zh-cn"] = "控制专家",
	},
	enemy_target_type_witch = {
		en = "Daemonhost",
		ru = "Демонхост",
		de = "Dämonenhost",
		["zh-cn"] = "恶魔宿主",
	},
	enemy_target_type_sniper = {
		en = "Sniper",
		ru = "Снайпер",
		de = "Scharfschütze",
		["zh-cn"] = "狙击手",
	},
	enemy_target_type_far = {
		en = "Ranged elite",
		ru = "Дальний элитник",
		de = "Fernkampf-Elite",
		["zh-cn"] = "远程精英",
	},
	enemy_target_type_elite = {
		en = "Melee elite",
		ru = "Ближний элитник",
		de = "Nahkampf-Elite",
		["zh-cn"] = "近战精英",
	},
	enemy_target_type_special = {
		en = "Special",
		ru = "Специалист",
		de = "Spezialist",
		["zh-cn"] = "输出专家",
	},
	enemy_target_type_horde = {
		en = "Horde",
		ru = "Орда",
		de = "Horde",
		["zh-cn"] = "尸潮怪",
	},
	enemy_target_type_enemy = {
		en = "Enemy",
		ru = "Враг",
		de = "Gegner",
		["zh-cn"] = "敌人",
	},
	enemy_target_debuff_label_bleed = {
		en = "Bleed",
		ru = "Кровотечение",
		de = "Blutung",
		["zh-cn"] = "流血",
	},
	enemy_target_debuff_label_fire = {
		en = "Fire",
		ru = "Поджог",
		de = "Feuer",
		["zh-cn"] = "燃烧",
	},
	enemy_target_debuff_label_warp = {
		en = "Warp",
		ru = "Варп",
		de = "Warp",
		["zh-cn"] = "灵能",
	},
	enemy_target_debuff_label_shock = {
		en = "Electroshock",
		ru = "Электрошок",
		de = "Elektroschock",
		["zh-cn"] = "电击",
	},
	enemy_target_debuff_label_toxin = {
		en = "Poison",
		ru = "Отравление",
		de = "Gift",
		["zh-cn"] = "中毒",
	},
	enemy_target_debuff_label_rending = {
		en = "Armor Break",
		ru = "Пробитие брони",
		de = "Rüstungsbruch",
		["zh-cn"] = "破甲",
	},
	enemy_target_debuff_label_stagger = {
		en = "Stun",
		ru = "Оглушение",
		de = "Betäubung",
		["zh-cn"] = "击晕",
	},
	enemy_target_debuff_label_blind = {
		en = "Smoke Effect",
		ru = "Эффект дыма",
		de = "Raucheffekt",
		["zh-cn"] = "致盲",
	},
	enemy_target_debuff_label_damage_taken = {
		en = "More Damage",
		ru = "Больше урона",
		de = "Mehr Schaden",
		["zh-cn"] = "易伤",
	},
	enemy_target_debuff_label_melee_damage_taken = {
		en = "More Melee Damage",
		ru = "Больше урона вблизи",
		de = "Mehr Nahkampfschaden",
		["zh-cn"] = "近战易伤",
	},
	enemy_target_debuff_label_stagger_damage = {
		en = "More Stunned Damage",
		ru = "Больше урона оглушённому",
		de = "Mehr Schaden gegen Betäubte",
		["zh-cn"] = "击晕易伤",
	},
	enemy_target_debuff_label_impact_taken = {
		en = "Easier to Stun",
		ru = "Легче оглушить",
		de = "Leichter zu betäuben",
		["zh-cn"] = "更易硬直",
	},
	enemy_target_debuff_label_count_as_stagger = {
		en = "Stun Effect",
		ru = "Эффект ошеломления",
		de = "Betäubungseffekt",
		["zh-cn"] = "硬直目标",
	},
	enemy_target_debuff_label_damage_dealt_down = {
		en = "Weakening Effect",
		ru = "Эффект ослабления",
		de = "Schwächungseffekt",
		["zh-cn"] = "攻击削弱",
	},
}
