return {
	mod_name = {
		en = "Division HUD",
		ru = "Division HUD",
		de = "Division HUD",
		fr = "Division HUD",
		["zh-cn"] = "全境封锁风格 HUD",
	},
	mod_description = {
		en = "Adds extra combat HUD styled like The Division.",
		ru = "Добавляет дополнительный боевой HUD в стиле The Division.",
		de = "Fügt ein zusätzliches Kampf-HUD im Stil von The Division hinzu.",
		fr = "Ajoute un HUD de combat supplémentaire dans le style de The Division.",
		["zh-cn"] = "添加《全境封锁》风格的额外战斗界面。",
	},
	divisionhud_super_layout = {
		en = "\238\128\140 DISPLAY",
		ru = "\238\128\140 ОТОБРАЖЕНИЕ",
		de = "\238\128\140 ANZEIGE",
		fr = "\238\128\140 AFFICHAGE",
		["zh-cn"] = "\238\128\140 显示设置",
	},
	divisionhud_visible = {
		en = "Show Division HUD",
		ru = "Показывать Division HUD",
		de = "Division HUD anzeigen",
		fr = "Afficher Division HUD",
		["zh-cn"] = "显示 Division HUD",
	},
	divisionhud_visible_description = {
		en = "When off, the entire Division HUD overlay is hidden.",
		ru = "Если выключено, скрыт весь оверлей Division HUD.",
		de = "Wenn deaktiviert, wird das gesamte Division-HUD-Overlay ausgeblendet.",
		fr = "Lorsque cette option est désactivée, toute la surcouche Division HUD est masquée.",
		["zh-cn"] = "关闭时隐藏整个 Division HUD。",
	},
	divisionhud_toggle_visible_keybind = {
		en = "Toggle HUD visibility",
		ru = "Переключить видимость HUD",
		de = "HUD-Sichtbarkeit umschalten",
		fr = "Basculer la visibilité du HUD",
		["zh-cn"] = "切换 HUD 显示",
	},
	divisionhud_toggle_visible_keybind_description = {
		en = "Same as «Show Division HUD» above.",
		ru = "То же, что чекбокс «Показывать Division HUD» выше.",
		de = "Entspricht oben «Division HUD anzeigen».",
		fr = "Identique à « Afficher Division HUD » ci-dessus.",
		["zh-cn"] = "与上方「显示 Division HUD」相同。",
	},
	divisionhud_auto_switch = {
		en = string.rep("\194\160", 8) .. "Auto visibility switch",
		ru = string.rep("\194\160", 8) .. "Авто переключение видимости",
		de = string.rep("\194\160", 8) .. "Automatische Sichtbarkeit",
		fr = string.rep("\194\160", 8) .. "Visibilité automatique",
		["zh-cn"] = string.rep("\194\160", 8) .. "自动切换可见性",
	},
	divisionhud_auto_first_person = {
		en = "First person",
		ru = "От первого лица",
		de = "Ego-Perspektive",
		fr = "Première personne",
		["zh-cn"] = "第一人称",
	},
	divisionhud_auto_first_person_description = {
		en = "Show HUD in first person.",
		ru = "Показывать HUD от первого лица.",
		de = "HUD in der Ego-Perspektive anzeigen.",
		fr = "Afficher le HUD à la première personne.",
		["zh-cn"] = "第一人称时显示。",
	},
	divisionhud_auto_third_person = {
		en = "Third person",
		ru = "От третьего лица",
		de = "Dritte Person",
		fr = "Troisième personne",
		["zh-cn"] = "第三人称",
	},
	divisionhud_auto_third_person_description = {
		en = "Show HUD in third person.",
		ru = "Показывать HUD от третьего лица.",
		de = "HUD in der Third-Person-Ansicht anzeigen.",
		fr = "Afficher le HUD à la troisième personne.",
		["zh-cn"] = "第三人称时显示。",
	},
	divisionhud_auto_slot_device = {
		en = "Device in hand",
		ru = "Устройство в руках",
		de = "Gerät in der Hand",
		fr = "Appareil en main",
		["zh-cn"] = "手持设备",
	},
	divisionhud_auto_slot_device_description = {
		en = "If you hold a device: off — hide Division HUD. On — do not hide.",
		ru = "Если в руках устройство: выкл — скрыть Division HUD. Вкл — не скрывать.",
		de = "Wenn du ein Gerät hältst: Aus — Division HUD ausblenden. Ein — nicht ausblenden.",
		fr = "Si vous tenez un appareil : désactivé — masquer Division HUD. Activé — ne pas masquer.",
		["zh-cn"] = "手持设备时：关 — 隐藏 Division HUD；开 — 不隐藏。",
	},
	divisionhud_placement = {
		en = string.rep("\194\160", 8) .. "Position, opacity & scale",
		ru = string.rep("\194\160", 8) .. "Позиция, прозрачность и масштаб",
		de = string.rep("\194\160", 8) .. "Position, Deckkraft & Skalierung",
		fr = string.rep("\194\160", 8) .. "Position, opacité et échelle",
		["zh-cn"] = string.rep("\194\160", 8) .. "位置、不透明度与缩放",
	},
	position_x = {
		en = "Offset X",
		ru = "Смещение по X",
		de = "Versatz X",
		fr = "Décalage X",
		["zh-cn"] = "水平偏移 X",
	},
	position_x_description = {
		en = "Horizontal offset from the screen center in logical pixels (reference canvas 1920×1080). Range ±960. Negative moves the HUD left, positive moves it right. The root block is center-aligned.",
		ru = "Горизонтальное смещение от центра экрана в логических пикселях (эталонный холст 1920×1080). Диапазон ±960. Отрицательные значения — влево, положительные — вправо. Корневой блок привязан к центру экрана.",
		de = "Horizontaler Versatz von der Bildschirmmitte in logischen Pixeln (Referenzfläche 1920×1080). Bereich ±960. Negative Werte verschieben das HUD nach links, positive nach rechts. Der Wurzelblock ist mittig ausgerichtet.",
		fr = "Décalage horizontal depuis le centre de l'écran en pixels logiques (surface de référence 1920×1080). Plage ±960. Les valeurs négatives déplacent le HUD vers la gauche, les valeurs positives vers la droite. Le bloc racine est aligné au centre.",
		["zh-cn"] = "以屏幕中心为基准的水平偏移（参考分辨率 1920×1080），范围 ±960。负值左移，正值右移。根节点默认居中。",
	},
	position_y = {
		en = "Offset Y",
		ru = "Смещение по Y",
		de = "Versatz Y",
		fr = "Décalage Y",
		["zh-cn"] = "垂直偏移 Y",
	},
	position_y_description = {
		en = "Vertical offset from the screen center in logical pixels (reference canvas 1920×1080). Range ±540. Negative moves the HUD up, positive moves it down. The root block is center-aligned.",
		ru = "Вертикальное смещение от центра экрана в логических пикселях (эталонный холст 1920×1080). Диапазон ±540. Отрицательные значения — вверх, положительные — вниз. Корневой блок привязан к центру экрана.",
		de = "Vertikaler Versatz von der Bildschirmmitte in logischen Pixeln (Referenzfläche 1920×1080). Bereich ±540. Negative Werte verschieben das HUD nach oben, positive nach unten. Der Wurzelblock ist mittig ausgerichtet.",
		fr = "Décalage vertical depuis le centre de l'écran en pixels logiques (surface de référence 1920×1080). Plage ±540. Les valeurs négatives déplacent le HUD vers le haut, les valeurs positives vers le bas. Le bloc racine est aligné au centre.",
		["zh-cn"] = "以屏幕中心为基准的垂直偏移（参考分辨率 1920×1080），范围 ±540。负值上移，正值下移。根节点默认居中。",
	},
	opacity = {
		en = "Opacity",
		ru = "Прозрачность",
		de = "Deckkraft",
		fr = "Opacité",
		["zh-cn"] = "不透明度",
	},
	hud_scale = {
		en = "Scale",
		ru = "Масштаб",
		de = "Skalierung",
		fr = "Échelle",
		["zh-cn"] = "缩放",
	},
	hud_scale_description = {
		en = "Scale multiplier applied to the whole Division HUD (reference canvas 1920×1080). Values below 1 shrink the HUD, values above 1 enlarge it.",
		ru = "Множитель масштаба, применяемый ко всему Division HUD (эталонный холст 1920×1080). Значения меньше 1 уменьшают HUD, больше 1 — увеличивают.",
		de = "Skalierungsfaktor für das gesamte Division HUD (Referenzfläche 1920×1080). Werte unter 1 verkleinern das HUD, Werte über 1 vergrößern es.",
		fr = "Multiplicateur d'échelle appliqué à tout le Division HUD (surface de référence 1920×1080). Les valeurs inférieures à 1 réduisent le HUD, les valeurs supérieures à 1 l'agrandissent.",
		["zh-cn"] = "对整个 Division HUD 应用的缩放倍率（参考分辨率 1920×1080）。小于1缩小，大于1放大。",
	},
	divisionhud_super_bars = {
		en = "\238\128\178 COMBAT HUD",
		ru = "\238\128\178 БОЕВОЙ HUD",
		de = "\238\128\178 KAMPF-HUD",
		fr = "\238\128\178 HUD DE COMBAT",
		["zh-cn"] = "\238\128\178 战斗界面",
	},
	show_stamina_bar = {
		en = "Stamina and dodge bar",
		ru = "Полоса стамины и уворотов",
		de = "Ausdauer- und Ausweichleiste",
		fr = "Barre d'endurance et d'esquive",
		["zh-cn"] = "体力与闪避条",
	},
	show_toughness_bar = {
		en = "Toughness bar",
		ru = "Полоса стойкости",
		de = "Widerstandsleiste",
		fr = "Barre de résistance",
		["zh-cn"] = "韧性条",
	},
	show_health_bar = {
		en = "Health bar",
		ru = "Полоса здоровья",
		de = "Gesundheitsleiste",
		fr = "Barre de santé",
		["zh-cn"] = "生命值条",
	},
	show_ability_timer = {
		en = "Ability bar",
		ru = "Полоса способности",
		de = "Fähigkeitsleiste",
		fr = "Barre de capacité",
		["zh-cn"] = "技能冷却条",
	},
	show_ability_icon = {
		en = "Ability icon",
		ru = "Иконка способности",
		de = "Fähigkeitssymbol",
		fr = "Icône de capacité",
		["zh-cn"] = "技能图标",
	},
	stimm_slot_icon_tint_by_type = {
		en = "Color pocket stimm icon",
		ru = "Цвет иконки шприца",
		de = "Stimm-Symbol im Taschenplatz einfärben",
		fr = "Colorer l'icône du stimulant de poche",
		["zh-cn"] = "注射器图标按类型着色",
	},
	stimm_slot_icon_tint_by_type_description = {
		en = "When enabled, the pocket stimm icon in the Division HUD strip is tinted by syringe template (speed, power, corruption cleanse, ability boost, broker syringe, etc.) using built-in colors. When off, the icon uses the default white tint.",
		ru = "Если включено, иконка карманного шприца в полоске Division HUD окрашивается по шаблону шприца (скорость, сила, снятие порчи, усиление способности, шприц брокера и т.д.) встроенными цветами. Если выключено — обычный белый тон.",
		de = "Wenn aktiviert, wird das Stimm-Symbol im Taschenplatz der Division-HUD-Leiste anhand der Spritzenvorlage eingefärbt (Geschwindigkeit, Kraft, Verderbnisreinigung, Fähigkeitsverstärkung, Broker-Spritze usw.) und nutzt integrierte Farben. Wenn deaktiviert, verwendet das Symbol die standardmäßige weiße Färbung.",
		fr = "Lorsque cette option est activée, l'icône du stimulant de poche dans la barre Division HUD est teintée selon le modèle de seringue (vitesse, puissance, purge de corruption, amélioration de capacité, seringue de courtier, etc.) avec les couleurs intégrées. Lorsqu'elle est désactivée, l'icône utilise la teinte blanche par défaut.",
		["zh-cn"] = "启用后，根据注射器类型（速度、力量、腐蚀清除、技能强化、巢都渣滓注射器等）使用内置颜色为图标着色。关闭时使用默认白色。",
	},
	ammo_text_color_by_fraction = {
		en = "Ammo text color by remaining fraction",
		ru = "Цвет патронов по доле боезапаса",
		de = "Munitionstextfarbe nach verbleibendem Anteil",
		fr = "Couleur du texte des munitions selon la fraction restante",
		["zh-cn"] = "弹药文字按剩余比例变色",
	},
	ammo_text_color_by_fraction_description = {
		en = "When enabled, the large ammo numbers tint by total ammo fraction: above 75% main, above 50% low, above 25% medium, 25% or less high. When off, they use the default main color.",
		ru = "Если включено, крупные цифры патронов окрашиваются по доле боезапаса: выше 75% — основной цвет; выше 50% и не выше 75% — низкий запас; выше 25% и не выше 50% — средний; 25% и ниже — критический. Если выключено — обычный основной цвет.",
		de = "Wenn aktiviert, werden die großen Munitionszahlen nach dem Gesamtmunitionsanteil eingefärbt: über 75% Hauptfarbe, über 50% niedrig, über 25% mittel, 25% oder weniger hoch. Wenn deaktiviert, verwenden sie die standardmäßige Hauptfarbe.",
		fr = "Lorsque cette option est activée, les grands nombres de munitions sont teintés selon la fraction totale de munitions : au-dessus de 75 % couleur principale, au-dessus de 50 % faible, au-dessus de 25 % moyenne, 25 % ou moins élevée. Lorsqu'elle est désactivée, ils utilisent la couleur principale par défaut.",
		["zh-cn"] = "启用后，大号弹药数字按剩余比例变色：75%以上为主色，50%–75%为低量色，25%–50%为中量色，25%及以下为警告色。关闭时使用默认主色。",
	},
	ammo_size_big = {
		en = "big",
		ru = "big",
		de = "big",
		fr = "big",
		["zh-cn"] = "big",
	},
	grenade_color_by_fraction = {
		en = "Grenade slot color by charge fraction",
		ru = "Цвет гранаты по доле зарядов",
		de = "Granatenplatzfarbe nach Ladungsanteil",
		fr = "Couleur de l'emplacement de grenade selon la fraction de charges",
		["zh-cn"] = "手雷槽按充能比例着色",
	},
	grenade_color_by_fraction_description = {
		en = "When enabled, the grenade ability slot icon and counter tint by remaining charges, using the same color bands and fraction thresholds as the large ammo numbers. When off, the slot uses the default colors.",
		ru = "Если включено, иконка и счётчик слота гранаты окрашиваются по доле оставшихся зарядов — те же цветовые полосы и пороги доли, что у крупного текста патронов. Если выключено — цвета по умолчанию.",
		de = "Wenn aktiviert, werden Symbol und Zähler des Granaten-Fähigkeitsplatzes nach verbleibenden Ladungen eingefärbt, mit denselben Farbbereichen und Anteilsschwellen wie die großen Munitionszahlen. Wenn deaktiviert, verwendet der Platz die Standardfarben.",
		fr = "Lorsque cette option est activée, l'icône et le compteur de l'emplacement de capacité de grenade sont teintés selon les charges restantes, avec les mêmes bandes de couleur et seuils de fraction que les grands nombres de munitions. Lorsqu'elle est désactivée, l'emplacement utilise les couleurs par défaut.",
		["zh-cn"] = "启用后，手雷图标与计数按剩余充能比例着色，规则与弹药数字一致。关闭时使用默认颜色。",
	},
	wielded_weapon_icon_state_colors = {
		en = "Current weapon icon colors",
		ru = "Цвет текущего оружия",
		de = "Farben des aktuellen Waffensymbols",
		fr = "Couleurs de l'icône de l'arme actuelle",
		["zh-cn"] = "当前武器图标按状态着色",
	},
	wielded_weapon_icon_state_colors_description = {
		en = "When enabled, tints the wielded-weapon strip icon for weapons included in this mod's internal list by inactive, active, and optional cooldown states. Other weapons stay full white.",
		ru = "Если включено, для оружия из внутреннего списка мода окрашивает иконку текущего оружия в полоске Division HUD по неактивному, активному и при необходимости кулдауну. Для остального оружия остаётся обычный белый.",
		de = "Wenn aktiviert, färbt es das Symbol der geführten Waffe in der Leiste für Waffen aus der internen Liste dieses Mods nach inaktivem, aktivem und optionalem Abklingzeit-Zustand ein. Andere Waffen bleiben vollständig weiß.",
		fr = "Lorsque cette option est activée, elle teinte l'icône de l'arme tenue dans la barre pour les armes incluses dans la liste interne de ce mod selon les états inactif, actif et éventuellement de recharge. Les autres armes restent entièrement blanches.",
		["zh-cn"] = "启用后，模组支持的武器会按未激活、激活、冷却状态变色，其他武器保持白色。",
	},
	buff_rows_enabled = {
		en = "Buff rows",
		ru = "Строки баффов",
		de = "Buff-Zeilen",
		fr = "Lignes de bonus",
		["zh-cn"] = "增益行",
	},
	buff_rows_enabled_description = {
		en = "Displays active player buffs in rows below the stamina/dodge bars (up to 15 buffs, 5 per row).",
		ru = "Отображает активные бафы игрока рядами ниже полос стамины/уклонения (до 15 бафов, по 5 в ряд).",
		de = "Zeigt aktive Spieler-Buffs in Zeilen unter den Ausdauer-/Ausweichleisten an (bis zu 15 Buffs, 5 pro Zeile).",
		fr = "Affiche les bonus actifs du joueur en lignes sous les barres d'endurance/d'esquive (jusqu'à 15 bonus, 5 par ligne).",
		["zh-cn"] = "在耐力/闪避栏下方以行显示玩家的激活增益（最多15个，每行5个）。",
	},
	main_strip_background_fill = {
		en = "Weapon & ammo slots background",
		ru = "Фон под слотами оружия и патронов",
		de = "Hintergrund für Waffen- und Munitionsplätze",
		fr = "Arrière-plan des emplacements d'arme et de munitions",
		["zh-cn"] = "武器与弹药槽背景",
	},
	main_strip_background_fill_description = {
		en = "Fill behind the weapon and ammo slots (Division HUD).",
		ru = "Заливка под слотами оружия и патронов (Division HUD).",
		de = "Füllung hinter den Waffen- und Munitionsplätzen (Division HUD).",
		fr = "Remplissage derrière les emplacements d'arme et de munitions (Division HUD).",
		["zh-cn"] = "武器与弹药槽背后的填充（Division HUD）。",
	},
	proximity_strip_background_fill = {
		en = "Detected items area background",
		ru = "Фон под иконками обнаруженных предметов",
		de = "Hintergrund des Bereichs erkannter Gegenstände",
		fr = "Arrière-plan de la zone des objets détectés",
		["zh-cn"] = "探测物品图标区域背景",
	},
	proximity_strip_background_fill_description = {
		en = "Fill behind proximity item icons; separate from weapon/ammo slots.",
		ru = "Заливка под иконками обнаруженных предметов (proximity), отдельно от слотов оружия и патронов.",
		de = "Füllung hinter Symbolen von Gegenständen in der Nähe; getrennt von Waffen-/Munitionsplätzen.",
		fr = "Remplissage derrière les icônes d'objets proches ; séparé des emplacements d'arme/munitions.",
		["zh-cn"] = "近距离探测到的物品图标背后的填充（与武器/弹药槽分开）。",
	},
	main_strip_background_fill_weapon_hud_plain = {
		en = "Weapon fill only",
		ru = "Только оружейная заливка",
		de = "Nur Waffenfüllung",
		fr = "Remplissage d'arme uniquement",
		["zh-cn"] = "仅武器填充",
	},
	main_strip_background_fill_weapon_hud = {
		en = "Weapon fill + frame",
		ru = "Оружейная заливка + рамка",
		de = "Waffenfüllung + Rahmen",
		fr = "Remplissage d'arme + cadre",
		["zh-cn"] = "武器填充 + 边框",
	},
	main_strip_background_fill_terminal = {
		en = "Terminal gradient green",
		ru = "Терминальный градиент зеленый",
		de = "Terminal-Verlauf grün",
		fr = "Dégradé terminal vert",
		["zh-cn"] = "终端渐变绿色",
	},
	main_strip_background_fill_black = {
		en = "Terminal gradient black",
		ru = "Терминальный градиент черный",
		de = "Terminal-Verlauf schwarz",
		fr = "Dégradé terminal noir",
		["zh-cn"] = "终端渐变黑色",
	},
	divisionhud_super_danger_zone = {
		en = "\238\128\161 DANGER ZONE",
		ru = "\238\128\161 ОПАСНАЯ ЗОНА",
		de = "\238\128\161 GEFAHRENBEREICH",
		fr = "\238\128\161 ZONE DANGEREUSE",
		["zh-cn"] = "\238\128\161 危险区域",
	},
	danger_zone_label = {
		en = "Danger zone",
		ru = "Опасная зона",
		de = "Gefahrenbereich",
		fr = "Zone dangereuse",
		["zh-cn"] = "危险区域",
	},
	danger_zone_in_zone = {
		en = "In blast\nzone",
		ru = "В зоне\nпоражения",
		de = "Im Explosions-\nbereich",
		fr = "Dans la zone\nd'explosion",
		["zh-cn"] = "位于\n危险区",
	},
	danger_zone_enabled = {
		en = "Enable danger zone",
		ru = "Включить опасную зону",
		de = "Gefahrenbereich aktivieren",
		fr = "Activer la zone dangereuse",
		["zh-cn"] = "启用危险区域",
	},
	danger_zone_enabled_description = {
		en = "Shows the Danger zone block when you approach tracked hazardous areas.",
		ru = "Показывает блок Danger zone при приближении к отслеживаемым опасным зонам.",
		de = "Zeigt den Gefahrenbereich-Block an, wenn du dich verfolgten Gefahrenzonen näherst.",
		fr = "Affiche le bloc Zone dangereuse lorsque vous approchez de zones dangereuses suivies.",
		["zh-cn"] = "接近已追踪的危险区域时显示 Danger zone 模块。",
	},
	danger_zone_radius = {
		en = "Detection distance (m)",
		ru = "Расстояние обнаружения (м)",
		de = "Erkennungsentfernung (m)",
		fr = "Distance de détection (m)",
		["zh-cn"] = "检测距离（米）",
	},
	danger_zone_radius_description = {
		en = "Maximum distance in meters from the edge of a tracked danger zone to show the Danger zone block.",
		ru = "Максимальное расстояние в метрах от границы отслеживаемой опасной зоны, на котором показывается блок Danger zone.",
		de = "Maximale Entfernung in Metern vom Rand eines verfolgten Gefahrenbereichs, bei der der Gefahrenbereich-Block angezeigt wird.",
		fr = "Distance maximale en mètres depuis le bord d'une zone dangereuse suivie pour afficher le bloc Zone dangereuse.",
		["zh-cn"] = "距离已追踪危险区域边缘的最大显示距离（米）。",
	},
	danger_zone_los_check = {
		en = "Account for obstacles (line of sight)",
		ru = "Учитывать препятствия (видимость)",
		de = "Hindernisse berücksichtigen (Sichtlinie)",
		fr = "Tenir compte des obstacles (ligne de vue)",
		["zh-cn"] = "考虑遮挡物（视线）",
	},
	danger_zone_los_check_description = {
		en = "Ignore danger sources separated from you by walls, floors or bridges (line-of-sight raycast). Disable to use distance only.",
		ru = "Игнорировать источники опасности, отделённые от вас стенами, полом или мостом (проверка прямой видимости лучом). Отключите, чтобы учитывать только расстояние.",
		de = "Ignoriert Gefahrenquellen, die durch Wände, Böden oder Brücken von dir getrennt sind (Sichtlinien-Raycast). Deaktivieren, um nur die Entfernung zu verwenden.",
		fr = "Ignore les sources de danger séparées de vous par des murs, sols ou ponts (raycast de ligne de vue). Désactivez cette option pour utiliser uniquement la distance.",
		["zh-cn"] = "忽略被墙壁、楼板或桥梁分隔的危险源（视线射线检测）。关闭则仅按距离判定。",
	},
	danger_zone_show_daemonhost = {
		en = "Daemonhost",
		ru = "Демонхост",
		de = "Dämonenhost",
		fr = "Démonhôte",
		["zh-cn"] = "恶魔宿主",
	},
	danger_zone_show_daemonhost_description = {
		en = "Show alerts for this unit (spawn and alert stages).",
		ru = "Показывать оповещения для этого юнита (появление и стадии тревоги).",
		de = "Warnungen für diese Einheit anzeigen (Erscheinen und Alarmstufen).",
		fr = "Afficher les alertes pour cette unité (apparition et phases d'alerte).",
		["zh-cn"] = "显示该单位的警报（出生与各警戒阶段）。",
	},
	danger_zone_show_daemonhost_aura = {
		en = "Daemonhost corruption aura",
		ru = "Аура демонхоста",
		de = "Verderbnis-Aura des Dämonenhosts",
		fr = "Aura de corruption du Démonhôte",
		["zh-cn"] = "恶魔宿主腐化光环",
	},
	danger_zone_show_daemonhost_aura_description = {
		en = "Show the radius of this corruption aura (area effect around the unit).",
		ru = "Показывать радиус этой коррумпирующей ауры (область воздействия вокруг юнита).",
		de = "Radius dieser Verderbnis-Aura anzeigen (Flächeneffekt um die Einheit).",
		fr = "Afficher le rayon de cette aura de corruption (effet de zone autour de l'unité).",
		["zh-cn"] = "显示该腐化光环的半径（单位周围的区域效果）。",
	},
	danger_zone_show_poxburster = {
		en = "Poxburster",
		ru = "Поксбёрстер",
		de = "Poxburster",
		fr = "Poxburster",
		["zh-cn"] = "瘟疫爆弹者",
	},
	danger_zone_show_poxburster_description = {
		en = "Show alerts for this explosion threat — uses its explosion radius.",
		ru = "Показывать оповещения для этой взрывной угрозы — используется её радиус взрыва.",
		de = "Warnungen für diese Explosionsgefahr anzeigen — verwendet ihren Explosionsradius.",
		fr = "Afficher les alertes pour cette menace explosive — utilise son rayon d'explosion.",
		["zh-cn"] = "显示该爆炸威胁的警报（使用其爆炸半径）。",
	},
	danger_zone_show_tox_flamer = {
		en = "Tox flamer",
		ru = "Токс-огнемётчик",
		de = "Tox-Flamer",
		fr = "Lance-flammes toxique",
		["zh-cn"] = "毒焰喷射者",
	},
	danger_zone_show_tox_flamer_description = {
		en = "Show alerts for this fire threat (backpack/flare explosions). Uses its explosion radius.",
		ru = "Показывать оповещения для этой огненной угрозы (взрывы ранца). Используется её радиус взрыва.",
		de = "Warnungen für diese Feuergefahr anzeigen (Rucksack-/Fackel-Explosionen). Verwendet ihren Explosionsradius.",
		fr = "Afficher les alertes pour cette menace incendiaire (explosions de sac à dos/fusée). Utilise son rayon d'explosion.",
		["zh-cn"] = "显示该火焰威胁的警报（背包/喷射器爆炸），使用其爆炸半径。",
	},
	danger_zone_show_scab_flamer = {
		en = "Scab flamer",
		ru = "Скаб-огнемётчик",
		de = "Scab-Flamer",
		fr = "Lance-flammes Scab",
		["zh-cn"] = "血痂喷火兵",
	},
	danger_zone_show_scab_flamer_description = {
		en = "Show alerts for this fire threat (backpack explosions). Uses its explosion radius.",
		ru = "Показывать оповещения для этой огненной угрозы (взрывы ранца). Используется её радиус взрыва.",
		de = "Warnungen für diese Feuergefahr anzeigen (Rucksackexplosionen). Verwendet ihren Explosionsradius.",
		fr = "Afficher les alertes pour cette menace incendiaire (explosions de sac à dos). Utilise son rayon d'explosion.",
		["zh-cn"] = "显示该火焰威胁的警报（背包爆炸），使用其爆炸半径。",
	},
	danger_zone_show_bomber_grenade = {
		en = "Bomber grenade",
		ru = "Граната бомбардира",
		de = "Bombergranate",
		fr = "Grenade de bombardier",
		["zh-cn"] = "投弹兵手雷",
	},
	danger_zone_show_bomber_grenade_description = {
		en = "Show alerts for Bomber grenade explosions — uses the grenade explosion radius.",
		ru = "Показывать оповещения о гранатах бомбардира — используется радиус взрыва гранаты.",
		de = "Warnungen für Bombergranaten-Explosionen anzeigen — verwendet den Explosionsradius der Granate.",
		fr = "Afficher les alertes pour les explosions de grenades de bombardier — utilise le rayon d'explosion de la grenade.",
		["zh-cn"] = "显示投弹兵手雷爆炸警报（使用手雷爆炸半径）。",
	},
	danger_zone_show_explosive_barrel = {
		en = "Explosive barrel",
		ru = "Взрывная бочка",
		de = "Explosives Fass",
		fr = "Baril explosif",
		["zh-cn"] = "爆炸桶",
	},
	danger_zone_show_explosive_barrel_description = {
		en = "Show alerts for explosive barrels — uses the barrel explosion radius.",
		ru = "Показывать оповещения о взрывных бочках — используется радиус взрыва бочки.",
		de = "Warnungen für explosive Fässer anzeigen — verwendet den Explosionsradius des Fasses.",
		fr = "Afficher les alertes pour les barils explosifs — utilise le rayon d'explosion du baril.",
		["zh-cn"] = "显示爆炸桶的警报（使用其爆炸半径）。",
	},
	danger_zone_show_fire_barrel = {
		en = "Fire barrel",
		ru = "Огненная бочка",
		de = "Feuerfass",
		fr = "Baril incendiaire",
		["zh-cn"] = "火焰桶",
	},
	danger_zone_show_fire_barrel_description = {
		en = "Show alerts for fire barrels — uses the fire barrel radius.",
		ru = "Показывать оповещения о огненных бочках — используется радиус их воздействия.",
		de = "Warnungen für Feuerfässer anzeigen — verwendet den Radius des Feuerfasses.",
		fr = "Afficher les alertes pour les barils incendiaires — utilise le rayon du baril incendiaire.",
		["zh-cn"] = "显示火焰桶的警报（使用其影响半径）。",
	},
	divisionhud_super_dynamic = {
		en = "\238\129\135 DYNAMIC HUD",
		ru = "\238\129\135 ДИНАМИЧЕСКИЙ HUD",
		de = "\238\129\135 DYNAMISCHES HUD",
		fr = "\238\129\135 HUD DYNAMIQUE",
		["zh-cn"] = "\238\129\135 动态界面",
	},
	dynamic_hud = {
		en = "Dynamic HUD",
		ru = "Динамический HUD",
		de = "Dynamisches HUD",
		fr = "HUD dynamique",
		["zh-cn"] = "动态界面",
	},
	dynamic_hud_strength = {
		en = "Shift strength",
		ru = "Сила сдвига",
		de = "Verschiebungsstärke",
		fr = "Force du décalage",
		["zh-cn"] = "偏移强度",
	},
	dynamic_hud_pitch_ratio = {
		en = "Vertical ratio",
		ru = "Вертикаль относительно горизонтали",
		de = "Vertikales Verhältnis",
		fr = "Ratio vertical",
		["zh-cn"] = "垂直偏移比例",
	},
	dynamic_hud_decay = {
		en = "Return speed",
		ru = "Скорость возврата",
		de = "Rückkehrgeschwindigkeit",
		fr = "Vitesse de retour",
		["zh-cn"] = "界面回弹速度",
	},
	dynamic_hud_max_offset = {
		en = "Max offset",
		ru = "Макс. смещение",
		de = "Max. Versatz",
		fr = "Décalage max.",
		["zh-cn"] = "界面最大偏移量",
	},
	dynamic_hud_freeze_on_ads = {
		en = "Freeze when aiming",
		ru = "Стабилизировать при прицеливании",
		de = "Beim Zielen einfrieren",
		fr = "Figer pendant la visée",
		["zh-cn"] = "瞄准时锁定界面",
	},
	dynamic_hud_freeze_on_ads_description = {
		en = "Freezes HUD movement while aiming down sights (works with mouse and controllers).",
		ru = "Фиксирует динамику HUD при прицеливании. Работает с мышью и геймпадом.",
		de = "Friert die HUD-Bewegung beim Zielen über Kimme und Korn ein (funktioniert mit Maus und Controllern).",
		fr = "Fige le mouvement du HUD pendant la visée (fonctionne avec la souris et les manettes).",
		["zh-cn"] = "瞄准时锁定界面偏移（支持鼠标和手柄）。",
	},
	divisionhud_super_vanilla_hide = {
		en = "\238\128\161 VANILLA HUD",
		ru = "\238\128\161 ВАНИЛЬНЫЙ HUD",
		de = "\238\128\161 VANILLA-HUD",
		fr = "\238\128\161 HUD VANILLA",
		["zh-cn"] = "\238\128\161 原版界面",
	},
	hide_vanilla_team_panel_local = {
		en = "Hide local player panel",
		ru = "Скрыть панель локального игрока",
		de = "Lokales Spielerfenster ausblenden",
		fr = "Masquer le panneau du joueur local",
		["zh-cn"] = "隐藏本地玩家面板",
	},
	hide_vanilla_stamina_area = {
		en = "Hide stamina",
		ru = "Скрыть стамину",
		de = "Ausdauer ausblenden",
		fr = "Masquer l'endurance",
		["zh-cn"] = "隐藏体力条",
	},
	hide_vanilla_dodge_area = {
		en = "Hide dodges",
		ru = "Скрыть увороты",
		de = "Ausweichmanöver ausblenden",
		fr = "Masquer les esquives",
		["zh-cn"] = "隐藏闪避计数",
	},
	hide_vanilla_weapon_pivot = {
		en = "Hide weapons",
		ru = "Скрыть оружие",
		de = "Waffen ausblenden",
		fr = "Masquer les armes",
		["zh-cn"] = "隐藏武器显示",
	},
	hide_vanilla_combat_ability_slot = {
		en = "Hide combat ability",
		ru = "Скрыть боевую способность",
		de = "Kampffähigkeit ausblenden",
		fr = "Masquer la capacité de combat",
		["zh-cn"] = "隐藏战斗技能",
	},
	hide_vanilla_player_buffs_background = {
		en = "Hide buffs",
		ru = "Скрыть баффы",
		de = "Buffs ausblenden",
		fr = "Masquer les bonus",
		["zh-cn"] = "隐藏增益效果",
	},
	hide_vanilla_mission_objectives = {
		en = "Hide mission objectives",
		ru = "Скрыть цели миссии",
		de = "Missionsziele ausblenden",
		fr = "Masquer les objectifs de mission",
		["zh-cn"] = "隐藏任务目标",
	},
	hide_vanilla_mission_objectives_description = {
		en = "When enabled, only the center mission objective popups are hidden; the objective feed (including the area strip) keeps drawing. Use the Mission objectives section to mirror selected popup events into the Division HUD notification strip.",
		ru = "Если включено, скрываются только центральные всплывающие окна целей; лента целей (включая область area) продолжает отображаться. В блоке «Цели миссии» можно дублировать выбранные события попапов в полоску оповещений Division HUD.",
		de = "Wenn aktiviert, werden nur die zentralen Missionsziel-Popups ausgeblendet; der Zielfeed (einschließlich Bereichsleiste) wird weiter gezeichnet. Im Abschnitt Missionsziele kannst du ausgewählte Popup-Ereignisse in die Benachrichtigungsleiste des Division HUD spiegeln.",
		fr = "Lorsque cette option est activée, seuls les popups centraux d'objectifs de mission sont masqués ; le flux d'objectifs (y compris la barre de zone) continue d'être affiché. Utilisez la section Objectifs de mission pour répliquer certains événements de popup dans la barre de notification de Division HUD.",
		["zh-cn"] = "启用后仅隐藏中央任务弹窗，目标条带仍保留。可在任务目标设置中，将弹窗事件同步显示到 Division HUD 提示栏。",
	},
	alerts_super = {
		en = "\238\128\161 ALERTS",
		ru = "\238\128\161 ОПОВЕЩЕНИЯ",
		de = "\238\128\161 WARNUNGEN",
		fr = "\238\128\161 ALERTES",
		["zh-cn"] = "\238\128\161 警报",
	},
	alerts_enabled = {
		en = "Enable approach alerts",
		ru = "Включить оповещения о приближении",
		de = "Annäherungswarnungen aktivieren",
		fr = "Activer les alertes d'approche",
		["zh-cn"] = "启用敌人接近警报",
	},
	alerts_max_visible = {
		en = "Maximum simultaneous alerts",
		ru = "Максимум одновременных оповещений",
		de = "Maximale gleichzeitige Warnungen",
		fr = "Nombre maximal d'alertes simultanées",
		["zh-cn"] = "同时显示警报上限",
	},
	alerts_duration_sec = {
		en = "Alert duration (seconds)",
		ru = "Время показа оповещения (сек.)",
		de = "Warnungsdauer (Sekunden)",
		fr = "Durée de l'alerte (secondes)",
		["zh-cn"] = "警报显示时长（秒）",
	},
	alerts_show_duration_bar = {
		en = "Alert display time bar",
		ru = "Полоса времени показа оповещения",
		de = "Leiste für Warnungsanzeigezeit",
		fr = "Barre de durée d'affichage de l'alerte",
		["zh-cn"] = "显示警报持续时间条",
	},
	alerts_group_threats = {
		en = string.rep("\194\160", 8) .. "Threats",
		ru = string.rep("\194\160", 8) .. "Угрозы",
		de = string.rep("\194\160", 8) .. "Bedrohungen",
		fr = string.rep("\194\160", 8) .. "Menaces",
		["zh-cn"] = string.rep("\194\160", 8) .. "威胁",
	},
	alerts_group_threats_description = {
		en = "Alerts when a monster changes its target after the first detection.",
		ru = "Оповещения, когда монстр меняет цель после первого обнаружения.",
		de = "Warnungen, wenn ein Monster nach der ersten Erkennung sein Ziel wechselt.",
		fr = "Alertes lorsqu'un monstre change de cible après la première détection.",
		["zh-cn"] = "怪物首次侦测后切换目标时显示警报。",
	},
	threat_advisor_show_monsters = {
		en = "Monster target change",
		ru = "Смена цели монстра",
		de = "Zielwechsel von Monstern",
		fr = "Changement de cible des monstres",
		["zh-cn"] = "怪物切换目标",
	},
	threat_advisor_show_monsters_description = {
		en = "Show an Attention Threat alert when a monster changes target after its first detection.",
		ru = "Показывать оповещение «Внимание угроза», когда монстр меняет цель после первого обнаружения.",
		de = "Zeigt eine Achtung-Bedrohung-Warnung, wenn ein Monster nach der ersten Erkennung sein Ziel wechselt.",
		fr = "Affiche une alerte Attention : menace lorsqu'un monstre change de cible après la première détection.",
		["zh-cn"] = "怪物首次侦测后切换目标时显示“注意：威胁”警报。",
	},
	alerts_group_bosses = {
		en = string.rep("\194\160", 8) .. "Bosses",
		ru = string.rep("\194\160", 8) .. "Боссы",
		de = string.rep("\194\160", 8) .. "Bosse",
		fr = string.rep("\194\160", 8) .. "Boss",
		["zh-cn"] = string.rep("\194\160", 8) .. "首领",
	},
	alerts_group_specialists = {
		en = string.rep("\194\160", 8) .. "Specialists",
		ru = string.rep("\194\160", 8) .. "Специалисты",
		de = string.rep("\194\160", 8) .. "Spezialisten",
		fr = string.rep("\194\160", 8) .. "Spécialistes",
		["zh-cn"] = string.rep("\194\160", 8) .. "专家",
	},
	mission_objectives_super = {
		en = string.rep("\194\160", 8) .. "Mission objectives",
		ru = string.rep("\194\160", 8) .. "Цели миссии",
		de = string.rep("\194\160", 8) .. "Missionsziele",
		fr = string.rep("\194\160", 8) .. "Objectifs de mission",
		["zh-cn"] = string.rep("\194\160", 8) .. "任务目标",
	},
	mission_objectives_super_description = {
		en = "When «Hide mission objectives» is on (VANILLA HUD section), these toggles choose which objective events appear in the Division HUD strip (title row + body; same look as enemy approach notifications).",
		ru = "Когда включено «Скрыть цели миссии» (супергруппа «Ванильный HUD»), эти переключатели задают, какие события целей показывать в полоске оповещений Division HUD (заголовок в полоске + текст цели, оформление как при оповещении о приближении).",
		de = "Wenn «Missionsziele ausblenden» aktiviert ist (Abschnitt VANILLA-HUD), legen diese Schalter fest, welche Zielereignisse in der Division-HUD-Leiste erscheinen (Titelzeile + Text; gleiches Aussehen wie Warnungen vor nahenden Gegnern).",
		fr = "Lorsque « Masquer les objectifs de mission » est activé (section HUD VANILLA), ces options choisissent quels événements d'objectif apparaissent dans la barre Division HUD (ligne de titre + corps ; même apparence que les notifications d'approche d'ennemis).",
		["zh-cn"] = "在原版界面设置中启用“隐藏任务目标”后，可通过这些开关选择哪些事件显示在 Division HUD 提示栏。",
	},
	alert_mission_objective_start = {
		en = "New objective",
		ru = "Новая цель",
		de = "Neues Ziel",
		fr = "Nouvel objectif",
		["zh-cn"] = "新目标",
	},
	alert_mission_objective_start_description = {
		en = "When enabled, show in the Division HUD strip when a mission objective starts (same title and description as the standard center popup).",
		ru = "Показывать в полоске Division HUD при старте цели миссии (тот же заголовок и текст, что у стандартного попапа по центру).",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn ein Missionsziel startet (gleicher Titel und gleiche Beschreibung wie im standardmäßigen zentralen Popup).",
		fr = "Lorsque cette option est activée, affiche dans la barre Division HUD le début d'un objectif de mission (mêmes titre et description que le popup central standard).",
		["zh-cn"] = "任务目标开始时，在 Division HUD 栏显示与中央弹窗相同的标题与描述。",
	},
	alert_mission_objective_progress = {
		en = "Objective progress",
		ru = "Прогресс цели",
		de = "Zielfortschritt",
		fr = "Progression de l'objectif",
		["zh-cn"] = "目标进度",
	},
	alert_mission_objective_progress_description = {
		en = "When enabled, show in the Division HUD strip when the game would show a progression popup for an objective (with counter text when applicable).",
		ru = "Показывать в полоске Division HUD, когда игра показала бы попап прогресса цели (со счётчиком, если он есть).",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn das Spiel ein Fortschritts-Popup für ein Ziel anzeigen würde (mit Zählertext, falls vorhanden).",
		fr = "Lorsque cette option est activée, affiche dans la barre Division HUD lorsque le jeu afficherait un popup de progression pour un objectif (avec le texte du compteur le cas échéant).",
		["zh-cn"] = "游戏显示目标进度弹窗时，在 Division HUD 栏同步显示（含计数）。",
	},
	alert_mission_objective_complete = {
		en = "Objective complete",
		ru = "Цель выполнена",
		de = "Ziel abgeschlossen",
		fr = "Objectif terminé",
		["zh-cn"] = "目标完成",
	},
	alert_mission_objective_complete_description = {
		en = "When enabled, show in the Division HUD strip when a mission objective completes.",
		ru = "Показывать в полоске Division HUD при завершении цели миссии.",
		de = "Wenn aktiviert, in der Division-HUD-Leiste anzeigen, wenn ein Missionsziel abgeschlossen wird.",
		fr = "Lorsque cette option est activée, affiche dans la barre Division HUD lorsqu'un objectif de mission est terminé.",
		["zh-cn"] = "任务目标完成时在 Division HUD 栏显示提示。",
	},
	alert_mission_objective_custom_popup = {
		en = "Scripted objective popups",
		ru = "Сюжетные всплывашки целей",
		de = "Geskriptete Ziel-Popups",
		fr = "Popups d'objectif scriptés",
		["zh-cn"] = "剧情脚本目标弹窗",
	},
	alert_mission_objective_custom_popup_description = {
		en = "When enabled, show in the Division HUD strip for generic mission popup events (event_show_objective_popup), e.g. some narrative beats.",
		ru = "Показывать в полоске Division HUD для общих всплывашек целей (event_show_objective_popup), например сюжетных сообщений.",
		de = "Wenn aktiviert, in der Division-HUD-Leiste für allgemeine Missions-Popup-Ereignisse anzeigen (event_show_objective_popup), z. B. manche erzählerische Momente.",
		fr = "Lorsque cette option est activée, affiche dans la barre Division HUD les événements génériques de popup de mission (event_show_objective_popup), par exemple certains moments narratifs.",
		["zh-cn"] = "对通用任务弹窗事件（如剧情提示）在 Division HUD 栏显示。",
	},
	mission_objective_custom_popup_strip_fallback = {
		en = "OBJECTIVE",
		ru = "ЦЕЛЬ",
		de = "ZIEL",
		fr = "OBJECTIF",
		["zh-cn"] = "目标",
	},
	alerts_group_team = {
		en = string.rep("\194\160", 8) .. "Strike team",
		ru = string.rep("\194\160", 8) .. "Ударная группа",
		de = string.rep("\194\160", 8) .. "Einsatzteam",
		fr = string.rep("\194\160", 8) .. "Équipe d'assaut",
		["zh-cn"] = string.rep("\194\160", 8) .. "小队",
	},
	alerts_group_team_description = {
		en = "Show teammate knockdowns, trapper net, Pox Hound pin, ledge hang, Beast of Nurgle consume, and deaths in the Division HUD alert strip. The player name uses the squad slot color.",
		ru = "Показывать нокдауны, сеть ловушечника, схват чумной гончей, висение на уступе, поглощение зверем Нургла и смерти в полоске оповещений Division HUD. Ник окрашивается цветом слота отряда.",
		de = "Zeigt Niederschläge von Teammitgliedern, Fallensteller-Netz, Pox-Hound-Fixierung, Hängen an Kanten, Verschlingen durch die Bestie des Nurgle und Tode in der Warnleiste des Division HUD. Der Spielername nutzt die Farbe des Truppplatzes.",
		fr = "Affiche les mises à terre d'alliés, le filet du piégeur, l'immobilisation par un molosse de la peste, la suspension à une corniche, l'absorption par la Bête de Nurgle et les morts dans la barre d'alerte Division HUD. Le nom du joueur utilise la couleur de l'emplacement d'escouade.",
		["zh-cn"] = "在警报栏显示队友倒地、被网、被狗咬、悬挂悬崖、被吞、阵亡等状态。玩家名称使用队伍颜色。",
	},
	alerts_team_knock = {
		en = "Teammate knocked down",
		ru = "Союзник упал",
		de = "Teammitglied niedergeschlagen",
		fr = "Allié à terre",
		["zh-cn"] = "队友倒地",
	},
	alerts_team_knock_description = {
		en = "When a teammate enters the knocked down state, enqueue an alert line (wording includes that help is needed).",
		ru = "Когда союзник падает в нокдаун, добавлять строку в оповещения (в тексте указано, что нужна помощь).",
		de = "Wenn ein Teammitglied niedergeschlagen wird, eine Warnzeile einreihen (der Text enthält, dass Hilfe benötigt wird).",
		fr = "Lorsqu'un allié passe à l'état à terre, ajoute une ligne d'alerte (le texte indique qu'il a besoin d'aide).",
		["zh-cn"] = "队友倒地时显示警报，并提示需要帮助。",
	},
	alerts_team_net = {
		en = "Caught in net",
		ru = "Пойман в сеть",
		de = "Im Netz gefangen",
		fr = "Pris dans un filet",
		["zh-cn"] = "被网困住",
	},
	alerts_team_net_description = {
		en = "When a teammate is netted (Scab Trapper), enqueue an alert. Uses character_state / disabled checks like the player panel, and also when the state machine applies a server correction to netted so other players on your client are covered.",
		ru = "Когда союзник в сети ловушечника — строка в оповещениях. Те же проверки character_state / disabled, что у панели игрока; дополнительно при server_correction_occurred в netted, чтобы срабатывало и для союзников с репликацией состояния.",
		de = "Wenn ein Teammitglied im Netz ist (Scab Trapper), eine Warnung einreihen. Nutzt character_state-/disabled-Prüfungen wie das Spielerfenster und zusätzlich, wenn die Zustandsmaschine eine Serverkorrektur auf netted anwendet, damit andere Spieler auf deinem Client abgedeckt sind.",
		fr = "Lorsqu'un allié est pris dans un filet (Scab Trapper), ajoute une alerte. Utilise les vérifications character_state / disabled comme le panneau joueur, ainsi que lorsque la machine d'état applique une correction serveur vers netted afin de couvrir les autres joueurs sur votre client.",
		["zh-cn"] = "队友被陷阱兵网住时显示警报，判定逻辑与原版玩家面板一致，并兼容服务器状态同步。",
	},
	alerts_team_hound = {
		en = "Pox Hound on teammate",
		ru = "Чумная Гончая на союзнике",
		de = "Pox Hound auf Teammitglied",
		fr = "Molosse de la peste sur un allié",
		["zh-cn"] = "瘟疫猎犬扑中队友",
	},
	alerts_team_hound_description = {
		en = "When a teammate enters the pounced disabled state (Pox Hound pin), enqueue an alert line. Uses the same disabled_character_state check as the vanilla player panel.",
		ru = "Когда союзник в состоянии «схвачен» с типом pounced (чумная гончая), добавлять строку. Проверка disabled_character_state + PlayerUnitStatus.is_pounced, как у ванильной панели игрока.",
		de = "Wenn ein Teammitglied in den deaktivierten Zustand pounced gerät (Pox-Hound-Fixierung), eine Warnzeile einreihen. Nutzt dieselbe disabled_character_state-Prüfung wie das Vanilla-Spielerfenster.",
		fr = "Lorsqu'un allié entre dans l'état désactivé pounced (immobilisation par un molosse de la peste), ajoute une ligne d'alerte. Utilise la même vérification disabled_character_state que le panneau joueur vanilla.",
		["zh-cn"] = "队友被瘟疫猎犬扑倒压制时显示警报，使用与原版一致的状态判定。",
	},
	alerts_team_ledge = {
		en = "Hanging on ledge",
		ru = "Висит на уступе",
		de = "Hängt an einer Kante",
		fr = "Suspendu à une corniche",
		["zh-cn"] = "悬挂悬崖",
	},
	alerts_team_ledge_description = {
		en = "When a teammate enters ledge_hanging (needs pull-up help), enqueue an alert line. Uses PlayerUnitStatus.is_ledge_hanging on character_state.",
		ru = "Когда союзник в состоянии ledge_hanging (висит на уступе, нужен подтяг), добавлять строку. Проверка PlayerUnitStatus.is_ledge_hanging по character_state.",
		de = "Wenn ein Teammitglied in ledge_hanging gerät (hängt an einer Kante und braucht Hilfe beim Hochziehen), eine Warnzeile einreihen. Nutzt PlayerUnitStatus.is_ledge_hanging auf character_state.",
		fr = "Lorsqu'un allié passe en ledge_hanging (suspendu à une corniche et a besoin d'aide pour remonter), ajoute une ligne d'alerte. Utilise PlayerUnitStatus.is_ledge_hanging sur character_state.",
		["zh-cn"] = "队友悬挂在悬崖需要救援时显示警报。",
	},
	alerts_team_consumed = {
		en = "Swallowed by Beast of Nurgle",
		ru = "Поглощён Зверем Нургла",
		de = "Von der Bestie des Nurgle verschlungen",
		fr = "Avalé par la Bête de Nurgle",
		["zh-cn"] = "被纳垢巨兽吞噬",
	},
	alerts_team_consumed_description = {
		en = "When a teammate enters the consumed disabled state (Beast of Nurgle), enqueue an alert line. Uses PlayerUnitStatus.is_consumed on disabled_character_state.",
		ru = "Когда союзник в состоянии consumed (поглощён зверем Нургла), добавлять строку. Проверка PlayerUnitStatus.is_consumed по disabled_character_state.",
		de = "Wenn ein Teammitglied in den deaktivierten Zustand consumed gerät (Bestie des Nurgle), eine Warnzeile einreihen. Nutzt PlayerUnitStatus.is_consumed auf disabled_character_state.",
		fr = "Lorsqu'un allié passe à l'état désactivé consumed (Bête de Nurgle), ajoute une ligne d'alerte. Utilise PlayerUnitStatus.is_consumed sur disabled_character_state.",
		["zh-cn"] = "队友被纳垢巨兽吞入体内时显示警报。",
	},
	alerts_team_death = {
		en = "Teammate death",
		ru = "Смерть союзника",
		de = "Tod eines Teammitglieds",
		fr = "Mort d'un allié",
		["zh-cn"] = "队友阵亡",
	},
	alerts_team_death_description = {
		en = "When a teammate dies, enqueue an alert line.",
		ru = "Когда союзник умирает, добавлять строку в оповещения.",
		de = "Wenn ein Teammitglied stirbt, eine Warnzeile einreihen.",
		fr = "Lorsqu'un allié meurt, ajoute une ligne d'alerte.",
		["zh-cn"] = "队友死亡时显示警报。",
	},
	alerts_team_strip = {
		en = "Strike team",
		ru = "Ударная группа",
		de = "Einsatzteam",
		fr = "Équipe d'assaut",
		["zh-cn"] = "小队",
	},
	alerts_team_suffix_knock = {
		en = "knocked down, needs help",
		ru = "упал, нужна помощь",
		de = "niedergeschlagen, braucht Hilfe",
		fr = "à terre, a besoin d'aide",
		["zh-cn"] = "倒地，需要帮助",
	},
	alerts_team_suffix_death = {
		en = "died",
		ru = "погиб",
		de = "ist gestorben",
		fr = "est mort",
		["zh-cn"] = "阵亡",
	},
	alerts_team_suffix_trapper_net = {
		en = "was ensnared by a Scab Trapper",
		ru = "пойман в сеть Скаб Ловушечника",
		de = "wurde von einem Scab Trapper gefangen",
		fr = "a été piégé par un Scab Trapper",
		["zh-cn"] = "被血痂陷阱手的网困住",
	},
	alerts_team_suffix_hound_pounce = {
		en = "was pinned by a Pox Hound",
		ru = "схватила Чумная гончая",
		de = "wurde von einem Pox Hound festgenagelt",
		fr = "a été immobilisé par un molosse de la peste",
		["zh-cn"] = "被瘟疫猎犬扑倒",
	},
	alerts_team_suffix_ledge_hanging = {
		en = "is hanging on a ledge, needs help",
		ru = "висит на уступе, нужна помощь",
		de = "hängt an einer Kante, braucht Hilfe",
		fr = "est suspendu à une corniche, a besoin d'aide",
		["zh-cn"] = "悬挂在悬崖，需要救援",
	},
	alerts_team_suffix_consumed = {
		en = "consumed by a Beast of Nurgle",
		ru = "поглощён зверем Нургла",
		de = "von einer Bestie des Nurgle verschlungen",
		fr = "avalé par une Bête de Nurgle",
		["zh-cn"] = "被纳垢兽吞噬",
	},
	alerts_ui_banner_alert = {
		en = "ALERT",
		ru = "ВНИМАНИЕ",
		de = "WARNUNG",
		fr = "ALERTE",
		["zh-cn"] = "警报",
	},
	alerts_message_specialist_approach = {
		en = "Spotted %s",
		ru = "Замечен %s",
		de = "%s gesichtet",
		fr = "%s repéré",
		["zh-cn"] = "发现%s",
	},
	alerts_message_boss_approach = {
		en = "Spotted %s",
		ru = "Замечен %s",
		de = "%s gesichtet",
		fr = "%s repéré",
		["zh-cn"] = "发现%s",
	},
	alerts_message_spawn_grouped = {
		en = "Spotted %s x%d",
		ru = "Замечен %s x%d",
		de = "%s x%d gesichtet",
		fr = "%s x%d repérés",
		["zh-cn"] = "发现%s x%d",
	},
	alerts_message_spawn_target = {
		en = "Spotted %s, pursuing %s",
		ru = "Замечен %s, преследует %s",
		de = "%s gesichtet, verfolgt %s",
		fr = "%s repéré, poursuit %s",
		["zh-cn"] = "发现%s，正在追击%s",
	},
	alerts_threat_strip = {
		en = "ATTENTION THREAT",
		ru = "ВНИМАНИЕ УГРОЗА",
		de = "ACHTUNG BEDROHUNG",
		fr = "ATTENTION MENACE",
		["zh-cn"] = "注意：威胁",
	},
	alerts_message_threat_target_you = {
		en = "%s switched target to you",
		ru = "%s сменил цель на тебя",
		de = "%s hat das Ziel auf dich gewechselt",
		fr = "%s vous prend pour cible",
		["zh-cn"] = "%s 已将目标切换为你",
	},
	alerts_message_threat_target_teammate = {
		en = "%s switched target to %s",
		ru = "%s сменил цель на %s",
		de = "%s hat das Ziel auf %s gewechselt",
		fr = "%s prend %s pour cible",
		["zh-cn"] = "%s 已将目标切换为 %s",
	},
	alerts_message_mission_objective_grouped = {
		en = "%s x%d",
		ru = "%s x%d",
		de = "%s x%d",
		fr = "%s x%d",
		["zh-cn"] = "%s x%d",
	},
	alerts_breed_title_override_chaos_mutator_daemonhost = {
		en = "Daemonhost (mutator)",
		ru = "Демонхост (мутатор)",
		de = "Dämonenhost (Mutator)",
		fr = "Démonhôte (mutateur)",
		["zh-cn"] = "恶魔宿主（突变）",
	},
	alerts_breed_title_override_chaos_hound_mutator = {
		en = "Pox Hound (mutator)",
		ru = "Чумная гончая (мутатор)",
		de = "Pox Hound (Mutator)",
		fr = "Molosse de la peste (mutateur)",
		["zh-cn"] = "瘟疫猎犬（突变）",
	},
	alerts_breed_title_override_renegade_grenadier = {
		en = "Renegade Grenadier",
		ru = "Скаб-Бомбардир",
		de = "Renegaten-Grenadier",
		fr = "Grenadier renégat",
		["zh-cn"] = "血痂火雷兵",
	},
	divisionhud_super_proximity = {
		en = "\238\128\161 PROXIMITY DETECTOR",
		ru = "\238\128\161 ДЕТЕКТОР ПРЕДМЕТОВ",
		de = "\238\128\161 NÄHE-DETEKTOR",
		fr = "\238\128\161 DÉTECTEUR DE PROXIMITÉ",
		["zh-cn"] = "\238\128\161 近距感应",
	},
	proximity_enabled = {
		en = "Enable proximity detector",
		ru = "Включить детектор предметов",
		de = "Nähe-Detektor aktivieren",
		fr = "Activer le détecteur de proximité",
		["zh-cn"] = "启用近距感应",
	},
	proximity_enabled_description = {
		en = "Shows nearby pickups (medkits, ammo, stimms) to the right of the HUD slots.",
		ru = "Показывает ближайшие предметы (аптечки, патроны, стимы) справа от слотов HUD.",
		de = "Zeigt nahe Pickups (Medkits, Munition, Stimms) rechts von den HUD-Plätzen an.",
		fr = "Affiche les objets ramassables proches (kits médicaux, munitions, stimulants) à droite des emplacements du HUD.",
		["zh-cn"] = "在HUD槽右侧显示附近的拾取物（急救箱、弹药、注射器）。",
	},
	proximity_radius = {
		en = "Detection radius (m)",
		ru = "Радиус обнаружения (м)",
		de = "Erkennungsradius (m)",
		fr = "Rayon de détection (m)",
		["zh-cn"] = "检测半径（米）",
	},
	proximity_radius_description = {
		en = "Maximum distance in meters to detect nearby items.",
		ru = "Максимальное расстояние в метрах для обнаружения предметов.",
		de = "Maximale Entfernung in Metern, um nahe Gegenstände zu erkennen.",
		fr = "Distance maximale en mètres pour détecter les objets proches.",
		["zh-cn"] = "检测附近物品的最大距离（米）。",
	},
	proximity_show_medical_station = {
		en = "Show health stations",
		ru = "Показывать мед станции",
		de = "Medicae-Stationen anzeigen",
		fr = "Afficher les stations de soins",
		["zh-cn"] = "显示医疗站",
	},
	proximity_show_medical_station_description = {
		en = "Detect health stations (only those with remaining charges).",
		ru = "Обнаруживать мед станции (только с оставшимися зарядами).",
		de = "Medicae-Stationen erkennen (nur solche mit verbleibenden Ladungen).",
		fr = "Détecter les stations de soins (uniquement celles avec des charges restantes).",
		["zh-cn"] = "检测医疗站（仅剩余充能时显示）。",
	},
	proximity_show_medical = {
		en = "Show medkits",
		ru = "Показывать аптечки",
		de = "Medkits anzeigen",
		fr = "Afficher les kits médicaux",
		["zh-cn"] = "显示急救箱",
	},
	proximity_show_medical_description = {
		en = "Detect pocketable medical crates.",
		ru = "Обнаруживать карманные мед ящики.",
		de = "Tragbare medizinische Kisten erkennen.",
		fr = "Détecter les caisses médicales transportables.",
		["zh-cn"] = "检测可携带医疗箱。",
	},
	proximity_show_medical_deployed = {
		en = "Show deployed medical crates",
		ru = "Показывать развёрнутые мед ящики",
		de = "Aufgestellte medizinische Kisten anzeigen",
		fr = "Afficher les caisses médicales déployées",
		["zh-cn"] = "显示已部署医疗箱",
	},
	proximity_show_medical_deployed_description = {
		en = "Detect deployed medical crates placed by players.",
		ru = "Обнаруживать развёрнутые мед ящики, выставленные игроками.",
		de = "Von Spielern platzierte aufgestellte medizinische Kisten erkennen.",
		fr = "Détecter les caisses médicales déployées placées par les joueurs.",
		["zh-cn"] = "检测玩家放置的已部署医疗箱。",
	},
	proximity_show_stimm = {
		en = "Show stimulants",
		ru = "Показывать стимуляторы",
		de = "Stimms anzeigen",
		fr = "Afficher les stimulants",
		["zh-cn"] = "显示注射器",
	},
	proximity_show_stimm_description = {
		en = "Detect stimulant syringes.",
		ru = "Обнаруживать стимулирующие шприцы.",
		de = "Stimm-Spritzen erkennen.",
		fr = "Détecter les seringues stimulantes.",
		["zh-cn"] = "检测刺激注射器。",
	},
	proximity_show_ammo_small = {
		en = "Show small ammo clips",
		ru = "Показывать малые патроны",
		de = "Kleine Munitionsclips anzeigen",
		fr = "Afficher les petits chargeurs de munitions",
		["zh-cn"] = "显示小弹夹",
	},
	proximity_show_ammo_small_description = {
		en = "Detect small ammo clips.",
		ru = "Обнаруживать малые обоймы с патронами.",
		de = "Kleine Munitionsclips erkennen.",
		fr = "Détecter les petits chargeurs de munitions.",
		["zh-cn"] = "检测小弹夹。",
	},
	proximity_show_ammo_large = {
		en = "Show large ammo clips",
		ru = "Показывать крупные патроны",
		de = "Große Munitionsclips anzeigen",
		fr = "Afficher les grands chargeurs de munitions",
		["zh-cn"] = "显示大弹夹",
	},
	proximity_show_ammo_large_description = {
		en = "Detect large ammo clips.",
		ru = "Обнаруживать крупные обоймы с патронами.",
		de = "Große Munitionsclips erkennen.",
		fr = "Détecter les grands chargeurs de munitions.",
		["zh-cn"] = "检测大弹夹。",
	},
	proximity_show_ammo_crate = {
		en = "Show ammo crates",
		ru = "Показывать ящики патронов",
		de = "Munitionskisten anzeigen",
		fr = "Afficher les caisses de munitions",
		["zh-cn"] = "显示弹药箱",
	},
	proximity_show_ammo_crate_description = {
		en = "Detect pocketable ammo crates and ammo crates placed on the level.",
		ru = "Обнаруживать карманные ящики патронов и ящики с патронами, размещённые на уровне.",
		de = "Tragbare Munitionskisten und im Level platzierte Munitionskisten erkennen.",
		fr = "Détecter les caisses de munitions transportables et les caisses de munitions placées dans le niveau.",
		["zh-cn"] = "检测可携带弹药箱和关卡内放置的弹药箱。",
	},
	proximity_show_ammo_crate_deployed = {
		en = "Show deployed ammo crates",
		ru = "Показывать развёрнутые ящики патронов",
		de = "Aufgestellte Munitionskisten anzeigen",
		fr = "Afficher les caisses de munitions déployées",
		["zh-cn"] = "显示已部署弹药箱",
	},
	proximity_show_ammo_crate_deployed_description = {
		en = "Detect deployed ammo crates placed by players.",
		ru = "Обнаруживать развёрнутые ящики патронов, выставленные игроками.",
		de = "Von Spielern platzierte aufgestellte Munitionskisten erkennen.",
		fr = "Détecter les caisses de munitions déployées placées par les joueurs.",
		["zh-cn"] = "检测玩家放置的已部署弹药箱。",
	},
	proximity_show_grenade = {
		en = "Show grenades",
		ru = "Показывать гранаты",
		de = "Granaten anzeigen",
		fr = "Afficher les grenades",
		["zh-cn"] = "显示手榴弹",
	},
	proximity_show_grenade_description = {
		en = "Detect grenades (standard and expedition).",
		ru = "Обнаруживать гранаты (обычные и экспедиционные).",
		de = "Granaten erkennen (Standard und Expedition).",
		fr = "Détecter les grenades (standard et expédition).",
		["zh-cn"] = "检测手榴弹（普通和远征）。",
	},
	proximity_show_grimoire = {
		en = "Show grimoires",
		ru = "Показывать гримуары",
		de = "Grimoires anzeigen",
		fr = "Afficher les grimoires",
		["zh-cn"] = "显示秘典",
	},
	proximity_show_grimoire_description = {
		en = "Detect grimoires on the map.",
		ru = "Обнаруживать гримуары на карте.",
		de = "Grimoires auf der Karte erkennen.",
		fr = "Détecter les grimoires sur la carte.",
		["zh-cn"] = "检测地图上的秘典。",
	},
	proximity_show_tome = {
		en = "Show scriptures",
		ru = "Показывать писания",
		de = "Schriften anzeigen",
		fr = "Afficher les écritures",
		["zh-cn"] = "显示圣书",
	},
	proximity_show_tome_description = {
		en = "Detect scriptures (tomes) on the map.",
		ru = "Обнаруживать писания на карте.",
		de = "Schriften (Tomes) auf der Karte erkennen.",
		fr = "Détecter les écritures (tomes) sur la carte.",
		["zh-cn"] = "检测地图上的圣书。",
	},
	divisionhud_super_tactical_advisor = {
		en = "\238\128\161 TACTICAL ADVISOR",
		ru = "\238\128\161 ТАКТИЧЕСКИЙ СОВЕТНИК",
		de = "\238\128\161 TAKTISCHER BERATER",
		fr = "\238\128\161 CONSEILLER TACTIQUE",
		["zh-cn"] = "\238\128\161 战术顾问",
	},
	tactical_advisor_enabled = {
		en = "Enable Tactical Advisor",
		ru = "Включить тактического советника",
		de = "Taktischen Berater aktivieren",
		fr = "Activer le conseiller tactique",
		["zh-cn"] = "启用战术顾问",
	},
	tactical_advisor_enabled_description = {
		en = "Enables all Tactical Advisor reminders and highlighted resources.",
		ru = "Включает все напоминания Tactical Advisor и подсветку ресурсов.",
		de = "Aktiviert alle Erinnerungen des Tactical Advisor und hervorgehobene Ressourcen.",
		fr = "Active tous les rappels de Tactical Advisor et les ressources mises en évidence.",
		["zh-cn"] = "启用 Tactical Advisor 的所有提醒和资源高亮。",
	},
	tactical_advisor_ammo_group = {
		en = string.rep("\194\160", 8) .. "Ammo advisor",
		ru = string.rep("\194\160", 8) .. "Советник патронов",
		de = string.rep("\194\160", 8) .. "Munitionsberater",
		fr = string.rep("\194\160", 8) .. "Conseiller de munitions",
		["zh-cn"] = string.rep("\194\160", 8) .. "弹药顾问",
	},
	tactical_advisor_ammo_group_description = {
		en = "Controls reminders for low ammunition and ammo resource highlighting.",
		ru = "Управляет напоминаниями о малом запасе патронов и подсветкой источников патронов.",
		de = "Steuert Erinnerungen bei wenig Munition und das Hervorheben von Munitionsquellen.",
		fr = "Contrôle les rappels de munitions faibles et la mise en évidence des sources de munitions.",
		["zh-cn"] = "控制低弹药提醒和弹药资源高亮。",
	},
	tactical_advisor_health_group = {
		en = string.rep("\194\160", 8) .. "Health advisor",
		ru = string.rep("\194\160", 8) .. "Советник по здоровью",
		de = string.rep("\194\160", 8) .. "Gesundheitsberater",
		fr = string.rep("\194\160", 8) .. "Conseiller de santé",
		["zh-cn"] = string.rep("\194\160", 8) .. "生命值顾问",
	},
	tactical_advisor_health_group_description = {
		en = "Controls reminders for low health and healing resource highlighting.",
		ru = "Управляет напоминаниями о малом здоровье и подсветкой лечебных ресурсов.",
		de = "Steuert Erinnerungen bei wenig Gesundheit und das Hervorheben von Heilressourcen.",
		fr = "Contrôle les rappels de santé faible et la mise en évidence des ressources de soin.",
		["zh-cn"] = "控制低生命值提醒和治疗资源高亮。",
	},
	tactical_advisor_wounds_group = {
		en = string.rep("\194\160", 8) .. "Wounds advisor",
		ru = string.rep("\194\160", 8) .. "Советник по ранам",
		de = string.rep("\194\160", 8) .. "Wundenberater",
		fr = string.rep("\194\160", 8) .. "Conseiller de blessures",
		["zh-cn"] = string.rep("\194\160", 8) .. "伤口顾问",
	},
	tactical_advisor_wounds_group_description = {
		en = "Controls reminders for low remaining wounds and healing resource highlighting.",
		ru = "Управляет напоминаниями о малом количестве оставшихся ран и подсветкой лечебных ресурсов.",
		de = "Steuert Erinnerungen bei wenigen verbleibenden Wunden und das Hervorheben von Heilressourcen.",
		fr = "Contrôle les rappels de blessures restantes faibles et la mise en évidence des ressources de soin.",
		["zh-cn"] = "控制低剩余伤口数提醒和治疗资源高亮。",
	},
	tactical_advisor_corruption_group = {
		en = string.rep("\194\160", 8) .. "Corruption advisor",
		ru = string.rep("\194\160", 8) .. "Советник по заражению",
		de = string.rep("\194\160", 8) .. "Verderbnisberater",
		fr = string.rep("\194\160", 8) .. "Conseiller de corruption",
		["zh-cn"] = string.rep("\194\160", 8) .. "腐化顾问",
	},
	tactical_advisor_corruption_group_description = {
		en = "Controls reminders for high corruption and healing resource highlighting.",
		ru = "Управляет напоминаниями о сильном заражении и подсветкой лечебных ресурсов.",
		de = "Steuert Erinnerungen bei hoher Verderbnis und das Hervorheben von Heilressourcen.",
		fr = "Contrôle les rappels de corruption élevée et la mise en évidence des ressources de soin.",
		["zh-cn"] = "控制高腐化提醒和治疗资源高亮。",
	},
	tactical_advisor_grenade_group = {
		en = string.rep("\194\160", 8) .. "Grenade advisor",
		ru = string.rep("\194\160", 8) .. "Советник гранат",
		de = string.rep("\194\160", 8) .. "Granatenberater",
		fr = string.rep("\194\160", 8) .. "Conseiller de grenades",
		["zh-cn"] = string.rep("\194\160", 8) .. "手雷顾问",
	},
	tactical_advisor_grenade_group_description = {
		en = "Controls reminders for low grenade charges and grenade pickup highlighting.",
		ru = "Управляет напоминаниями о малом запасе гранат и подсветкой ближайших гранат.",
		de = "Steuert Erinnerungen bei wenigen Granatenladungen und das Hervorheben von Granaten-Pickups.",
		fr = "Contrôle les rappels de charges de grenade faibles et la mise en évidence des grenades proches.",
		["zh-cn"] = "控制低手雷充能提醒和手雷拾取物高亮。",
	},
	tactical_advisor_low_ammo_enabled = {
		en = "Low ammo reminder",
		ru = "Напоминание о малом запасе патронов",
		de = "Warnung bei wenig Munition",
		fr = "Rappel de munitions faibles",
		["zh-cn"] = "低弹药提醒",
	},
	tactical_advisor_low_ammo_enabled_description = {
		en = "When ammo is below the threshold, flashes nearby ammo pickups and your carried ammo crate slot.",
		ru = "Если патронов меньше порога, мигает фон ближайших патронов и слота переносимого ящика патронов.",
		de = "Wenn die Munition unter dem Schwellenwert liegt, blinken nahe Munitions-Pickups und dein getragener Munitionskistenplatz.",
		fr = "Quand les munitions passent sous le seuil, fait clignoter les munitions proches et l'emplacement de caisse de munitions portée.",
		["zh-cn"] = "弹药低于阈值时，使附近弹药拾取物和携带的弹药箱槽位闪烁。",
	},
	tactical_advisor_low_ammo_threshold = {
		en = "Low ammo threshold (%%)",
		ru = "Порог малого запаса патронов (%%)",
		de = "Schwelle für wenig Munition (%%)",
		fr = "Seuil de munitions faibles (%%)",
		["zh-cn"] = "低弹药阈值（%%）",
	},
	tactical_advisor_low_ammo_threshold_description = {
		en = "Ammo percentage below which Tactical Advisor starts highlighting ammo resources.",
		ru = "Процент патронов, ниже которого Tactical Advisor начинает подсвечивать источники патронов.",
		de = "Munitionsprozentsatz, unter dem Tactical Advisor Munitionsquellen hervorhebt.",
		fr = "Pourcentage de munitions sous lequel Tactical Advisor met en évidence les sources de munitions.",
		["zh-cn"] = "弹药百分比低于此值时，Tactical Advisor 开始高亮弹药资源。",
	},
	tactical_advisor_low_ammo_alert_enabled = {
		en = "Show low ammo alert",
		ru = "Показывать оповещение о малом запасе патронов",
		de = "Warnung bei wenig Munition anzeigen",
		fr = "Afficher l'alerte de munitions faibles",
		["zh-cn"] = "显示低弹药警报",
	},
	tactical_advisor_low_ammo_alert_enabled_description = {
		en = "When enabled, show an alert strip when ammo reserves first fall below the threshold.",
		ru = "Показывать оповещение в ленте, когда запас патронов впервые падает ниже порога.",
		de = "Zeigt eine Warnungsleiste, wenn der Munitionsvorrat erstmals unter den Schwellenwert fällt.",
		fr = "Affiche une alerte dans la barre lorsque les réserves de munitions passent sous le seuil.",
		["zh-cn"] = "弹药储备首次低于阈值时显示警报栏。",
	},
	tactical_advisor_low_health_enabled = {
		en = "Low health reminder",
		ru = "Напоминание о малом здоровье",
		de = "Warnung bei wenig Gesundheit",
		fr = "Rappel de santé faible",
		["zh-cn"] = "低生命值提醒",
	},
	tactical_advisor_low_health_enabled_description = {
		en = "When health is below the threshold, flashes nearby healing resources and your carried medkit or health stimm slot.",
		ru = "Если здоровье меньше порога, мигает фон ближайших лечебных ресурсов и слота переносимого мед ящика или лечебного стима.",
		de = "Wenn die Gesundheit unter dem Schwellenwert liegt, blinken nahe Heilressourcen und dein getragener Medkit- oder Heil-Stimm-Platz.",
		fr = "Quand la santé passe sous le seuil, fait clignoter les ressources de soin proches et l'emplacement de kit médical ou de stimulant de soin porté.",
		["zh-cn"] = "生命值低于阈值时，使附近治疗资源和携带的医疗箱或治疗注射器槽位闪烁。",
	},
	tactical_advisor_low_health_threshold = {
		en = "Low health threshold (%%)",
		ru = "Порог малого здоровья (%%)",
		de = "Schwelle für wenig Gesundheit (%%)",
		fr = "Seuil de santé faible (%%)",
		["zh-cn"] = "低生命值阈值（%%）",
	},
	tactical_advisor_low_health_threshold_description = {
		en = "Health percentage below which Tactical Advisor starts highlighting healing resources.",
		ru = "Процент здоровья, ниже которого Tactical Advisor начинает подсвечивать лечебные ресурсы.",
		de = "Gesundheitsprozentsatz, unter dem Tactical Advisor Heilressourcen hervorhebt.",
		fr = "Pourcentage de santé sous lequel Tactical Advisor met en évidence les ressources de soin.",
		["zh-cn"] = "生命值百分比低于此值时，Tactical Advisor 开始高亮治疗资源。",
	},
	tactical_advisor_low_health_alert_enabled = {
		en = "Show low health alert",
		ru = "Показывать оповещение о малом здоровье",
		de = "Warnung bei wenig Gesundheit anzeigen",
		fr = "Afficher l'alerte de santé faible",
		["zh-cn"] = "显示低生命值警报",
	},
	tactical_advisor_low_health_alert_enabled_description = {
		en = "When enabled, show an alert strip when health first falls below the threshold.",
		ru = "Показывать оповещение в ленте, когда здоровье впервые падает ниже порога.",
		de = "Zeigt eine Warnungsleiste, wenn die Gesundheit erstmals unter den Schwellenwert fällt.",
		fr = "Affiche une alerte dans la barre lorsque la santé passe sous le seuil.",
		["zh-cn"] = "生命值首次低于阈值时显示警报栏。",
	},
	tactical_advisor_low_wounds_enabled = {
		en = "Low wounds reminder",
		ru = "Напоминание о малом запасе ран",
		de = "Warnung bei wenigen Wunden",
		fr = "Rappel de blessures faibles",
		["zh-cn"] = "低伤口数提醒",
	},
	tactical_advisor_low_wounds_enabled_description = {
		en = "When remaining wounds are below the threshold, flashes nearby healing resources and your carried medkit or health stimm slot.",
		ru = "Если оставшихся ран меньше порога, мигает фон ближайших лечебных ресурсов и слота переносимого мед ящика или лечебного стима.",
		de = "Wenn die verbleibenden Wunden unter dem Schwellenwert liegen, blinken nahe Heilressourcen und dein getragener Medkit- oder Heil-Stimm-Platz.",
		fr = "Quand les blessures restantes passent sous le seuil, fait clignoter les ressources de soin proches et l'emplacement de kit médical ou de stimulant de soin porté.",
		["zh-cn"] = "剩余伤口数低于阈值时，使附近治疗资源和携带的医疗箱或治疗注射器槽位闪烁。",
	},
	tactical_advisor_low_wounds_threshold = {
		en = "Low wounds threshold",
		ru = "Порог малого запаса ран",
		de = "Schwelle für wenige Wunden",
		fr = "Seuil de blessures faibles",
		["zh-cn"] = "低伤口数阈值",
	},
	tactical_advisor_low_wounds_threshold_description = {
		en = "Remaining wounds below which Tactical Advisor starts highlighting healing resources.",
		ru = "Количество оставшихся ран, ниже которого Tactical Advisor начинает подсвечивать лечебные ресурсы.",
		de = "Verbleibende Wunden, unter denen Tactical Advisor Heilressourcen hervorhebt.",
		fr = "Nombre de blessures restantes sous lequel Tactical Advisor met en évidence les ressources de soin.",
		["zh-cn"] = "剩余伤口数低于此值时，Tactical Advisor 开始高亮治疗资源。",
	},
	tactical_advisor_low_wounds_alert_enabled = {
		en = "Show low wounds alert",
		ru = "Показывать оповещение о малом запасе ран",
		de = "Warnung bei wenigen Wunden anzeigen",
		fr = "Afficher l'alerte de blessures faibles",
		["zh-cn"] = "显示低伤口数警报",
	},
	tactical_advisor_low_wounds_alert_enabled_description = {
		en = "When enabled, show an alert strip when remaining wounds first fall below the threshold.",
		ru = "Показывать оповещение в ленте, когда оставшиеся раны впервые падают ниже порога.",
		de = "Zeigt eine Warnungsleiste, wenn die verbleibenden Wunden erstmals unter den Schwellenwert fallen.",
		fr = "Affiche une alerte dans la barre lorsque les blessures restantes passent sous le seuil.",
		["zh-cn"] = "剩余伤口数首次低于阈值时显示警报栏。",
	},
	tactical_advisor_high_corruption_enabled = {
		en = "High corruption reminder",
		ru = "Напоминание о сильном заражении",
		de = "Warnung bei hoher Verderbnis",
		fr = "Rappel de corruption élevée",
		["zh-cn"] = "高腐化提醒",
	},
	tactical_advisor_high_corruption_enabled_description = {
		en = "When corruption is above the threshold, flashes nearby healing resources and your carried medkit or health stimm slot.",
		ru = "Если заражение выше порога, мигает фон ближайших лечебных ресурсов и слота переносимого мед ящика или лечебного стима.",
		de = "Wenn die Verderbnis über dem Schwellenwert liegt, blinken nahe Heilressourcen und dein getragener Medkit- oder Heil-Stimm-Platz.",
		fr = "Quand la corruption dépasse le seuil, fait clignoter les ressources de soin proches et l'emplacement de kit médical ou de stimulant de soin porté.",
		["zh-cn"] = "腐化高于阈值时，使附近治疗资源和携带的医疗箱或治疗注射器槽位闪烁。",
	},
	tactical_advisor_high_corruption_threshold = {
		en = "High corruption threshold (%%)",
		ru = "Порог сильного заражения (%%)",
		de = "Schwelle für hohe Verderbnis (%%)",
		fr = "Seuil de corruption élevée (%%)",
		["zh-cn"] = "高腐化阈值（%%）",
	},
	tactical_advisor_high_corruption_threshold_description = {
		en = "Corruption percentage above which Tactical Advisor starts highlighting healing resources.",
		ru = "Процент заражения, выше которого Tactical Advisor начинает подсвечивать лечебные ресурсы.",
		de = "Verderbnisprozentsatz, über dem Tactical Advisor Heilressourcen hervorhebt.",
		fr = "Pourcentage de corruption au-dessus duquel Tactical Advisor met en évidence les ressources de soin.",
		["zh-cn"] = "腐化百分比高于此值时，Tactical Advisor 开始高亮治疗资源。",
	},
	tactical_advisor_high_corruption_alert_enabled = {
		en = "Show high corruption alert",
		ru = "Показывать оповещение о сильном заражении",
		de = "Warnung bei hoher Verderbnis anzeigen",
		fr = "Afficher l'alerte de corruption élevée",
		["zh-cn"] = "显示高腐化警报",
	},
	tactical_advisor_high_corruption_alert_enabled_description = {
		en = "When enabled, show an alert strip when corruption first rises above the threshold.",
		ru = "Показывать оповещение в ленте, когда заражение впервые поднимается выше порога.",
		de = "Zeigt eine Warnungsleiste, wenn die Verderbnis erstmals über den Schwellenwert steigt.",
		fr = "Affiche une alerte dans la barre lorsque la corruption dépasse le seuil.",
		["zh-cn"] = "腐化首次高于阈值时显示警报栏。",
	},
	tactical_advisor_low_grenade_enabled = {
		en = "Low grenade reminder",
		ru = "Напоминание о малом запасе гранат",
		de = "Warnung bei wenig Granaten",
		fr = "Rappel de grenades faibles",
		["zh-cn"] = "低手雷提醒",
	},
	tactical_advisor_low_grenade_enabled_description = {
		en = "When grenade charges are below the threshold, flashes nearby grenade pickups.",
		ru = "Если зарядов гранат меньше порога, мигает фон ближайших гранат.",
		de = "Wenn Granatenladungen unter dem Schwellenwert liegen, blinken nahe Granaten-Pickups.",
		fr = "Quand les charges de grenade passent sous le seuil, fait clignoter les grenades proches.",
		["zh-cn"] = "手雷充能低于阈值时，使附近手雷拾取物闪烁。",
	},
	tactical_advisor_low_grenade_threshold = {
		en = "Low grenade threshold (%%)",
		ru = "Порог малого запаса гранат (%%)",
		de = "Schwelle für wenig Granaten (%%)",
		fr = "Seuil de grenades faibles (%%)",
		["zh-cn"] = "低手雷阈值（%%）",
	},
	tactical_advisor_low_grenade_threshold_description = {
		en = "Grenade charge percentage below which Tactical Advisor starts highlighting nearby grenades.",
		ru = "Процент зарядов гранат, ниже которого Tactical Advisor начинает подсвечивать ближайшие гранаты.",
		de = "Granatenladungsprozentsatz, unter dem Tactical Advisor nahe Granaten hervorhebt.",
		fr = "Pourcentage de charges de grenade sous lequel Tactical Advisor met en évidence les grenades proches.",
		["zh-cn"] = "手雷充能百分比低于此值时，Tactical Advisor 开始高亮附近手雷。",
	},
	tactical_advisor_low_grenade_alert_enabled = {
		en = "Show low grenade alert",
		ru = "Показывать оповещение о малом запасе гранат",
		de = "Warnung bei wenigen Granaten anzeigen",
		fr = "Afficher l'alerte de grenades faibles",
		["zh-cn"] = "显示低手雷警报",
	},
	tactical_advisor_low_grenade_alert_enabled_description = {
		en = "When enabled, show an alert strip when grenade supply first falls below the threshold.",
		ru = "Показывать оповещение в ленте, когда запас гранат впервые падает ниже порога.",
		de = "Zeigt eine Warnungsleiste, wenn der Granatenvorrat erstmals unter den Schwellenwert fällt.",
		fr = "Affiche une alerte dans la barre lorsque les grenades passent sous le seuil.",
		["zh-cn"] = "手雷储备首次低于阈值时显示警报栏。",
	},
	tactical_advisor_blink_intensity = {
		en = "Advisor blink intensity (%%)",
		ru = "Интенсивность мигания советника (%%)",
		de = "Blinkintensität des Beraters (%%)",
		fr = "Intensité du clignotement du conseiller (%%)",
		["zh-cn"] = "顾问闪烁强度（%%）",
	},
	tactical_advisor_blink_intensity_description = {
		en = "Controls how strongly Tactical Advisor flashes highlighted resources and carried slots.",
		ru = "Управляет силой мигания ресурсов и переносимых слотов, подсвеченных Tactical Advisor.",
		de = "Steuert, wie stark Tactical Advisor hervorgehobene Ressourcen und getragene Plätze blinken lässt.",
		fr = "Contrôle l'intensité du clignotement des ressources et emplacements portés mis en évidence par Tactical Advisor.",
		["zh-cn"] = "控制 Tactical Advisor 高亮资源和携带槽位的闪烁强度。",
	},
	tactical_advisor_alert_strip = {
		en = "Tactical advisor",
		ru = "Тактический советник",
		de = "Taktischer Berater",
		fr = "Conseiller tactique",
		["zh-cn"] = "战术顾问",
	},
	tactical_advisor_alert_low_ammo_find = {
		en = "Ammo reserves are running low, find supplies",
		ru = "Запас патронов на исходе, найди боеприпасы",
		de = "Munitionsreserven gehen zur Neige, Vorräte suchen",
		fr = "Les réserves de munitions diminuent, trouvez du ravitaillement",
		["zh-cn"] = "弹药储备不足，寻找补给",
	},
	tactical_advisor_alert_low_ammo_use_ammo_crate = {
		en = "Ammo reserves are running low, deploy your ammo crate",
		ru = "Запас патронов на исходе, поставь ящик патронов",
		de = "Munitionsreserven gehen zur Neige, Munitionskiste aufstellen",
		fr = "Les réserves de munitions diminuent, déployez votre caisse de munitions",
		["zh-cn"] = "弹药储备不足，部署弹药箱",
	},
	tactical_advisor_alert_low_health_find = {
		en = "Health is critically low, find healing",
		ru = "Здоровье на критическом уровне, найди лечение",
		de = "Gesundheit ist kritisch niedrig, Heilung suchen",
		fr = "La santé est critique, trouvez des soins",
		["zh-cn"] = "生命值已到危急水平，寻找治疗",
	},
	tactical_advisor_alert_low_health_use_health_stimm = {
		en = "Health is critically low, use your stimm",
		ru = "Здоровье на критическом уровне, используй стимм",
		de = "Gesundheit ist kritisch niedrig, Stimm nutzen",
		fr = "La santé est critique, utilisez votre stim",
		["zh-cn"] = "生命值已到危急水平，使用兴奋剂",
	},
	tactical_advisor_alert_low_health_use_medical_crate = {
		en = "Health is critically low, deploy your med crate",
		ru = "Здоровье на критическом уровне, поставь мед. ящик",
		de = "Gesundheit ist kritisch niedrig, Medizinkiste aufstellen",
		fr = "La santé est critique, déployez votre caisse médicale",
		["zh-cn"] = "生命值已到危急水平，部署医疗箱",
	},
	tactical_advisor_alert_low_health_near_health_station = {
		en = "Health is critically low, use the nearby health station",
		ru = "Здоровье на критическом уровне, используй медстанцию рядом",
		de = "Gesundheit ist kritisch niedrig, nahe Sanitätsstation nutzen",
		fr = "La santé est critique, utilisez la station médicale proche",
		["zh-cn"] = "生命值已到危急水平，使用附近医疗站",
	},
	tactical_advisor_alert_low_health_near_medical_crate = {
		en = "Health is critically low, use the nearby med crate",
		ru = "Здоровье на критическом уровне, используй мед. ящик рядом",
		de = "Gesundheit ist kritisch niedrig, nahe Medizinkiste nutzen",
		fr = "La santé est critique, utilisez la caisse médicale proche",
		["zh-cn"] = "生命值已到危急水平，使用附近医疗箱",
	},
	tactical_advisor_alert_low_health_near_medical_pickup = {
		en = "Health is critically low, pick up the nearby med crate",
		ru = "Здоровье на критическом уровне, подбери мед. ящик рядом",
		de = "Gesundheit ist kritisch niedrig, nahe Medizinkiste aufnehmen",
		fr = "La santé est critique, ramassez la caisse médicale proche",
		["zh-cn"] = "生命值已到危急水平，拾取附近医疗箱",
	},
	tactical_advisor_alert_low_health_near_health_stimm = {
		en = "Health is critically low, pick up the nearby stimm",
		ru = "Здоровье на критическом уровне, подбери стимм рядом",
		de = "Gesundheit ist kritisch niedrig, nahen Stimm aufnehmen",
		fr = "La santé est critique, ramassez le stim proche",
		["zh-cn"] = "生命值已到危急水平，拾取附近兴奋剂",
	},
	tactical_advisor_alert_low_wounds_find = {
		en = "Remaining wounds are low, find a health station",
		ru = "Осталось мало ран, найди медстанцию",
		de = "Nur wenige Wunden verbleiben, Sanitätsstation suchen",
		fr = "Il reste peu de blessures, trouvez une station médicale",
		["zh-cn"] = "剩余伤口数不足，寻找医疗站",
	},
	tactical_advisor_alert_low_wounds_use_health_stimm = {
		en = "Remaining wounds are low, use your stimm",
		ru = "Осталось мало ран, используй стимм",
		de = "Nur wenige Wunden verbleiben, Stimm nutzen",
		fr = "Il reste peu de blessures, utilisez votre stim",
		["zh-cn"] = "剩余伤口数不足，使用兴奋剂",
	},
	tactical_advisor_alert_low_wounds_use_medical_crate = {
		en = "Remaining wounds are low, deploy your med crate",
		ru = "Осталось мало ран, поставь мед. ящик",
		de = "Nur wenige Wunden verbleiben, Medizinkiste aufstellen",
		fr = "Il reste peu de blessures, déployez votre caisse médicale",
		["zh-cn"] = "剩余伤口数不足，部署医疗箱",
	},
	tactical_advisor_alert_low_wounds_near_health_station = {
		en = "Remaining wounds are low, use the nearby health station",
		ru = "Осталось мало ран, используй медстанцию рядом",
		de = "Nur wenige Wunden verbleiben, nahe Sanitätsstation nutzen",
		fr = "Il reste peu de blessures, utilisez la station médicale proche",
		["zh-cn"] = "剩余伤口数不足，使用附近医疗站",
	},
	tactical_advisor_alert_low_wounds_near_medical_crate = {
		en = "Remaining wounds are low, use the nearby med crate",
		ru = "Осталось мало ран, используй мед. ящик рядом",
		de = "Nur wenige Wunden verbleiben, nahe Medizinkiste nutzen",
		fr = "Il reste peu de blessures, utilisez la caisse médicale proche",
		["zh-cn"] = "剩余伤口数不足，使用附近医疗箱",
	},
	tactical_advisor_alert_low_wounds_near_medical_pickup = {
		en = "Remaining wounds are low, pick up the nearby med crate",
		ru = "Осталось мало ран, подбери мед. ящик рядом",
		de = "Nur wenige Wunden verbleiben, nahe Medizinkiste aufnehmen",
		fr = "Il reste peu de blessures, ramassez la caisse médicale proche",
		["zh-cn"] = "剩余伤口数不足，拾取附近医疗箱",
	},
	tactical_advisor_alert_low_wounds_near_health_stimm = {
		en = "Remaining wounds are low, pick up the nearby stimm",
		ru = "Осталось мало ран, подбери стимм рядом",
		de = "Nur wenige Wunden verbleiben, nahen Stimm aufnehmen",
		fr = "Il reste peu de blessures, ramassez le stim proche",
		["zh-cn"] = "剩余伤口数不足，拾取附近兴奋剂",
	},
	tactical_advisor_alert_high_corruption_find = {
		en = "Corruption is spreading, find cleansing",
		ru = "Заражение распространяется, найди очищение",
		de = "Verderbnis breitet sich aus, Reinigung suchen",
		fr = "La corruption se propage, trouvez de quoi la purifier",
		["zh-cn"] = "腐化正在蔓延，寻找净化手段",
	},
	tactical_advisor_alert_high_corruption_use_health_stimm = {
		en = "Corruption is spreading, use your stimm",
		ru = "Заражение распространяется, используй стимм",
		de = "Verderbnis breitet sich aus, Stimm nutzen",
		fr = "La corruption se propage, utilisez votre stim",
		["zh-cn"] = "腐化正在蔓延，使用兴奋剂",
	},
	tactical_advisor_alert_high_corruption_use_medical_crate = {
		en = "Corruption is spreading, deploy your med crate",
		ru = "Заражение распространяется, поставь мед. ящик",
		de = "Verderbnis breitet sich aus, Medizinkiste aufstellen",
		fr = "La corruption se propage, déployez votre caisse médicale",
		["zh-cn"] = "腐化正在蔓延，部署医疗箱",
	},
	tactical_advisor_alert_high_corruption_near_health_station = {
		en = "Corruption is spreading, use the nearby health station",
		ru = "Заражение распространяется, используй медстанцию рядом",
		de = "Verderbnis breitet sich aus, nahe Sanitätsstation nutzen",
		fr = "La corruption se propage, utilisez la station médicale proche",
		["zh-cn"] = "腐化正在蔓延，使用附近医疗站",
	},
	tactical_advisor_alert_high_corruption_near_medical_crate = {
		en = "Corruption is spreading, use the nearby med crate",
		ru = "Заражение распространяется, используй мед. ящик рядом",
		de = "Verderbnis breitet sich aus, nahe Medizinkiste nutzen",
		fr = "La corruption se propage, utilisez la caisse médicale proche",
		["zh-cn"] = "腐化正在蔓延，使用附近医疗箱",
	},
	tactical_advisor_alert_high_corruption_near_medical_pickup = {
		en = "Corruption is spreading, pick up the nearby med crate",
		ru = "Заражение распространяется, подбери мед. ящик рядом",
		de = "Verderbnis breitet sich aus, nahe Medizinkiste aufnehmen",
		fr = "La corruption se propage, ramassez la caisse médicale proche",
		["zh-cn"] = "腐化正在蔓延，拾取附近医疗箱",
	},
	tactical_advisor_alert_high_corruption_near_health_stimm = {
		en = "Corruption is spreading, pick up the nearby stimm",
		ru = "Заражение распространяется, подбери стимм рядом",
		de = "Verderbnis breitet sich aus, nahen Stimm aufnehmen",
		fr = "La corruption se propage, ramassez le stim proche",
		["zh-cn"] = "腐化正在蔓延，拾取附近兴奋剂",
	},
	tactical_advisor_alert_low_grenade_find = {
		en = "Grenade supply is running low, resupply",
		ru = "Запас гранат на исходе, пополни запас",
		de = "Granatenvorrat geht zur Neige, nachrüsten",
		fr = "Les réserves de grenades diminuent, ravitaillez-vous",
		["zh-cn"] = "手雷储备不足，补充库存",
	},
	divisionhud_integrations = {
		en = "\238\128\172 INTEGRATIONS",
		ru = "\238\128\172 ИНТЕГРАЦИИ",
		de = "\238\128\172 INTEGRATIONEN",
		fr = "\238\128\172 INTÉGRATIONS",
		["zh-cn"] = "\238\128\172 模组兼容",
	},
	integration_custom_hud = {
		en = "Custom HUD",
		ru = "Custom HUD",
		de = "Custom HUD",
		fr = "Custom HUD",
		["zh-cn"] = "Custom HUD 兼容",
	},
	integration_custom_hud_description = {
		en = "When enabled and Custom HUD has saved layout for this HUD (including root), Division HUD applies that position every frame and adds Dynamic HUD motion on top. Offset X/Y sliders are ignored for root. If only inner nodes are saved, root is left unchanged. Until anything is saved in Custom HUD, the X/Y sliders still move the block.",
		ru = "Если включено и в Custom HUD сохранена раскладка этого HUD (в т.ч. root), Division HUD каждый кадр ставит эту позицию и при необходимости добавляет смещение Dynamic HUD. Слайдеры X/Y для root не используются. Если в Custom HUD сохранены только внутренние узлы, root не трогаем. Пока в Custom HUD нет сохранений — блок двигают слайдеры X/Y.",
		de = "Wenn aktiviert und Custom HUD ein Layout für dieses HUD gespeichert hat (einschließlich root), wendet Division HUD diese Position in jedem Frame an und fügt die Dynamic-HUD-Bewegung darüber hinzu. Die X/Y-Versatzregler werden für root ignoriert. Wenn nur innere Knoten gespeichert sind, bleibt root unverändert. Solange in Custom HUD nichts gespeichert ist, bewegen die X/Y-Regler den Block weiterhin.",
		fr = "Lorsque cette option est activée et que Custom HUD a enregistré une disposition pour ce HUD (y compris root), Division HUD applique cette position à chaque image et ajoute le mouvement Dynamic HUD par-dessus. Les curseurs de décalage X/Y sont ignorés pour root. Si seuls des nœuds internes sont enregistrés, root reste inchangé. Tant que rien n'est enregistré dans Custom HUD, les curseurs X/Y déplacent toujours le bloc.",
		["zh-cn"] = "启用后，若 Custom HUD 已保存布局，Division HUD 将使用其位置并叠加动态效果，忽略 X/Y 偏移。未保存布局时仍可使用滑块调整。",
	},
	integration_stimm_countdown = {
		en = "StimmCountdown",
		ru = "StimmCountdown",
		de = "StimmCountdown",
		fr = "StimmCountdown",
		["zh-cn"] = "StimmCountdown 兼容",
	},
	integration_stimm_countdown_description = {
		en = "When enabled and the StimmCountdown mod is loaded and enabled, the pocket stimm slot in the Division HUD strip shows its countdown (active / cooldown) using that mod’s display options. When off, the slot uses the usual 01/00 counter only.",
		ru = "Если включено и мод StimmCountdown загружен и включён, в слоте карманного шприца в полоске Division HUD показывается отсчёт (действие / перезарядка) с учётом настроек того мода. Если выключено — только обычные 01/00.",
		de = "Wenn aktiviert und der Mod StimmCountdown geladen und aktiviert ist, zeigt der Stimm-Taschenplatz in der Division-HUD-Leiste seinen Countdown (aktiv / Abklingzeit) mit den Anzeigeoptionen dieses Mods. Wenn deaktiviert, verwendet der Platz nur den üblichen 01/00-Zähler.",
		fr = "Lorsque cette option est activée et que le mod StimmCountdown est chargé et activé, l'emplacement de stimulant de poche dans la barre Division HUD affiche son compte à rebours (actif / recharge) avec les options d'affichage de ce mod. Lorsqu'elle est désactivée, l'emplacement utilise uniquement le compteur habituel 01/00.",
		["zh-cn"] = "启用后，若已加载 StimmCountdown，注射器槽会显示持续/冷却倒计时；关闭则只显示 01/00。",
	},
	integration_recolor_stimms = {
		en = "RecolorStimms",
		ru = "RecolorStimms",
		de = "RecolorStimms",
		fr = "RecolorStimms",
		["zh-cn"] = "RecolorStimms 兼容",
	},
	integration_recolor_stimms_description = {
		en = "When enabled and the RecolorStimms mod is loaded and enabled, pocket stimm icon colors are taken from that mod (get_stimm_argb_255). When off or the mod is unavailable, built-in syringe colors are used.",
		ru = "Если включено и мод RecolorStimms загружен и включён, цвета иконки карманного шприца берутся из него (get_stimm_argb_255). Иначе используются встроенные цвета шприцев.",
		de = "Wenn aktiviert und der Mod RecolorStimms geladen und aktiviert ist, werden die Farben des Stimm-Symbols im Taschenplatz von diesem Mod übernommen (get_stimm_argb_255). Wenn deaktiviert oder der Mod nicht verfügbar ist, werden die integrierten Spritzenfarben verwendet.",
		fr = "Lorsque cette option est activée et que le mod RecolorStimms est chargé et activé, les couleurs de l'icône du stimulant de poche proviennent de ce mod (get_stimm_argb_255). Lorsque l'option est désactivée ou que le mod est indisponible, les couleurs de seringues intégrées sont utilisées.",
		["zh-cn"] = "启用后，注射器图标颜色将从 RecolorStimms 读取；未启用时使用内置颜色。",
	},
	divisionhud_super_enemy_target = {
		en = "\238\128\178 ENEMY TARGET",
		ru = "\238\128\178 ВРАЖЕСКАЯ ЦЕЛЬ",
		de = "\238\128\178 GEGNERZIEL",
		fr = "\238\128\178 CIBLE ENNEMIE",
		["zh-cn"] = "\238\128\178 敌方目标",
	},
	enemy_target_enabled = {
		en = "Enable enemy target",
		ru = "Включить вражескую цель",
		de = "Gegnerziel aktivieren",
		fr = "Activer la cible ennemie",
		["zh-cn"] = "启用敌方目标",
	},
	enemy_target_enabled_description = {
		en = "Shows or hides the enemy target block.",
		ru = "Показывает или скрывает блок вражеской цели.",
		de = "Zeigt oder verbirgt den Gegnerziel-Block.",
		fr = "Affiche ou masque le bloc de cible ennemie.",
		["zh-cn"] = "显示或隐藏敌方目标模块。",
	},
	enemy_target_sources = {
		en = string.rep("\194\160", 8) .. "Information sources",
		ru = string.rep("\194\160", 8) .. "Источники информации",
		de = string.rep("\194\160", 8) .. "Informationsquellen",
		fr = string.rep("\194\160", 8) .. "Sources d'information",
		["zh-cn"] = string.rep("\194\160", 8) .. "信息来源",
	},
	enemy_target_sources_description = {
		en = "Choose which events are allowed to show the enemy target block.",
		ru = "Выберите, какие события могут показывать блок цели.",
		de = "Wähle, welche Ereignisse den Gegnerziel-Block anzeigen dürfen.",
		fr = "Choisissez quels événements sont autorisés à afficher le bloc de cible ennemie.",
		["zh-cn"] = "选择哪些事件可以显示敌方目标模块。",
	},
	enemy_target_show_on_hover = {
		en = "Hover enemy",
		ru = "Наведение на врага",
		de = "Gegner anvisieren",
		fr = "Viser un ennemi",
		["zh-cn"] = "瞄准敌人",
	},
	enemy_target_show_on_hover_description = {
		en = "Show the block when the current target is under the crosshair.",
		ru = "Показывать блок, когда текущая цель находится под прицелом.",
		de = "Block anzeigen, wenn sich das aktuelle Ziel unter dem Fadenkreuz befindet.",
		fr = "Afficher le bloc lorsque la cible actuelle est sous le réticule.",
		["zh-cn"] = "当当前目标处于准星下时显示模块。",
	},
	enemy_target_show_on_hit = {
		en = "Hit enemy",
		ru = "Попадание по врагу",
		de = "Gegner treffen",
		fr = "Toucher un ennemi",
		["zh-cn"] = "命中敌人",
	},
	enemy_target_show_on_hit_description = {
		en = "Show the block when you damage an enemy.",
		ru = "Показывать блок, когда вы наносите урон врагу.",
		de = "Block anzeigen, wenn du einem Gegner Schaden zufügst.",
		fr = "Afficher le bloc lorsque vous infligez des dégâts à un ennemi.",
		["zh-cn"] = "当你对敌人造成伤害时显示模块。",
	},
	enemy_target_hold_time = {
		en = "Display time (seconds)",
		ru = "Время показа (сек.)",
		de = "Anzeigedauer (Sekunden)",
		fr = "Durée d'affichage (secondes)",
		["zh-cn"] = "显示时间（秒）",
	},
	enemy_target_hold_time_description = {
		en = "How many seconds the block remains visible after a hit trigger (does not affect hover).",
		ru = "Сколько секунд блок остается видимым после триггера попадания (не влияет на наведение).",
		de = "Wie viele Sekunden der Block nach einem Treffer-Auslöser sichtbar bleibt (wirkt sich nicht auf Anvisieren aus).",
		fr = "Nombre de secondes pendant lesquelles le bloc reste visible après un déclenchement par touche (n'affecte pas la visée).",
		["zh-cn"] = "命中触发后模块保持显示的秒数（不影响瞄准触发）。",
	},
	enemy_target_show_debuffs = {
		en = "Show debuffs",
		ru = "Показывать дебафы",
		de = "Debuffs anzeigen",
		fr = "Afficher les malus",
		["zh-cn"] = "显示减益",
	},
	enemy_target_show_debuffs_description = {
		en = "Show the list of active debuffs on the enemy target inside the block.",
		ru = "Показывать список активных дебафов на вражеской цели внутри блока.",
		de = "Liste aktiver Debuffs auf dem Gegnerziel im Block anzeigen.",
		fr = "Afficher la liste des malus actifs sur la cible ennemie dans le bloc.",
		["zh-cn"] = "在模块中显示敌方目标身上的有效减益列表。",
	},
	enemy_target_groups = {
		en = string.rep("\194\160", 8) .. "Enemy groups",
		ru = string.rep("\194\160", 8) .. "Группы врагов",
		de = string.rep("\194\160", 8) .. "Gegnergruppen",
		fr = string.rep("\194\160", 8) .. "Groupes d'ennemis",
		["zh-cn"] = string.rep("\194\160", 8) .. "敌人分组",
	},
	enemy_target_groups_description = {
		en = "Choose which enemy groups are allowed to appear in the block.",
		ru = "Выберите, какие группы врагов можно показывать в блоке.",
		de = "Wähle, welche Gegnergruppen im Block erscheinen dürfen.",
		fr = "Choisissez quels groupes d'ennemis sont autorisés à apparaître dans le bloc.",
		["zh-cn"] = "选择允许在模块中显示的敌人分组。",
	},
	enemy_target_show_boss = {
		en = "Boss",
		ru = "Боссы",
		de = "Boss",
		fr = "Boss",
		["zh-cn"] = "Boss",
	},
	enemy_target_show_boss_description = {
		en = "Allow bosses in the enemy target block.",
		ru = "Разрешить показ боссов в блоке цели.",
		de = "Bosse im Gegnerziel-Block erlauben.",
		fr = "Autoriser les boss dans le bloc de cible ennemie.",
		["zh-cn"] = "允许在敌方目标模块中显示 Boss。",
	},
	enemy_target_show_elite = {
		en = "Elite",
		ru = "Элита",
		de = "Elite",
		fr = "Élite",
		["zh-cn"] = "精英",
	},
	enemy_target_show_elite_description = {
		en = "Allow elites in the enemy target block.",
		ru = "Разрешить показ элиты в блоке цели.",
		de = "Eliten im Gegnerziel-Block erlauben.",
		fr = "Autoriser les élites dans le bloc de cible ennemie.",
		["zh-cn"] = "允许在敌方目标模块中显示精英。",
	},
	enemy_target_show_special = {
		en = "Special",
		ru = "Специалисты",
		de = "Spezialist",
		fr = "Spécialiste",
		["zh-cn"] = "专家",
	},
	enemy_target_show_special_description = {
		en = "Allow specials in the enemy target block.",
		ru = "Разрешить показ специалистов в блоке цели.",
		de = "Spezialisten im Gegnerziel-Block erlauben.",
		fr = "Autoriser les spécialistes dans le bloc de cible ennemie.",
		["zh-cn"] = "允许在敌方目标模块中显示专家。",
	},
	divisionhud_super_system = {
		en = "\238\128\169 SYSTEM SETTINGS",
		ru = "\238\128\169 СИСТЕМНЫЕ НАСТРОЙКИ",
		de = "\238\128\169 SYSTEMEINSTELLUNGEN",
		fr = "\238\128\169 PARAMÈTRES SYSTÈME",
		["zh-cn"] = "\238\128\169 系统设置",
	},
	debug = {
		en = "Debug",
		ru = "Debug",
		de = "Debug",
		fr = "Debug",
		["zh-cn"] = "调试",
	},
	debug_description = {
		en = "Enables the internal DivisionHUD debug hotkeys on the numpad. Numpad 1 shows the alert \"Enemies nearby\". Numpad 2 simulates the invulnerability toughness buff and the 125 + 170 toughness label.",
		ru = "Включает внутренние debug-горячие клавиши DivisionHUD на numpad. Numpad 1 показывает алерт «Враги рядом». Numpad 2 имитирует баф неуязвимости на стойкость и подпись стойкости 125 + 170.",
		de = "Aktiviert die internen Debug-Hotkeys von DivisionHUD auf dem Nummernblock. Nummernblock 1 zeigt die Warnung \"Gegner in der Nähe\". Nummernblock 2 simuliert den Unverwundbarkeits-Buff auf Widerstand und die Widerstandsbeschriftung 125 + 170.",
		fr = "Active les raccourcis de debug internes de DivisionHUD sur le pavé numérique. Pavé numérique 1 affiche l'alerte \"Ennemis proches\". Pavé numérique 2 simule le bonus de résistance d'invulnérabilité et le libellé de résistance 125 + 170.",
		["zh-cn"] = "启用 DivisionHUD 的数字小键盘调试热键。小键盘 1 显示“敌人接近”警报，小键盘 2 模拟无敌韧性增益和 125 + 170 韧性文本。",
	},
	divisionhud_reset_all_settings = {
		en = "Reset settings",
		ru = "Сбросить настройки",
		de = "Einstellungen zurücksetzen",
		fr = "Réinitialiser les paramètres",
		["zh-cn"] = "重置设置",
	},
	divisionhud_reset_all_settings_description = {
		en = "Pick the confirm entry and apply. All Division HUD options return to defaults.",
		ru = "Выберите подтверждение и примените. Все параметры Division HUD вернутся к значениям по умолчанию.",
		de = "Bestätigungseintrag auswählen und anwenden. Alle Division-HUD-Optionen werden auf Standardwerte zurückgesetzt.",
		fr = "Sélectionnez l'entrée de confirmation et appliquez. Toutes les options de Division HUD reviennent aux valeurs par défaut.",
		["zh-cn"] = "选择确认并应用，所有 Division HUD 设置恢复默认。",
	},
	divisionhud_reset_confirm = {
		en = "Yes, reset",
		ru = "Да, сбросить",
		de = "Ja, zurücksetzen",
		fr = "Oui, réinitialiser",
		["zh-cn"] = "确认重置",
	},
	divisionhud_reset_done = {
		en = "Division HUD: settings restored to defaults.",
		ru = "Division HUD: настройки сброшены к значениям по умолчанию.",
		de = "Division HUD: Einstellungen auf Standardwerte zurückgesetzt.",
		fr = "Division HUD : paramètres restaurés aux valeurs par défaut.",
		["zh-cn"] = "全境封锁 HUD：已恢复默认设置。",
	},
	enemy_target_type_monster = {
		en = "Miniboss",
		ru = "Минибосс",
		de = "Miniboss",
		fr = "Mini-boss",
		["zh-cn"] = "小BOSS",
	},
	enemy_target_type_captain = {
		en = "Boss",
		ru = "Босс",
		de = "Boss",
		fr = "Boss",
		["zh-cn"] = "BOSS",
	},
	enemy_target_type_disabler = {
		en = "Disabler",
		ru = "Контроль",
		de = "Disabler",
		fr = "Neutraliseur",
		["zh-cn"] = "控制专家",
	},
	enemy_target_type_witch = {
		en = "Daemonhost",
		ru = "Демонхост",
		de = "Dämonenhost",
		fr = "Démonhôte",
		["zh-cn"] = "恶魔宿主",
	},
	enemy_target_type_sniper = {
		en = "Sniper",
		ru = "Снайпер",
		de = "Scharfschütze",
		fr = "Sniper",
		["zh-cn"] = "狙击手",
	},
	enemy_target_type_far = {
		en = "Ranged elite",
		ru = "Дальний элитник",
		de = "Fernkampf-Elite",
		fr = "Élite à distance",
		["zh-cn"] = "远程精英",
	},
	enemy_target_type_elite = {
		en = "Melee elite",
		ru = "Ближний элитник",
		de = "Nahkampf-Elite",
		fr = "Élite de mêlée",
		["zh-cn"] = "近战精英",
	},
	enemy_target_type_special = {
		en = "Special",
		ru = "Специалист",
		de = "Spezialist",
		fr = "Spécialiste",
		["zh-cn"] = "输出专家",
	},
	enemy_target_type_horde = {
		en = "Horde",
		ru = "Орда",
		de = "Horde",
		fr = "Horde",
		["zh-cn"] = "尸潮怪",
	},
	enemy_target_type_enemy = {
		en = "Enemy",
		ru = "Враг",
		de = "Gegner",
		fr = "Ennemi",
		["zh-cn"] = "敌人",
	},
	enemy_target_debuff_label_bleed = {
		en = "Bleed",
		ru = "Кровотечение",
		de = "Blutung",
		fr = "Saignement",
		["zh-cn"] = "流血",
	},
	enemy_target_debuff_label_fire = {
		en = "Fire",
		ru = "Поджог",
		de = "Feuer",
		fr = "Feu",
		["zh-cn"] = "燃烧",
	},
	enemy_target_debuff_label_warp = {
		en = "Warp",
		ru = "Варп",
		de = "Warp",
		fr = "Warp",
		["zh-cn"] = "灵能",
	},
	enemy_target_debuff_label_shock = {
		en = "Electroshock",
		ru = "Электрошок",
		de = "Elektroschock",
		fr = "Électrochoc",
		["zh-cn"] = "电击",
	},
	enemy_target_debuff_label_toxin = {
		en = "Poison",
		ru = "Отравление",
		de = "Gift",
		fr = "Poison",
		["zh-cn"] = "中毒",
	},
	enemy_target_debuff_label_rending = {
		en = "Armor Break",
		ru = "Пробитие брони",
		de = "Rüstungsbruch",
		fr = "Brise-armure",
		["zh-cn"] = "破甲",
	},
	enemy_target_debuff_label_stagger = {
		en = "Stun",
		ru = "Оглушение",
		de = "Betäubung",
		fr = "Étourdissement",
		["zh-cn"] = "击晕",
	},
	enemy_target_debuff_label_blind = {
		en = "Smoke Effect",
		ru = "Эффект дыма",
		de = "Raucheffekt",
		fr = "Effet de fumée",
		["zh-cn"] = "致盲",
	},
	enemy_target_debuff_label_damage_taken = {
		en = "More Damage",
		ru = "Больше урона",
		de = "Mehr Schaden",
		fr = "Plus de dégâts",
		["zh-cn"] = "易伤",
	},
	enemy_target_debuff_label_melee_damage_taken = {
		en = "More Melee Damage",
		ru = "Больше урона вблизи",
		de = "Mehr Nahkampfschaden",
		fr = "Plus de dégâts de mêlée",
		["zh-cn"] = "近战易伤",
	},
	enemy_target_debuff_label_stagger_damage = {
		en = "More Stunned Damage",
		ru = "Больше урона оглушённому",
		de = "Mehr Schaden gegen Betäubte",
		fr = "Plus de dégâts aux cibles étourdies",
		["zh-cn"] = "击晕易伤",
	},
	enemy_target_debuff_label_impact_taken = {
		en = "Easier to Stun",
		ru = "Легче оглушить",
		de = "Leichter zu betäuben",
		fr = "Plus facile à étourdir",
		["zh-cn"] = "更易硬直",
	},
	enemy_target_debuff_label_count_as_stagger = {
		en = "Stun Effect",
		ru = "Эффект ошеломления",
		de = "Betäubungseffekt",
		fr = "Effet d'étourdissement",
		["zh-cn"] = "硬直目标",
	},
	enemy_target_debuff_label_damage_dealt_down = {
		en = "Weakening Effect",
		ru = "Эффект ослабления",
		de = "Schwächungseffekt",
		fr = "Effet d'affaiblissement",
		["zh-cn"] = "攻击削弱",
	},
}
