return {
	DEBUFF_STYLES = {
		bleed = {
			icon = "content/ui/materials/icons/presets/preset_13",
			colour = { 255, 255, 0, 0 },
			label = "Bleed",
			localization_key = "enemy_target_debuff_label_bleed",
		},
		fire = {
			icon = "content/ui/materials/icons/presets/preset_20",
			colour = { 255, 250, 150, 20 },
			label = "Fire",
			localization_key = "enemy_target_debuff_label_fire",
		},
		warp = {
			icon = "content/ui/materials/icons/circumstances/havoc/havoc_mutator_ember",
			colour = { 255, 120, 200, 255 },
			label = "Warp",
			localization_key = "enemy_target_debuff_label_warp",
		},
		shock = {
			icon = "content/ui/materials/icons/presets/preset_11",
			colour = { 255, 255, 255, 0 },
			label = "Electroshock",
			localization_key = "enemy_target_debuff_label_shock",
		},
		toxin = {
			icon = "content/ui/materials/hud/interactions/icons/pocketable_syringe_corruption",
			colour = { 255, 50, 255, 20 },
			label = "Poison",
			localization_key = "enemy_target_debuff_label_toxin",
		},
		rending = {
			icon = "content/ui/materials/icons/circumstances/havoc/havoc_mutator_rotten_armor",
			colour = { 255, 172, 115, 255 },
			label = "Armor Break",
			localization_key = "enemy_target_debuff_label_rending",
		},
		stagger = {
			icon = "content/ui/materials/icons/throwables/hud/small/party_non_grenade",
			colour = { 255, 100, 200, 255 },
			label = "Stun",
			localization_key = "enemy_target_debuff_label_stagger",
		},
		blind = {
			icon = "content/ui/materials/icons/circumstances/ventilation_purge_01",
			colour = { 255, 200, 200, 200 },
			label = "Smoke Effect",
			localization_key = "enemy_target_debuff_label_blind",
		},
		damage_taken = {
			icon = "content/ui/materials/hud/interactions/icons/pocketable_syringe_power",
			colour = { 255, 255, 185, 100 },
			label = "More Damage",
			localization_key = "enemy_target_debuff_label_damage_taken",
		},
		melee_damage_taken = {
			icon = "content/ui/materials/icons/weapons/actions/melee",
			colour = { 255, 255, 242, 99 },
			label = "More Melee Damage",
			localization_key = "enemy_target_debuff_label_melee_damage_taken",
		},
		stagger_damage = {
			icon = "content/ui/materials/icons/weapons/actions/melee_hand",
			colour = { 255, 124, 227, 187 },
			label = "More Stunned Damage",
			localization_key = "enemy_target_debuff_label_stagger_damage",
		},
		impact_taken = {
			icon = "content/ui/materials/icons/presets/preset_18",
			colour = { 255, 124, 227, 187 },
			label = "Easier to Stun",
			localization_key = "enemy_target_debuff_label_impact_taken",
		},
		count_as_stagger = {
			icon = "content/ui/materials/icons/throwables/hud/small/party_non_grenade",
			colour = { 255, 100, 200, 255 },
			label = "Stun Effect",
			localization_key = "enemy_target_debuff_label_count_as_stagger",
		},
		damage_dealt_down = {
			icon = "content/ui/materials/icons/circumstances/havoc/havoc_mutator_rampaging_enemies",
			colour = { 255, 0, 144, 255 },
			label = "Weakening Effect",
			localization_key = "enemy_target_debuff_label_damage_dealt_down",
		},
	},
	DEBUFFS = {
		bleed = { name = "bleed", type = "dot", group = "bleed" },
		flamer_assault = { name = "flamer_assault", type = "dot", group = "fire" },
		flame_grenade_liquid_area = { name = "flame_grenade_liquid_area", type = "dot", group = "fire" },
		warp_fire = { name = "warp_fire", type = "dot", group = "warp" },
		shock_effect = { name = "shock_effect", type = "dot", group = "shock" },
		neurotoxin_interval_buff = { name = "neurotoxin_interval_buff", type = "dot", group = "toxin" },
		neurotoxin_interval_buff2 = { name = "neurotoxin_interval_buff2", type = "dot", group = "toxin" },
		neurotoxin_interval_buff3 = { name = "neurotoxin_interval_buff3", type = "dot", group = "toxin" },
		exploding_toxin_interval_buff = { name = "exploding_toxin_interval_buff", type = "dot", group = "toxin" },
		rending_debuff = { name = "rending_debuff", type = "utility", group = "rending" },
		rending_debuff_medium = { name = "rending_debuff_medium", type = "utility", group = "rending" },
		rending_burn_debuff = { name = "rending_burn_debuff", type = "utility", group = "rending" },
		saw_rending_debuff = { name = "saw_rending_debuff", type = "utility", group = "rending" },
		increase_impact_received_while_staggered = {
			name = "increase_impact_received_while_staggered",
			type = "utility",
			group = "impact_taken",
		},
		increase_damage_received_while_staggered = {
			name = "increase_damage_received_while_staggered",
			type = "utility",
			group = "stagger_damage",
		},
		power_maul_sticky_tick = { name = "power_maul_sticky_tick", type = "utility", group = "stagger" },
		increase_damage_taken = { name = "increase_damage_taken", type = "utility", group = "damage_taken" },
		psyker_force_staff_quick_attack_debuff = {
			name = "psyker_force_staff_quick_attack_debuff",
			type = "utility",
			group = "warp",
		},
		psyker_heavy_swings_shock = { name = "psyker_heavy_swings_shock", type = "utility", group = "shock" },
		psyker_heavy_swings_shock_improved = {
			name = "psyker_heavy_swings_shock_improved",
			type = "utility",
			group = "shock",
		},
		psyker_protectorate_spread_chain_lightning_interval = {
			name = "psyker_protectorate_spread_chain_lightning_interval",
			type = "utility",
			group = "shock",
		},
		psyker_protectorate_spread_chain_lightning_interval_improved = {
			name = "psyker_protectorate_spread_chain_lightning_interval_improved",
			type = "utility",
			group = "shock",
		},
		psyker_protectorate_spread_charged_chain_lightning_interval = {
			name = "psyker_protectorate_spread_charged_chain_lightning_interval",
			type = "utility",
			group = "shock",
		},
		psyker_protectorate_spread_charged_chain_lightning_interval_improved = {
			name = "psyker_protectorate_spread_charged_chain_lightning_interval_improved",
			type = "utility",
			group = "shock",
		},
		psyker_discharge_damage_debuff = {
			name = "psyker_discharge_damage_debuff",
			type = "utility",
			group = "damage_taken",
		},
		ogryn_recieve_damage_taken_increase_debuff = {
			name = "ogryn_recieve_damage_taken_increase_debuff",
			type = "utility",
			group = "damage_taken",
		},
		ogryn_taunt_increased_damage_taken_buff = {
			name = "ogryn_taunt_increased_damage_taken_buff",
			type = "utility",
			group = "damage_taken",
		},
		ogryn_staggering_damage_taken_increase = {
			name = "ogryn_staggering_damage_taken_increase",
			type = "utility",
			group = "melee_damage_taken",
		},
		veteran_improved_tag_debuff = {
			name = "veteran_improved_tag_debuff",
			type = "utility",
			group = "damage_taken",
		},
		zealot_bled_enemies_take_more_damage_effect = {
			name = "zealot_bled_enemies_take_more_damage_effect",
			type = "utility",
			group = "damage_taken",
		},
		adamant_drone_enemy_debuff = { name = "adamant_drone_enemy_debuff", type = "utility", group = "damage_taken" },
		adamant_drone_talent_debuff = {
			name = "adamant_drone_talent_debuff",
			type = "utility",
			group = "damage_dealt_down",
		},
		adamant_melee_weakspot_hits_count_as_stagger_debuff = {
			name = "adamant_melee_weakspot_hits_count_as_stagger_debuff",
			type = "utility",
			group = "count_as_stagger",
		},
		adamant_staggered_enemies_deal_less_damage_debuff = {
			name = "adamant_staggered_enemies_deal_less_damage_debuff",
			type = "utility",
			group = "damage_dealt_down",
		},
		adamant_staggering_increases_damage_taken = {
			name = "adamant_staggering_increases_damage_taken",
			type = "utility",
			group = "stagger_damage",
		},
		broker_punk_rage_improved_shout_debuff = {
			name = "broker_punk_rage_improved_shout_debuff",
			type = "utility",
			group = "damage_dealt_down",
		},
		shock_grenade_interval = { name = "shock_grenade_interval", type = "utility", group = "stagger" },
		in_smoke_fog = { name = "in_smoke_fog", type = "utility", group = "blind" },
		toxin_damage_debuff = { name = "toxin_damage_debuff", type = "utility", group = "damage_dealt_down" },
		toxin_damage_debuff_monster = { name = "toxin_damage_debuff_monster", type = "utility", group = "damage_dealt_down" },
		broker_passive_toxin_infected_enemies_take_increased_damage_debuff = {
			name = "broker_passive_toxin_infected_enemies_take_increased_damage_debuff",
			type = "utility",
			group = "damage_taken",
		},
	},
}
