-- Единый источник значений по умолчанию: data.lua, systems/settings.lua, сброс из DivisionHUD.lua
return {
	position_x = 960,
	position_y = 540,
	opacity = 1.0,
	show_stamina_bar = true,
	show_toughness_bar = true,
	show_health_bar = true,
	show_ability_timer = true,
	dynamic_hud = true,
	dynamic_hud_strength = 110,
	dynamic_hud_pitch_ratio = 1,
	dynamic_hud_decay = 11,
	dynamic_hud_max_offset = 100,
	hide_vanilla_team_panel_local = false,
	hide_vanilla_stamina_area = false,
	hide_vanilla_dodge_area = false,
	hide_vanilla_weapon_pivot = false,
	hide_vanilla_combat_ability_slot = false,
	divisionhud_reset_all_settings = 0,
}
